/*
 * This file was generated automatically by xsubpp version 1.9507 from the 
 * contents of Blowfish.xs. Do not edit this file, edit Blowfish.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Blowfish.xs"
/*
 *	Copyright (C) 1995, 1996 Systemics Ltd (http://www.systemics.com/)
 *
 *      Code Modfifications Copyright (C) 2000 W3Works, LLC (http://www.w3works.co/)
 *	All rights reserved.
 */

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "blowfish.h"

/*  thanks to LDS */
#ifndef sv_undef
#define sv_undef PL_sv_undef
#endif

#line 29 "Blowfish.c"
XS(XS_Crypt__Blowfish_init)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Crypt::Blowfish::init(key)");
    {
	unsigned char *	key;
	STRLEN	key_len;
	char *	RETVAL;
#line 29 "Blowfish.xs"
	{
		/*
		* What should this length be???
		*/
		char ks[8192];

		key = (unsigned char *) SvPV(ST(0), key_len);
		if (key_len < 8 || key_len > 56)
			croak("Invalid length key");

		if (blowfish_make_bfkey(key, key_len, ks))
			croak("Error creating key schedule");

		ST(0) = sv_2mortal(newSVpv(ks, sizeof(ks)));
	}
#line 55 "Blowfish.c"
    }
    XSRETURN(1);
}

XS(XS_Crypt__Blowfish_crypt)
{
    dXSARGS;
    if (items != 4)
	croak("Usage: Crypt::Blowfish::crypt(input, output, ks, dir)");
    {
	char *	input;
	SV *	output = ST(1);
	char *	ks;
	STRLEN	input_len;
	STRLEN	output_len;
	STRLEN	ks_len;
	int	dir = (int)SvIV(ST(3));
#line 55 "Blowfish.xs"
	{
		input = (char *) SvPV(ST(0), input_len);
		if (input_len != 8)
			croak("input must be 8 bytes long");

		ks = (char *) SvPV(ST(2), ks_len);

		if (output == &sv_undef)
			output = sv_newmortal();
		output_len = 8;

		if (!SvUPGRADE(output, SVt_PV))
			croak("cannot use output argument as lvalue");

		/* blowfish_crypt_8bytes(input, SvGROW(output, 8), ks, dir); */
		/* HP-UX (HP cc) fix below, thanks Addi! */
		blowfish_crypt_8bytes( (unsigned char*)input, (unsigned char*)SvGROW(output, 8), ks, (short)dir);

		SvCUR_set(output, output_len);
		*SvEND(output) = '\0';
		(void) SvPOK_only(output);
		SvTAINT(output);

		ST(0) = output;
	}
#line 99 "Blowfish.c"
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Crypt__Blowfish)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Crypt::Blowfish::init", XS_Crypt__Blowfish_init, file);
        newXS("Crypt::Blowfish::crypt", XS_Crypt__Blowfish_crypt, file);
    XSRETURN_YES;
}

