-- created by Oraschemadoc Mon Aug 31 10:54:23 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE UNIQUE INDEX "MIM1"."RHN_SRVPO_SERV_ORIG_PR_ID_UQ" ON "MIM1"."RHN_SERVICE_PROBE_ORIGINS" ("ORIGIN_PROBE_ID", "SERVICE_PROBE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
