# Makefile for the action handlers module
#

TOP	= ../..
SUBDIR	= server/action

SPACEWALK_FILES	= __init__ configfiles kickstart kickstart_guest packages errata hardware reboot \
          rollback activation script rhnsd rhn_applet virt kickstart_host \
          utils scap image clientcert

include $(TOP)/Makefile.defs

