# Makefile for the action handlers module
#
# $Id$

TOP	= ../..
SUBDIR	= server/action

SPACEWALK_FILES	= __init__ configfiles kickstart kickstart_guest packages errata hardware reboot \
          rollback activation solarispkgs script rhnsd rhn_applet virt kickstart_host \
          utils scap

include $(TOP)/Makefile.defs

