# Kickstart file automatically generated by anaconda.

upgrade
nfs --server=shell.boston.redhat.com --dir=/mnt/redhat/iso/f7-64
lang en_US.UTF-8
keyboard us
xconfig --startxonboot
network --device eth0 --bootproto dhcp --hostname manus.boston.redhat.com
rootpw --iscrypted $1$XfFmKil8$NyKJOMScsYgSE53j8/Lq51
firewall --enabled --port=22:tcp
authconfig --enableshadow --enablemd5
selinux --enforcing
timezone --utc America/New_York
bootloader --location=mbr --driveorder=sda,sdb --append="rhgb quiet"
# The following is the partition information you requested
# Note that any partitions you deleted are not expressed
# here so unless you clear all partitions first, this is
# not guaranteed to work
#clearpart --linux --drives=sda,sdb
#part /boot --fstype ext3 --size=100 --ondisk=sda
#part pv.27 --size=0 --grow --ondisk=sdb
#part pv.26 --size=0 --grow --ondisk=sda
#volgroup VolGroup00 --pesize=32768 pv.27 pv.26
#logvol / --fstype ext3 --name=LogVol00 --vgname=VolGroup00 --size=1024 --grow
#logvol swap --fstype swap --name=LogVol01 --vgname=VolGroup00 --size=1000 --grow --maxsize=1984

%packages
@ Base