# Makefile for the rhnServer module
#

TOP     = ../..
SUBDIR	= server/rhnServer

SPACEWALK_FILES	= __init__ server_certificate server_hardware \
	  server_packages server_history server_class \
	  server_class server_wrapper server_lib server_route server_token \
          server_kickstart search_notify

include $(TOP)/Makefile.defs
