# Makefile for the rhnServer module
#
# $Id$

TOP     = ../..
SUBDIR	= server/rhnServer

FILES	= __init__ server_certificate server_hardware \
	  server_packages server_history server_class \
	  server_class server_wrapper server_lib server_route server_token \
          satellite_cert server_kickstart server_solarispatches search_notify

include $(TOP)/Makefile.defs
