# Makefile for the import code
#
# $Id$

TOP	= ../..

SUBDIR	= server/importlib

FILES	= __init__ archImport backendLib backendOracle backend  \
            blacklistImport bugzillaErrataImport bugzillaErrataSource \
            channelImport errataCache errataImport headerSource importLib \
	    kickstartImport mpmSource \
            packageImport productNamesImport packageUpload userAuth

include $(TOP)/Makefile.defs
