# Makefile for the import code
#

TOP	= ../..

SUBDIR	= server/importlib

SPACEWALK_FILES	= __init__ archImport backendLib backendOracle backend backend_checker \
            channelImport debPackage errataCache errataImport headerSource importLib \
	    kickstartImport mpmSource orgImport contentSourcesImport \
            packageImport productNamesImport packageUpload userAuth

include $(TOP)/Makefile.defs
