#
# Copyright (c) 2008 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public License,
# version 2 (GPLv2). There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
# along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
# 
# Red Hat trademarks are not licensed under GPLv2. No permission is
# granted to use or replicate Red Hat trademarks that are incorporated
# in this software or its documentation. 
#

err = {
 'advisory_name'    : 'MISA-2006:0009',
 'revision'         : 3,
 'author': '',
 'cross': '',
 'cve': 'CAN-2005-2337 CAN-2005-2978',
 'depends': [],
 'description': 'The hwdata package contains various hardware identification and configuration\ndata, such as the pci.ids database and the XFree86 compatibility database.\n\nThe pci.ids and MonitorsDB files have been updated with new monitor\ndescriptions for manual monitor configuration, and new PCI ID descriptions\nused in printing descriptions of PCI hardware.\n\nAll users should upgrade to this updated package.',
 'errata_files': [{'arch': 'SRPMS',
                   'ftppath': '/ftp/pub/redhat/linux/updates/enterprise/3AS/en/os/SRPMS/hwdata-0.101.20-1.src.rpm',
                   'fullpath': '/mnt/redhat/beehive/updates/dist/3AS/SRPMS/hwdata-0.101.20-1.src.rpm',
                   'md5sum': 'ecb8ea5eb95679634f73675b5627f267',
                   'package': 'hwdata-0.101.20-1.src.rpm',
                   'release': '3AS',
                   'rhn_beta_channel': '',
                   'rhn_channel': [],
                   'selected': 1,
                   'signed': ['security']},
                  {'arch': 'noarch',
                   'ftppath': '/ftp/pub/redhat/linux/updates/enterprise/3AS/en/os/noarch/hwdata-0.101.20-1.noarch.rpm',
                   'fullpath': '/mnt/redhat/beehive/updates/dist/3AS/noarch/hwdata-0.101.20-1.noarch.rpm',
                   'md5sum': 'a4fd0744d18bdf17740056cf4c3cd468',
                   'package': 'hwdata-0.101.20-1.noarch.rpm',
                   'release': '3AS',
                   'rhn_beta_channel': '',
                   'rhn_channel': ['rhel-i386-as-3', 'rhel-i386-es-3'],
                   'selected': 1,
                   'signed': ['security']},
                  {'arch': 'SRPMS',
                   'ftppath': '/ftp/pub/redhat/linux/updates/enterprise/3ES/en/os/SRPMS/hwdata-0.101.20-1.src.rpm',
                   'fullpath': '/mnt/redhat/beehive/updates/dist/3ES/SRPMS/hwdata-0.101.20-1.src.rpm',
                   'md5sum': 'ecb8ea5eb95679634f73675b5627f267',
                   'package': 'hwdata-0.101.20-1.src.rpm',
                   'release': '3ES',
                   'rhn_beta_channel': '',
                   'rhn_channel': [],
                   'selected': 1,
                   'signed': ['security']},
                  {'arch': 'noarch',
                   'ftppath': '/ftp/pub/redhat/linux/updates/enterprise/3ES/en/os/noarch/hwdata-0.101.20-1.noarch.rpm',
                   'fullpath': '/mnt/redhat/beehive/updates/dist/3ES/noarch/hwdata-0.101.20-1.noarch.rpm',
                   'md5sum': 'a4fd0744d18bdf17740056cf4c3cd468',
                   'package': 'hwdata-0.101.20-1.noarch.rpm',
                   'release': '3ES',
                   'rhn_beta_channel': '',
                   'rhn_channel': ['rhel-i386-as-3', 'rhel-i386-es-3'],
                   'selected': 1,
                   'signed': ['security']},
                  {'arch': 'SRPMS',
                   'ftppath': '/ftp/pub/redhat/linux/updates/enterprise/3WS/en/os/SRPMS/hwdata-0.101.20-1.src.rpm',
                   'fullpath': '/mnt/redhat/beehive/updates/dist/3WS/SRPMS/hwdata-0.101.20-1.src.rpm',
                   'md5sum': 'ecb8ea5eb95679634f73675b5627f267',
                   'package': 'hwdata-0.101.20-1.src.rpm',
                   'release': '3WS',
                   'rhn_beta_channel': '',
                   'rhn_channel': [],
                   'selected': 1,
                   'signed': ['security']},
                  {'arch': 'noarch',
                   'ftppath': '/ftp/pub/redhat/linux/updates/enterprise/3WS/en/os/noarch/hwdata-0.101.20-1.noarch.rpm',
                   'fullpath': '/mnt/redhat/beehive/updates/dist/3WS/noarch/hwdata-0.101.20-1.noarch.rpm',
                   'md5sum': 'a4fd0744d18bdf17740056cf4c3cd468',
                   'package': 'hwdata-0.101.20-1.noarch.rpm',
                   'release': '3WS',
                   'rhn_beta_channel': '',
                   'rhn_channel': ['rhel-i386-as-3', 'rhel-i386-es-3'],
                   'selected': 1,
                   'signed': ['security']}],
 'errata_id': 86,
 'errata_type': 'RHEA',
 'erratum_deployed_by': 'misa@redhat.com',
 'ftp_files': [],
 'ftp_path': '',
 'groups': ['RHEL3-QU2'],
 'id': 1200,
 'idsfixed': [92322, 109341, 104069, 112557],
 'idsfixedlist': ['92322 - RHEL3: Need to update MonitorsDB in distribution',
                  '109341 - RHEL 3 U2:  Support for new Dell monitors',
                  "104069 - pciutils database doesn't know about SmartArray 64xx",
                  '112557 - [PATCH] LTC5605 - e1000 82545 chipsets not in pci.ids'],
 'issue_date': '2004-05-10',
 'keywords': [],
 'md5list': ['ecb8ea5eb95679634f73675b5627f267 3AS/en/os/SRPMS/hwdata-0.101.20-1.src.rpm',
             'a4fd0744d18bdf17740056cf4c3cd468 3AS/en/os/noarch/hwdata-0.101.20-1.noarch.rpm',
             'ecb8ea5eb95679634f73675b5627f267 3ES/en/os/SRPMS/hwdata-0.101.20-1.src.rpm',
             'a4fd0744d18bdf17740056cf4c3cd468 3ES/en/os/noarch/hwdata-0.101.20-1.noarch.rpm',
             'ecb8ea5eb95679634f73675b5627f267 3WS/en/os/SRPMS/hwdata-0.101.20-1.src.rpm',
             'a4fd0744d18bdf17740056cf4c3cd468 3WS/en/os/noarch/hwdata-0.101.20-1.noarch.rpm'],
 'modbugzilla': 0,
 'obsoletes': '',
 'package_map': ['3AS SRPMS hwdata-0.101.20-1.src.rpm',
                 '3AS noarch hwdata-0.101.20-1.noarch.rpm',
                 '3ES SRPMS hwdata-0.101.20-1.src.rpm',
                 '3ES noarch hwdata-0.101.20-1.noarch.rpm',
                 '3WS SRPMS hwdata-0.101.20-1.src.rpm',
                 '3WS noarch hwdata-0.101.20-1.noarch.rpm'],
 'package_path': '/mnt/redhat/beehive/updates/dist',
 'packages': 'hwdata-0.101.20-1',
 'product': 'Red Hat Enterprise Linux',
 'reference': '',
 'relarchlist': ['Red Hat Enterprise Linux AS version 3 - noarch',
                 'Red Hat Enterprise Linux ES version 3 - noarch',
                 'Red Hat Enterprise Linux WS version 3 - noarch'],
 'release_date': '',
 'reporter': 4,
 'rhnonly': 0,
 'rpmlist': 'Red Hat Enterprise Linux AS version 3:\n\nSRPMS:\nftp://updates.redhat.com/enterprise/3AS/en/os/SRPMS/hwdata-0.101.20-1.src.rpm\n\nnoarch:\nAvailable from Red Hat Network: hwdata-0.101.20-1.noarch.rpm\n\nRed Hat Enterprise Linux ES version 3:\n\nSRPMS:\nftp://updates.redhat.com/enterprise/3ES/en/os/SRPMS/hwdata-0.101.20-1.src.rpm\n\nnoarch:\nAvailable from Red Hat Network: hwdata-0.101.20-1.noarch.rpm\n\nRed Hat Enterprise Linux WS version 3:\n\nSRPMS:\nftp://updates.redhat.com/enterprise/3WS/en/os/SRPMS/hwdata-0.101.20-1.src.rpm\n\nnoarch:\nAvailable from Red Hat Network: hwdata-0.101.20-1.noarch.rpm\n\n',
 'solution': 'Before applying this update, make sure all previously released errata\nrelevant to your system have been applied.\n\nTo update all RPMs for your particular architecture, run:\n\nrpm -Fvh [filenames]\n\nwhere [filenames] is a list of the RPMs you wish to upgrade.  Only those\nRPMs which are currently installed will be updated.  Those RPMs which are\nnot installed but included in the list will not be updated.  Note that you\ncan also use wildcards (*.rpm) if your current directory *only* contains the\ndesired RPMs.\n\nPlease note that this update is also available via Red Hat Network.  Many\npeople find this an easier way to apply updates.  To use Red Hat Network,\nlaunch the Red Hat Update Agent with the following command:\n\nup2date\n\nThis will start an interactive process that will result in the appropriate\nRPMs being upgraded on your system.\n\nIf up2date fails to connect to Red Hat Network due to SSL\nCertificate Errors, you need to install a version of the\nup2date client with an updated certificate.  The latest version of\nup2date is available from the Red Hat FTP site and may also be\ndownloaded directly from the RHN website:\n\nhttps://rhn.redhat.com/help/latest-up2date.pxt',
 'synopsis': 'Updated hwdata package available',
 'topic': 'An updated hwdata package that revises some manufacturer branding data is\nnow available.',
 'type': 'RHEA',
 'update_date': '2004-05-10'}
