# Makefile for the xmlrpc handlers
#

TOP	= ../..
SUBDIR	= server/handlers

FILES	= __init__

SUBDIRS = \
		  app \
		  applet \
		  config \
		  config_mgmt \
                  sat \
		  xmlrpc

include $(TOP)/Makefile.defs

