# Makefile for installation of the RHN server configuration files
#
# $Id$

# what is the backend top dir
TOP	= ..

INSTALL_FILES	= $(wildcard *.conf)
INSTALL_DEST	= /etc/rhn/default

include $(TOP)/Makefile.defs

install :: $(PREFIX)$(INSTALL_DEST)
