#!/bin/bash
#
# Monitoring   Startup script for Monitoring
#
# chkconfig: - 85 16
# description: NOCpulse Monitoring

### BEGIN INIT INFO
# Provides: Monitoring
# Required-Start: $local_fs $named $time
# Required-Stop: $local_fs $named $time
# Default-Stop: 0 1 6
# Short-Description: NOCpulse Monitoring
# Description: NOCpulse Monitoring 
### END INIT INFO

/usr/sbin/Monitoring $@

