#!/bin/bash
#
# Monitoring   Startup script for Monitoring Scout
#
# chkconfig: - 86 14
# description: NOCpulse Monitoring Scout

### BEGIN INIT INFO
# Provides: MonitoringScout
# Required-Start: $local_fs $named $time Monitoring
# Required-Stop: $local_fs $named $time Monitoring
# Default-Stop: 0 1 6
# Short-Description: NOCpulse Monitoring Scout
# Description: NOCpulse MonitoringScout 
### END INIT INFO

/usr/sbin/MonitoringScout $@

