#!/bin/sh
#
# Startup script for the NOCpulse Message Dequeuer
#
# chkconfig: 345 85 15
# description: NOCpulse message dequeuer
# processname: dequeue


# Source function library.
. /etc/rc.d/init.d/functions

daemon_user=nocpulse

# Make sure we're in a directory readable by $daemon_user
cd /tmp

# See how we were called.
case "$1" in
  start)
	echo -n "Starting dequeuer: "
	/opt/home/nocpulse/bin/gogo.pl --user $daemon_user --hbfile=/opt/home/nocpulse/var/dequeue.log --hbfreq=60 /opt/home/nocpulse/bin/dequeue &
	echo_success
	echo
	;;
  stop)
  	/opt/home/nocpulse/bin/gogo.pl --kill dequeue
	exit $?
	;;
  status)
  	/opt/home/nocpulse/bin/gogo.pl --check dequeue
	exit $?
	;;
  restart)
	$0 stop
	$0 start
	exit $?
	;;
  *)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
esac

exit 0
