Name:           perl-Satcon
Summary:        Framework for configuration files
Version:        1.3
Release:        10%{?dist}
License:        GPLv2
Group:          Applications/System
# This src.rpm is cannonical upstream
# You can obtain it using this set of commands
# git clone git://git.fedorahosted.org/git/spacewalk.git/
# cd projects/perl-Satcon
# make test-srpm
URL:            https://fedorahosted.org/spacewalk
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Source0:        %{name}-%{version}.tar.gz

%description
Framework for generating config files during installation.
This package include Satcon perl module and supporting applications.

%prep
%setup -q

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc README
%{perl_vendorlib}/*
%{_bindir}/*

%changelog
* Mon Aug  4 2008 Jan Pazdziora 1.3-10
- rebuild
* Fri Apr 27 2007 Matthew Davis <mdavis@redhat.com> - 1.3-7
- Backup config files
* Tue Jul 20 2004 Robin Norwood <rnorwood@redhat.com> - 1.2
- New Satcon version - 1.2
* Wed May 05 2004 Chip Turner <cturner@redhat.com> - 1.1-2
- Specfile autogenerated.
