#!/usr/bin/python
#
# Licensed under the GNU General Public License Version 3
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Copyright 2010 Aron Parsons <aron@redhat.com>
#

""" spacecmd - a command line interface to Spacewalk """

import logging, os, sys, xml, xmlrpclib
from optparse import Option, OptionParser

sys.path.append('/usr/share/rhn')
from spacecmd.SpacewalkShell import SpacewalkShell

if __name__ == '__main__':
    optionsTable = [
        Option('-u', '--username', action='store',
               help='use this username to connect to the server'),
        Option('-p', '--password', action='store',
               help='use this password to connect to the server'),
        Option('-s', '--server', action='store', default='localhost',
               help='connect to this server [default: %default]'),
        Option('--nocache', action='store_true',
                help='do not create a username/password cache'),
        Option('--nossl', action='store_true',
               help='use HTTP instead of HTTPS'),
        Option('--nohistory', action='store_true',
                help='do not store command history in ~/.spacecmd_history'),
        Option('-y', '--yes', action='store_true',
               help='answer yes for all questions'),
        Option('-q', '--quiet', action='store_true',
               help='print only error messages'),
        Option('-v', '--verbose', action='store_true',
               help='print informational messages'),
        Option('-d', '--debug', action='store_true',
               help='print debug messages'),
    ]

    usage = 'usage: %prog [options] [command]'
    parser = OptionParser(option_list=optionsTable, usage=usage)
    (options, args) = parser.parse_args()

    if options.debug:
        level = logging.DEBUG
    elif options.verbose:
        level = logging.INFO
    elif options.quiet:
        level = logging.ERROR
    else:
        level = logging.WARNING

    logging.basicConfig(level=level, format='%(levelname)s: %(message)s')

    shell = SpacewalkShell(options)

    if len(args):
        try:
            # run a single command given on the command line
            shell.preloop()
            shell.onecmd(shell.precmd(' '.join(args), True))
        except xmlrpclib.Fault, err:
            logging.debug(sys.exc_info())
            message = ' '.join(err.faultString.split(':')[-2:])
            logging.error(message)
        except KeyboardInterrupt:
            print
    else:
        while True:
            try:
                try:
                    shell.cmdloop()
                except xmlrpclib.Fault, err:
                    try:
                        logging.debug(sys.exc_info())
                        message = ' '.join(err.faultString.split(':')[-2:])
                        logging.error(message)
                    except:
                        # a few XML-RPC messages are different
                        logging.error(err.faultString)
                except xml.parsers.expat.ExpatError:
                    logging.error(sys.exc_info()[1])
                    logging.debug(sys.exc_info())
                except KeyboardInterrupt:
                    print
            finally:
                shell.intro = ''

# vim:ts=4:expandtab:
