#!/usr/bin/python

""" spacecmd - Interactive, console prompt to Spacewalk

Author: Aron Parsons <aron@redhat.com> -or- <aronparsons@gmail.com>
License: GPLv3+
"""

# TODO for Spacewalk:
# configchannel.listSubscribedSystems
# configchannel - show channel ranks
# configchannel.lookupFileInfo - returns null if invalid files is passed
# kickstart.profile.system - partitions not being returned

import logging, os, sys, xml, xmlrpclib
from optparse import Option, OptionParser

sys.path.append(os.getcwd())
from SpacewalkShell import SpacewalkShell

if __name__ == "__main__":
    optionsTable = [
        Option('-u', '--username', action='store',
               help='Use this username to connect to RHN/Satellite'),
        Option('-p', '--password', action='store',
               help='Use this password to connect to RHN/Satellite'),
        Option('--server', action='store', default="localhost", 
               help='Connect to this server (http[s]://<hostname>/APP)'),
        Option('--nocache', action='store_true',
                help="Do not create a username/password cache"),
        Option('--nossl', action='store_true',
               help="Use HTTP instead of HTTPS"),
        Option('--nohistory', action='store_true',
                help="Do not store command history in ~/.spacewalk_history"),
        Option('-q', '--quiet', action='store_true',
               help="Only print error messages"),
        Option('-d', '--debug', action='store_true',
               help="Enable debug logging"),
    ]
    
    parser = OptionParser(option_list=optionsTable)
    (options, args) = parser.parse_args()
 
    if options.debug:
        log_level = logging.DEBUG
    elif options.quiet:
        log_level = logging.ERROR
    else:
        log_level = logging.INFO

    logging.basicConfig(level=log_level, format="%(levelname)s: %(message)s")

    shell = SpacewalkShell(options)

    if len(args) > 0:
        # run a single command given on the command line
        shell.preloop()
        shell.onecmd(shell.precmd(' '.join(args), True))
    else:
        while True:
            try:
                shell.cmdloop()
            except xmlrpclib.Fault, err:
                shell.intro = ''

                try:
                    logging.debug(sys.exc_info())
                    logging.error(err.faultString.rsplit(': ', 1)[1])
                except:
                    # a few XML-RPC messages are different
                    logging.error(err.faultString)
            except xml.parsers.expat.ExpatError:
                shell.intro = ''
                logging.error(sys.exc_info()[1])
                logging.debug(sys.exc_info())
            except KeyboardInterrupt:
                shell.intro = ''
                print

# vim:ts=4:expandtab:
