# Makefile for registration server for RHNS
#
# $Id$

# what is the backend top dir
TOP     = ..

# Specific stuff
SUBDIR		= config_common
FILES           = __init__ cfg_exceptions \
                  file_utils deploy \
                  handler_base local_config \
		  repository rhn_log rhn_main rhn_rpc \
                  utils transactions rpc_wrapper


include $(TOP)/Makefile.defs
