#!/bin/bash

NOTIFICATION_LOG_DIR=`/usr/bin/npConfigValue notification log_dir`
/usr/bin/log-remote-check --expr 'Started Alert' --lines 10000 --mins 15 --warn 1000 --crit 2000 $NOTIFICATION_LOG_DIR/notif-launcher.log
exit $?
