#!/bin/bash

NOTIFICATION_HOME=`/opt/home/nocpulse/bin/npConfigValue notification home`
$NOTIFICATION_HOME/scripts/log-remote-check --expr http --lines 10000 --mins 15 --warn 1000 --crit 2000 /var/tmp/enqueue.log
exit $?
