#!/usr/bin/perl

use strict;
use Data::Dumper;
use NOCpulse::Notif::Alert;

&help unless(@ARGV);

foreach (@ARGV) {
  my $alert=NOCpulse::Notif::Alert->from_file($_);
  print &Dumper($alert), "\n\n";
}

sub help {
  print "Usage: $0 filename [...filename]\n";
  print "$0 is a utility for displaying enqueued alerts in the notification system.\n"
}
