#!/usr/bin/perl

use strict;
use NOCpulse::Config;

my $CFG=NOCpulse::Config->new;

my $queue = { ALERTS   => 'alert_queue_dir',
              ACKS     => 'ack_queue_dir',
              REQUESTS => 'request_queue_dir' };

foreach (keys(%$queue)) {
  my $QUEUE_DIR = $CFG->get('notification', $queue->{$_});     # Dir for queuing alerts 

  chdir $QUEUE_DIR;
  my @files=glob("*");

  print "$_ QUEUE SIZE: ", scalar(@files), "\n";
}
