#!/usr/bin/perl

use strict;
use Data::Dumper;
use Storable;
use NOCpulse::Config;

my $np_cfg       = new NOCpulse::Config;
my $tmp_dir      = $np_cfg->get('notification','tmp_dir');
my $STATE_FILE   = "$tmp_dir/escalator.state";

my $escalator;
print "Escalator current state looks like this....\n";

eval {
$escalator=retrieve($STATE_FILE);
};

if ($@ || !$escalator) {
    print "Uh oh.  Something went wrong. $@"
} else {
    print &Dumper($escalator);
}
