# Makefile for the action handlers module
#
# $Id$

TOP	= ../..
SUBDIR	= server/action_extra_data

SPACEWALK_FILES	= __init__ configfiles kickstart kickstart_guest packages errata hardware reboot \
          rollback up2date_config solarispkgs script rhnsd rhn_applet virt kickstart_host scap image

include $(TOP)/Makefile.defs

