# Makefile for spacewalk-client-cert

ACTIONS		= clientcert
PYFILES		= $(addsuffix .py, $(ACTIONS))
CAPABILITY	= client-cert
OBJECTS		= $(PYFILES)

PREFIX		?=
ACTIONDIR	= $(PREFIX)$(PYTHONPATH)/rhn/actions
CAPSDIR		= $(PREFIX)/etc/sysconfig/rhn/clientCaps.d
INSTALL		= /usr/bin/install -c
FILE		= -m 644
DIR		= -m 755 --verbose -d


all: $(OBJECTS)

install: all
	$(INSTALL) $(DIR) $(ACTIONDIR) $(XSLTDIR) $(CAPSDIR)
	$(INSTALL) $(FILE) $(PYFILES) $(ACTIONDIR)
	$(INSTALL) $(FILE) $(CAPABILITY) $(CAPSDIR)

clean:
	@rm -rf *.pyc *~ .*~
