#!/usr/bin/python -u
""" activate an Spacewalk Proxy Server v3.6+

    Copyright (c) 2004--2015 Red Hat, Inc.
    All rights reserved.

    Author: Todd Warner <taw@redhat.com>
"""
#-------------------------------------------------------------------------------

## language imports
import sys
import os
import string


# set up paths:
sys.path.append('/usr/share/rhn')

mod_name = string.replace(os.path.basename(sys.argv[0]), '-', '_')
try:
    mod = __import__("installer." + mod_name)
except KeyboardInterrupt:
    sys.stderr.write("\nUser interrupted process.\n")
    sys.exit(0)
except ImportError, e:
    sys.stderr.write("Unable to load module %s\n" % mod_name)
    sys.stderr.write(str(e) + "\n")
    sys.exit(1)
mod = getattr(mod, mod_name)


#-------------------------------------------------------------------------------
if __name__ == '__main__':
    try:
        sys.exit(mod.main() or 0)
    except KeyboardInterrupt:
        sys.stderr.write("\nUser interrupted process.\n")
        sys.exit(0)
    except SystemExit:
        raise
    except:
        sys.stderr.write("\nERROR: unhandled exception occurred:\n")
        raise
#===============================================================================
