#!/usr/bin/perl
#
# Copyright (c) 2008 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public License,
# version 2 (GPLv2). There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
# along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
#
# Red Hat trademarks are not licensed under GPLv2. No permission is
# granted to use or replicate Red Hat trademarks that are incorporated
# in this software or its documentation.
#

use lib '/var/www/lib';

use RHN::Token;
use RHN::DB;
use RHN::User;
use RHN::Server;

if ($#ARGV < 1) {
    print "Usage: $0 database system-id\n";
    exit 1;
}

my $db = $ARGV[0];
my $sysid= $ARGV[1];

#my $sysid= "1004541246";

RHN::DB->set_default_handle($db);

my $server = RHN::Server->lookup(-id => $sysid);
my $name = $server->name;
print "$name\n";
