# Makefile for installation of the logrotation configuration files
#
# $Id$

# what is the backend top dir
TOP	= ..

INSTALL_FILES	= $(wildcard spacewalk-backend-*)
INSTALL_DEST	= /etc/logrotate.d

include $(TOP)/Makefile.defs
