#!/usr/bin/perl -w
use strict;
use lib '/tmp/lib';
use Dobby::DB;
use Dobby::Files;
use File::Basename qw/basename/;
use POSIX;

$|++;

my $d = new Dobby::DB;
$d->assert_local;

my $backup_dir = sprintf($d->config->get("backup_dir_format"), $d->sid, 1);

my $ts = shift;
die "No tablespace specified" unless $ts;

$d->tablespace_begin_backup($ts);

for my $df ($d->tablespace_datafiles($ts)) {
  my $file = $df->{FILENAME};
  my $dest = sprintf("%s/%s.gz", $backup_dir, basename($file));

  print "$file -> $dest ... ";
  Dobby::Files->gzip_copy($file, $dest);

  print "done.\n";
}

$d->tablespace_end_backup($ts);
