-- created by Oraschemadoc Fri Jan 22 13:39:49 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHN_UNITS"
   (	"UNIT_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"QUANTUM_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"UNIT_LABEL" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(200), 
	"TO_BASE_UNIT_FN" VARCHAR2(2000), 
	"FROM_BASE_UNIT_FN" VARCHAR2(2000), 
	"VALIDATE_FN" VARCHAR2(2000), 
	"LAST_UPDATE_USER" VARCHAR2(40), 
	"LAST_UPDATE_DATE" DATE, 
	 CONSTRAINT "RHN_UNITS_UNIT_ID_PK" PRIMARY KEY ("UNIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_UNITS_QNTA0_QUANTUM_ID_FK" FOREIGN KEY ("QUANTUM_ID")
	  REFERENCES "SPACEWALK"."RHN_QUANTA" ("QUANTUM_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
