-- created by Oraschemadoc Fri Mar  2 05:57:10 2012
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHN_DEPLOYED_PROBE" 
   (	"RECID" NUMBER(12,0) NOT NULL ENABLE, 
	"PROBE_TYPE" VARCHAR2(15) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255), 
	"CUSTOMER_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"COMMAND_ID" NUMBER(16,0) NOT NULL ENABLE, 
	"CONTACT_GROUP_ID" NUMBER(12,0), 
	"OS_ID" NUMBER(12,0), 
	"NOTIFY_CRITICAL" CHAR(1), 
	"NOTIFY_WARNING" CHAR(1), 
	"NOTIFY_RECOVERY" CHAR(1), 
	"NOTIFY_UNKNOWN" CHAR(1), 
	"NOTIFICATION_INTERVAL_MINUTES" NUMBER(16,0) NOT NULL ENABLE, 
	"CHECK_INTERVAL_MINUTES" NUMBER(16,0) NOT NULL ENABLE, 
	"RETRY_INTERVAL_MINUTES" NUMBER(16,0) NOT NULL ENABLE, 
	"MAX_ATTEMPTS" NUMBER(16,0), 
	"SAT_CLUSTER_ID" NUMBER(12,0), 
	"PARENT_PROBE_ID" NUMBER(12,0), 
	"LAST_UPDATE_USER" VARCHAR2(40), 
	"LAST_UPDATE_DATE" DATE, 
	 CONSTRAINT "RHN_DPROB_RECID_PK" PRIMARY KEY ("RECID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ENABLE ROW MOVEMENT 
 
/
