-- created by Oraschemadoc Fri Jan 22 13:39:46 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHN_REDIRECT_CRITERIA" 
   (	"RECID" NUMBER(12,0) NOT NULL ENABLE, 
	"REDIRECT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"MATCH_PARAM" VARCHAR2(255) NOT NULL ENABLE, 
	"MATCH_VALUE" VARCHAR2(255), 
	"INVERTED" CHAR(1) DEFAULT (0) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_RDRCR_RECID_PK" PRIMARY KEY ("RECID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_RDRCR_RDRCT_REDIRECT_ID_FK" FOREIGN KEY ("REDIRECT_ID")
	  REFERENCES "MIM_H1"."RHN_REDIRECTS" ("RECID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_RDRCR_RDRMT_MATCH_NM_FK" FOREIGN KEY ("MATCH_PARAM")
	  REFERENCES "MIM_H1"."RHN_REDIRECT_MATCH_TYPES" ("NAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
