-- created by Oraschemadoc Fri Mar  2 05:56:32 2012
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHNACTIONPACKAGEDELTA" 
   (	"ACTION_ID" NUMBER NOT NULL ENABLE, 
	"PACKAGE_DELTA_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACT_PD_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEWALK"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ACT_PD_PDID_FK" FOREIGN KEY ("PACKAGE_DELTA_ID")
	  REFERENCES "SPACEWALK"."RHNPACKAGEDELTA" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ENABLE ROW MOVEMENT 
 
/
