-- created by Oraschemadoc Fri Jan 22 13:39:00 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNACTIONPACKAGE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ACTION_ID" NUMBER NOT NULL ENABLE, 
	"PARAMETER" VARCHAR2(128) DEFAULT ('upgrade') NOT NULL ENABLE, 
	"NAME_ID" NUMBER NOT NULL ENABLE, 
	"EVR_ID" NUMBER, 
	"PACKAGE_ARCH_ID" NUMBER, 
	 CONSTRAINT "RHN_ACT_P_PARAM_CK" CHECK (parameter IN ( 'upgrade' , 'install' , 'remove' , 'downgrade' )) ENABLE, 
	 CONSTRAINT "RHN_ACT_P_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_ACT_P_ACT_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "MIM_H1"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ACT_P_NAME_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "MIM_H1"."RHNPACKAGENAME" ("ID") ENABLE, 
	 CONSTRAINT "RHN_ACT_P_EVR_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "MIM_H1"."RHNPACKAGEEVR" ("ID") ENABLE, 
	 CONSTRAINT "RHN_ACT_P_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "MIM_H1"."RHNPACKAGEARCH" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
