-- created by Oraschemadoc Fri Jan 22 13:39:04 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHNARCHTYPEACTIONS"
   (	"ARCH_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"ACTION_STYLE" VARCHAR2(64) NOT NULL ENABLE, 
	"ACTION_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ARCHTYPEACTS_ATID_FK" FOREIGN KEY ("ARCH_TYPE_ID")
	  REFERENCES "SPACEWALK"."RHNARCHTYPE" ("ID") ENABLE,
	 CONSTRAINT "RHN_ARCHTYPEACTS_ACTID_FK" FOREIGN KEY ("ACTION_TYPE_ID")
	  REFERENCES "SPACEWALK"."RHNACTIONTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
