-- created by Oraschemadoc Fri Jan 22 13:39:04 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNBLACKLISTOBSOLETES" 
   (	"NAME_ID" NUMBER NOT NULL ENABLE, 
	"EVR_ID" NUMBER NOT NULL ENABLE, 
	"PACKAGE_ARCH_ID" NUMBER NOT NULL ENABLE, 
	"IGNORE_NAME_ID" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_BL_OBS_NEPI_UQ" UNIQUE ("NAME_ID", "EVR_ID", "PACKAGE_ARCH_ID", "IGNORE_NAME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_BL_OBS_NID_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "MIM_H1"."RHNPACKAGENAME" ("ID") ENABLE, 
	 CONSTRAINT "RHN_BL_OBS_EID_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "MIM_H1"."RHNPACKAGEEVR" ("ID") ENABLE, 
	 CONSTRAINT "RHN_BL_OBS_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "MIM_H1"."RHNPACKAGEARCH" ("ID") ENABLE, 
	 CONSTRAINT "RHN_BL_OBS_INID_FK" FOREIGN KEY ("IGNORE_NAME_ID")
	  REFERENCES "MIM_H1"."RHNPACKAGENAME" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
