-- created by Oraschemadoc Fri Jan 22 13:39:04 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNBEEHIVEPATHMAP" 
   (	"PATH" VARCHAR2(128) NOT NULL ENABLE, 
	"BEEHIVE_PATH" VARCHAR2(128) NOT NULL ENABLE, 
	"FTP_PATH" VARCHAR2(128) NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (SYSDATE), 
	"MODIFIED" DATE DEFAULT (SYSDATE), 
	 CONSTRAINT "RHN_BEEHIVE_PATH_MAP_P_PK" PRIMARY KEY ("PATH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
