-- created by Oraschemadoc Fri Jan 22 13:39:07 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNCHECKSUM" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CHECKSUM_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"CHECKSUM" VARCHAR2(128) NOT NULL ENABLE, 
	 CONSTRAINT "RHNCHECKSUM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHNCHECKSUM_TYPEID_FK" FOREIGN KEY ("CHECKSUM_TYPE_ID")
	  REFERENCES "MIM_H1"."RHNCHECKSUMTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
