-- created by Oraschemadoc Fri Jan 22 13:39:05 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNCHANNELFAMILYMEMBERS" 
   (	"CHANNEL_ID" NUMBER NOT NULL ENABLE, 
	"CHANNEL_FAMILY_ID" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CF_MEMBERS_C_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "MIM_H1"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_CF_FAMILY_FK" FOREIGN KEY ("CHANNEL_FAMILY_ID")
	  REFERENCES "MIM_H1"."RHNCHANNELFAMILY" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
