-- created by Oraschemadoc Fri Mar  2 05:56:38 2012
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHNCONTENTSOURCEFILTER" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SOURCE_ID" NUMBER, 
	"SORT_ORDER" NUMBER NOT NULL ENABLE, 
	"FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"FILTER" VARCHAR2(4000) NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CHECK (flag in ('+','-')) ENABLE, 
	 CONSTRAINT "RHN_CSF_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RHN_CSF_SOURCE_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SPACEWALK"."RHNCONTENTSOURCE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ENABLE ROW MOVEMENT 
 
/
