-- created by Oraschemadoc Fri Jan 22 13:39:17 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNKICKSTARTSESSIONHISTORY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"KICKSTART_SESSION_ID" NUMBER NOT NULL ENABLE, 
	"ACTION_ID" NUMBER, 
	"STATE_ID" NUMBER NOT NULL ENABLE, 
	"TIME" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(4000), 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_KS_SESSIONHIST_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_KS_SESSIONHIST_KSID_FK" FOREIGN KEY ("KICKSTART_SESSION_ID")
	  REFERENCES "MIM_H1"."RHNKICKSTARTSESSION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_KS_SESSIONHIST_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "MIM_H1"."RHNACTION" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_KS_SESSIONHIST_STAT_FK" FOREIGN KEY ("STATE_ID")
	  REFERENCES "MIM_H1"."RHNKICKSTARTSESSIONSTATE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
