-- created by Oraschemadoc Fri Jan 22 13:39:18 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNMESSAGE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MESSAGE_TYPE" NUMBER NOT NULL ENABLE, 
	"PRIORITY" NUMBER DEFAULT (0) NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_M_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_M_MT_FK" FOREIGN KEY ("MESSAGE_TYPE")
	  REFERENCES "MIM_H1"."RHNMESSAGETYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_M_PRIORITY_FK" FOREIGN KEY ("PRIORITY")
	  REFERENCES "MIM_H1"."RHNMESSAGEPRIORITY" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
