-- created by Oraschemadoc Fri Jan 22 13:39:19 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNORGENTITLEMENTS" 
   (	"ORG_ID" NUMBER NOT NULL ENABLE, 
	"ENTITLEMENT_ID" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ORG_ENT_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "MIM_H1"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ORG_ENT_EID_FK" FOREIGN KEY ("ENTITLEMENT_ID")
	  REFERENCES "MIM_H1"."RHNORGENTITLEMENTTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
