-- created by Oraschemadoc Fri Mar  2 05:56:48 2012
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHNPACKAGEEVR" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"EPOCH" VARCHAR2(16), 
	"VERSION" VARCHAR2(512) NOT NULL ENABLE, 
	"RELEASE" VARCHAR2(512) NOT NULL ENABLE, 
	"EVR" "SPACEWALK"."EVR_T"  NOT NULL ENABLE, 
	 CONSTRAINT "RHN_PE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ENABLE ROW MOVEMENT 
 
/
