-- created by Oraschemadoc Fri Jan 22 13:39:23 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNPATHCHANNELMAP" 
   (	"PATH" VARCHAR2(128) NOT NULL ENABLE, 
	"CHANNEL_ID" NUMBER NOT NULL ENABLE, 
	"IS_SOURCE" VARCHAR2(1), 
	"CREATED" DATE DEFAULT (SYSDATE), 
	"MODIFIED" DATE DEFAULT (SYSDATE), 
	 CONSTRAINT "RHN_PATH_CHANNEL_MAP_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "MIM_H1"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
