-- created by Oraschemadoc Fri Mar  2 05:56:52 2012
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHNREGTOKENENTITLEMENT" 
   (	"REG_TOKEN_ID" NUMBER NOT NULL ENABLE, 
	"SERVER_GROUP_TYPE_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_REG_TOK_ENT_RTID_FK" FOREIGN KEY ("REG_TOKEN_ID")
	  REFERENCES "SPACEWALK"."RHNREGTOKEN" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_REG_TOK_ENT_SGTID_FK" FOREIGN KEY ("SERVER_GROUP_TYPE_ID")
	  REFERENCES "SPACEWALK"."RHNSERVERGROUPTYPE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ENABLE ROW MOVEMENT 
 
/
