-- created by Oraschemadoc Fri Jan 22 13:39:25 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNREGTOKEN" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ORG_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER, 
	"SERVER_ID" NUMBER, 
	"NOTE" VARCHAR2(2048) NOT NULL ENABLE, 
	"USAGE_LIMIT" NUMBER DEFAULT (0), 
	"DISABLED" NUMBER DEFAULT (0) NOT NULL ENABLE, 
	"DEPLOY_CONFIGS" CHAR(1) DEFAULT ('Y') NOT NULL ENABLE, 
	 CONSTRAINT "RHN_REG_TOKEN_DEPLOYCONFS_CK" CHECK (deploy_configs in ( 'Y' , 'N' )) ENABLE, 
	 CONSTRAINT "RHN_REG_TOKEN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_REG_TOKEN_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "MIM_H1"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_REG_TOKEN_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "MIM_H1"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_REG_TOKEN_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "MIM_H1"."RHNSERVER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
