-- created by Oraschemadoc Fri Mar  2 05:56:53 2012
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHNREGTOKENPACKAGES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TOKEN_ID" NUMBER NOT NULL ENABLE, 
	"NAME_ID" NUMBER NOT NULL ENABLE, 
	"ARCH_ID" NUMBER, 
	 CONSTRAINT "RHN_REG_TOK_PKG_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RHN_REG_TOK_PKG_ID_FK" FOREIGN KEY ("TOKEN_ID")
	  REFERENCES "SPACEWALK"."RHNREGTOKEN" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_REG_TOK_PKG_SGS_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "SPACEWALK"."RHNPACKAGENAME" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_REG_TOK_PKG_AID_FK" FOREIGN KEY ("ARCH_ID")
	  REFERENCES "SPACEWALK"."RHNPACKAGEARCH" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ENABLE ROW MOVEMENT 
 
/
