-- created by Oraschemadoc Fri Jan 22 13:39:35 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHNSSMOPERATIONSERVER"
   (	"OPERATION_ID" NUMBER, 
	"SERVER_ID" NUMBER, 
	 CONSTRAINT "RHN_SSMOPS_SSMOP_FK" FOREIGN KEY ("OPERATION_ID")
	  REFERENCES "SPACEWALK"."RHNSSMOPERATION" ("ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "RHN_SSMOPS_SER_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEWALK"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
