-- created by Oraschemadoc Fri Jan 22 13:39:32 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNSGTYPEVIRTSUBLEVEL" 
   (	"SERVER_GROUP_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"VIRT_SUB_LEVEL_ID" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SGTVSL_SGTID_FK" FOREIGN KEY ("SERVER_GROUP_TYPE_ID")
	  REFERENCES "MIM_H1"."RHNSERVERGROUPTYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SGTVSL_VSLID_FK" FOREIGN KEY ("VIRT_SUB_LEVEL_ID")
	  REFERENCES "MIM_H1"."RHNVIRTSUBLEVEL" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
