-- created by Oraschemadoc Fri Jan 22 13:39:30 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHNSERVERMESSAGE"
   (	"SERVER_ID" NUMBER NOT NULL ENABLE, 
	"MESSAGE_ID" NUMBER NOT NULL ENABLE, 
	"SERVER_EVENT" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SM_SERVER_ID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEWALK"."RHNSERVER" ("ID") ENABLE,
	 CONSTRAINT "RHN_SM_MESSAGE_ID_FK" FOREIGN KEY ("MESSAGE_ID")
	  REFERENCES "SPACEWALK"."RHNMESSAGE" ("ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "RHN_SM_SE_FK" FOREIGN KEY ("SERVER_EVENT")
	  REFERENCES "SPACEWALK"."RHNSERVEREVENT" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
