-- created by Oraschemadoc Fri Jan 22 13:39:32 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNSGTYPEBASEADDONCOMPAT" 
   (	"BASE_ID" NUMBER NOT NULL ENABLE, 
	"ADDON_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SGT_BAC_BID_FK" FOREIGN KEY ("BASE_ID")
	  REFERENCES "MIM_H1"."RHNSERVERGROUPTYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SGT_BAC_AID_FK" FOREIGN KEY ("ADDON_ID")
	  REFERENCES "MIM_H1"."RHNSERVERGROUPTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
