-- created by Oraschemadoc Fri Jan 22 13:39:36 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNTRANSACTIONELEMENT" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_PACKAGE_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_TRANSELEM_TID_FK" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "MIM_H1"."RHNTRANSACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_TRANSELEM_TPID_FK" FOREIGN KEY ("TRANSACTION_PACKAGE_ID")
	  REFERENCES "MIM_H1"."RHNTRANSACTIONPACKAGE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
