-- created by Oraschemadoc Fri Mar  2 05:57:02 2012
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHNTASKORUN" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TEMPLATE_ID" NUMBER NOT NULL ENABLE, 
	"SCHEDULE_ID" NUMBER NOT NULL ENABLE, 
	"ORG_ID" NUMBER, 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"STD_OUTPUT_PATH" VARCHAR2(100), 
	"STD_ERROR_PATH" VARCHAR2(100), 
	"STATUS" VARCHAR2(10), 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_TASKO_RUN_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RHN_TASKO_RUN_TEMPLATE_FK" FOREIGN KEY ("TEMPLATE_ID")
	  REFERENCES "SPACEWALK"."RHNTASKOTEMPLATE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_TASKO_RUN_SCHEDULE_FK" FOREIGN KEY ("SCHEDULE_ID")
	  REFERENCES "SPACEWALK"."RHNTASKOSCHEDULE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 
/
