-- created by Oraschemadoc Fri Jan 22 13:39:38 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM_H1"."RHNUSERMESSAGE" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"MESSAGE_ID" NUMBER NOT NULL ENABLE, 
	"STATUS" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_UM_USER_ID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "MIM_H1"."WEB_CONTACT" ("ID") ENABLE, 
	 CONSTRAINT "RHN_UM_MESSAGE_ID_FK" FOREIGN KEY ("MESSAGE_ID")
	  REFERENCES "MIM_H1"."RHNMESSAGE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_UM_STATUS_FK" FOREIGN KEY ("STATUS")
	  REFERENCES "MIM_H1"."RHNUSERMESSAGESTATUS" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
