-- created by Oraschemadoc Fri Mar  2 05:57:03 2012
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHNUSERDEFAULTSYSTEMGROUPS" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"SYSTEM_GROUP_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_UDSG_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SPACEWALK"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_UDSG_CIDFFK" FOREIGN KEY ("SYSTEM_GROUP_ID")
	  REFERENCES "SPACEWALK"."RHNSERVERGROUP" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ENABLE ROW MOVEMENT 
 
/
