-- created by Oraschemadoc Fri Mar  2 05:57:07 2012
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."RHNXCCDFRULERESULT" 
   (	"TESTRESULT_ID" NUMBER NOT NULL ENABLE, 
	"IDENT_ID" NUMBER NOT NULL ENABLE, 
	"RESULT_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_XCCDF_RRESULT_TRESULT_FK" FOREIGN KEY ("TESTRESULT_ID")
	  REFERENCES "SPACEWALK"."RHNXCCDFTESTRESULT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_XCCDF_RRESULT_IDENT_FK" FOREIGN KEY ("IDENT_ID")
	  REFERENCES "SPACEWALK"."RHNXCCDFIDENT" ("ID") ENABLE, 
	 CONSTRAINT "RHN_XCCDF_RRESULT_RESULT_FK" FOREIGN KEY ("RESULT_ID")
	  REFERENCES "SPACEWALK"."RHNXCCDFRULERESULTTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ENABLE ROW MOVEMENT 
 
/
