-- created by Oraschemadoc Fri Mar  2 05:57:16 2012
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."TIME_SERIES_DATA" 
   (	"ORG_ID" NUMBER NOT NULL ENABLE, 
	"PROBE_ID" NUMBER NOT NULL ENABLE, 
	"PROBE_DESC" VARCHAR2(64), 
	"ENTRY_TIME" NUMBER NOT NULL ENABLE, 
	"DATA" VARCHAR2(1024), 
	 CONSTRAINT "TIME_SERIES_DATA_PID_FK" FOREIGN KEY ("PROBE_ID")
	  REFERENCES "SPACEWALK"."TIME_SERIES_PURGE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ENABLE ROW MOVEMENT 
 
/
