-- created by Oraschemadoc Thu Jan 20 13:48:59 2011
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEWALK"."VALID_COUNTRIES_TL" 
   (	"LANG" CHAR(2) NOT NULL ENABLE, 
	"CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"SHORT_NAME_TL" VARCHAR2(80) NOT NULL ENABLE, 
	 CONSTRAINT "VALID_COUNTRIES_TL_UNQ" UNIQUE ("LANG", "CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "VALID_COUNTRIES_TL_CODE" FOREIGN KEY ("CODE")
	  REFERENCES "SPACEWALK"."VALID_COUNTRIES" ("CODE") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ENABLE ROW MOVEMENT 
 
/
