#!/bin/sh
#
# Copyright (c) 2008--2013 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public License,
# version 2 (GPLv2). There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
# along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
#
# Red Hat trademarks are not licensed under GPLv2. No permission is
# granted to use or replicate Red Hat trademarks that are incorporated
# in this software or its documentation.
#
#

# We do this, because Runtime.exec in the java code seems to only allocate a buffer so big for stdout
#   and since we are restarting ourself, we can not flush the buffer in order 
#   to keep the process running, so now we use this script to rid ourselves of output! :{
#

/usr/sbin/rhn-satellite restart &> /dev/null < /dev/null
