.\" Copyright 2006--2010 Red Hat, Inc.
.\"
.\" This man page is free documentation; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this man page; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH RHN-PROFILE-SYNC 8 "2010 July 8" "Linux" "Red Hat, Inc."
.SH NAME

rhn-profile-sync \- Update system information on Red Hat Network.

.SH SYNOPSIS

rhn-profile-sync [\fIoptions\fP]

.SH DESCRIPTION

.PP
\fBrhn-profile-sync\fP is a client program that connects to 
.B Red Hat Network
(or a Red Hat Network Satellite) and refreshes the data stored for this system.

.PP
\fBrhn-profile-sync\fP updates data about installed packages, machine hardware, and virtual guest instances (if virtualization is enabled).

.SH OPTIONS

.IP "\fB-v, --verbose\fP"
Increase the debugging output.
.br
.IP "\fB--proxy=PROXY\fP"
Specify an http proxy to use.
.br
.IP "\fB--proxyUser=PROXYUSER\fP"
Specify a username to use for an authenticated proxy. This option must be used
in conjunction with \fBproxyPassword\fP.
.br
.IP "\fB--proxyPassword=PROXYPASSWORD\fP"
Specify a password to use for an authenticated proxy. This option must be used
in conjunction with \fBproxyUser\fP.
.br
.IP "\fB--version\fP"
Show the program's version number and exit.
.br
.IP "\fB-h, --help\fP"
Show a help message and exit.

.SH FILES

.IP /etc/sysconfig/rhn/update
The common configuration file used by RHN client programs.

.SH "SEE ALSO"

.PP
\fBrhn_check\fP(8), \fBrhn_register\fP(8), \fBrhnreg_ks\fP(8), \fBrhnsd\fP(8), \fBup2date\fP(5).

.SH AUTHORS
.PP
See the AUTHORS file included with this software.
.PP
This manual page was written by James Bowes <jbowes@redhat.com>

.SH "BUGS"
.PP
Report bugs to <http://bugzilla.redhat.com>.

.SH COPYRIGHT

.PP
Copyright \(co 1999\-2010 Red Hat, Inc.

.PP
This is free software; see the source for copying conditions.  There is 
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
