# Makefile for installation of the logrotation configuration files
#
# $Id: Makefile,v 1.1 2002/08/20 20:59:43 misa Exp $

# what is the backend top dir
TOP	= ..

INSTALL_FILES	= $(wildcard rhn-*)
INSTALL_DEST	= /etc/logrotate.d

include $(TOP)/Makefile.defs
