#!/usr/bin/perl

# tst - simple template for using ReleaseDB with debug capability

use Data::Dumper;
use NOCpulse::ReleaseDB;
use Getopt::Long;
use NOCpulse::Log::LogManager;

my %args = ();
GetOptions(\%args, ('log=s%')) or die;

NOCpulse::Log::LogManager->instance->configure(%{$args{log}});


my $rdb = new NOCpulse::ReleaseDB();


# Do stuff here
print $rdb->ver2str('1.4a12-1'), "\n";
