# Makefile for the rhnSQL module
#
# $Id$

TOP     = ../..
SUBDIR	= server/rhnSQL

FILES	= __init__ sql_base sql_lib \
	  sql_row sql_sequence sql_table sql_types \
          dbi driver_cx_Oracle driver_postgresql

include $(TOP)/Makefile.defs
