#!/usr/bin/python
from sys import argv, exit
import os, stat

testclass="""#!/usr/bin/python
import unittest
from config import *

class %s (RhnTestCase):
    def setUp(self):
        RhnTestCase.setUp(self)
    def tearDown(self):
        RhnTestCase.tearDown(self)

if __name__ == "__main__":
    unittest.main()
"""

def main():
    file_name = argv[1].lower() + ".py"
    open(file_name,"w").write(testclass % argv[1])
    os.chmod(file_name, stat.S_IRWXU)

if __name__=="__main__":
    if len(argv) != 2:
        print "Usage: %s <TestClassName>" % argv[0]
        exit(0)
    main()
