# Makefile for installation of the httpd configuration files
#
# $Id$

# what is the backend top dir
TOP	= ..

INSTALL_FILES	= $(wildcard *.conf) $(wildcard rhn/*.conf)
INSTALL_DEST	= /etc/rhn/satellite-httpd/conf

EXTRA_DIRS	= $(INSTALL_DEST)/rhn

include $(TOP)/Makefile.defs
