This is a place-holder which indicates to Apache's src/Configure script that
it shouldn't provide the default targets when building the Makefile from
Makefile.tmpl in this directory.  Instead it'll just prepend all the important
variable definitions, and copy the Makefile.tmpl onto the end.
