#!/usr/bin/perl

use strict;
use Data::Dumper;
use SetID;

my %args = (
  ruid      => 0,
  euid      => 'bin',
  rgid      => 'daemon',
  egid      => 3,
  groups   => ['adm', 5, 'disk', 'lp'],
);

my $ids = &Sys::SetID::names2ids(\%args)
  or die "ERORR: $@\n";

print "BEFORE TRANSLATION:\n", &Dumper(\%args), "\n";
print "AFTER  TRANSLATION:\n", &Dumper($ids), "\n";
