#!/usr/bin/python
import sys, os

# make sure we have the path for RHN modules
if not "/var/www/rhns/" in sys.path:
    sys.path.append("/var/www/rhns/")
from server import rhnSQL

if len(sys.argv) != 2:
    print "usage: ./clean-tablespace login/password@database"
    sys.exit(-1)

rhnSQL.initDB(sys.argv[1])

h = rhnSQL.prepare("""\
    select  'drop type ' || object_name ||' force' drop_stmt
    from    user_objects
    where   object_type = 'TYPE'
    union
    select  'drop ' || object_type ||' '|| object_name drop_stmt
    from    user_objects
    where   object_type not in ('TABLE','INDEX','TRIGGER','TYPE','TYPE BODY')
    union
    select  'drop table ' || object_name ||' cascade constraints' drop_stmt
    from    user_objects
    where   object_type = 'TABLE'
""")
h.execute()
for row in h.fetchall():
    try:
	i = rhnSQL.prepare(row[0])
	i.execute()
    except:
	pass
