# Makefile for the apacheServer.py for Red Hat Proxy Server.
#
# $Id: Makefile,v 1.18 2004/04/07 18:43:34 taw Exp $

TOP	= ..
SUBDIR	= proxy/broker
FILES	= __init__ rhnRepository rhnBroker
include $(TOP)/Makefile.defs
