# Makefile for sql schema testing
#
# $Id$

TBS	= data_tbs
SQLOWNER = schema
SQLUSER	= $(SQLOWNER)/$(SQLOWNER)@$(SQLOWNER)
SQLUSER_SYNS = $(SQLOWNER)user/$(SQLOWNER)user@$(SQLOWNER)
SQLPLUS = sqlplus $(SQLUSER)
SYNONYMS = sqlplus $(SQLUSER_SYNS)
GENDROP	= $(TOP)/build/gendrop.sql

# default universe prints a nasty message
UNIVERSE ?= no-universe

LIST	= $(basename $(UNIVERSE)).lst
SYNLIST = $(basename $(UNIVERSE))-synonyms.lst

synonyms : $(UNIVERSE)-synonyms test-$(UNIVERSE)-synonyms $(SYNLIST)

all ::
	@echo $^

all :: $(UNIVERSE) test-$(UNIVERSE) $(LIST)
all :: $(if $(filter-out satellite, $(SCHEMA)), synonyms)

$(LIST) :
	@cat $(GENDROP) | $(SQLPLUS) | grep ^drop | $(SQLPLUS)
	@echo "@test-$(UNIVERSE)" | $(SQLPLUS) || exit -1 && \
	    (grep "^Errors for" $@ && echo "Please consult $(shell pwd)/$@" && exit -2 || exit 0)

$(SYNLIST) :
	@echo cat $(GENDROP) | $(SYNONYMS) | grep ^drop | $(SYNONYMS)
	@echo "@test-$(UNIVERSE)-synonyms" | $(SYNONYMS) || exit -1


define print-sql-file
{ \
	if [ "${SCHEMA}" = "production" ]; then \
	  sed -re 'sY^grant (.*) on (.*) to (.*);Ygrant \1 on \2 to rhn_dml_r;Yg' $(1) ; \
	else \
	  cat $(1) ; \
	fi \
}
endef

test-$(UNIVERSE) : $(UNIVERSE)
	@{ \
		echo "set serveroutput on" ; \
		echo "whenever sqlerror exit failure" ; \
		echo "spool $(LIST)" ; \
		$(call print-sql-file,$<) | sed -re 's/\[\[.*\]\]/$(TBS)/g' ; \
		echo "select 'Schema Load Test Complete' status_message from dual;" ; \
		echo "commit;" ; \
	} > $@

test-$(UNIVERSE)-synonyms : $(UNIVERSE)-synonyms
	@{ \
		echo "set serveroutput on" ; \
		echo "whenever sqlerror exit failure" ; \
		echo "spool $(SYNLIST)" ; \
		sed -e 's/\[\[.*\]\]/$(TBS)/g' $< | \
		sed -re "sY^create.*synonym (.*) for .*\.(.*);Ycreate or replace synonym \1 for $(SQLOWNER).\2;Yg" ; \
		echo "select 'Schema Load Test Complete' status_message from dual;" ; \
		echo "commit;" ; \
	} > $@

clean:
	@rm -fv *~
	@rm -fv test-$(UNIVERSE) $(LIST)
	@rm -fv test-$(UNIVERSE)-synonyms $(SYNLIST)

no-universe :
	@echo "Apparently you don't know what you're doing ($@)..."
	@exit -1

.PHONY: no-universe 
