#!/usr/bin/python

import sys
sys.path.append("/usr/share/rhn")

from common.rhnConfig import RHNOptions

do_list=0
if len(sys.argv) == 4 and sys.argv[1] == "get":
    comp = sys.argv[2]
    key = sys.argv[3]
elif len(sys.argv) == 3 and sys.argv[1] == "list":
    comp = sys.argv[2]
    do_list = 1
elif len(sys.argv) == 2:
    # assume we want key from root
    comp = ''
    key = sys.argv[1]
else:
    print "Usage: spacewalk-cfg-get [ { get | list } component [ key ]"
    print "       spacewalk-cfg-get key"
    sys.exit(1)

cfg = RHNOptions(comp)
cfg.parse()

if do_list:
    cfg.show()
else:
    val = cfg.get(key)
    if isinstance(val, list):
        for i in val:
            print i
    else:
        print val

