# Makefile for the apacheServer.py for RHN Proxy SSL Redirect Server.
#
# $Id: Makefile,v 1.12 2002/08/20 22:53:18 misa Exp $

TOP	= ..
SUBDIR	= proxy/redirect
FILES	= __init__ rhnRedirect
include $(TOP)/Makefile.defs

