#!/usr/bin/perl
use strict;
use lib '/etc/rc.d/np.d';
use NOCpulse::NOCpulseini;
use PhysCluster;
use Data::Dumper;
use Getopt::Long;

#set the defaults
my $all = 0;
my @groups = ();
my $raw = 0;
my @macros = ();
my $set_macro = '';
my $set_param = '';
my $new_value = '';
my $save = 0;

GetOptions("all" => \$all,
        "group:s@" => \@groups,
        "raw" => \$raw,
        "macro:s@" => \@macros,
        "set-macro:s" => \$set_macro,
        "set-param:s" => \$set_param,
        "new-value:s" => \$new_value,
        );

my $cluster = PhysCluster->newInitialized('/etc/rhn/cluster.ini');
my $localConfig = $cluster->get_LocalConfig;
my $ini = NOCpulse::NOCpulseini->new;

if (%$localConfig) {
        my $config = (values(%$localConfig))[0];
        my $dbd = $config->get_dbd;
        my $dbname = $config->get_dbname;
        my $username = $config->get_username;
        my $password = $config->get_password;
        $ini->connect($dbd, $dbname, $username, $password);
        $ini->raw($raw);
        $ini->fetch_nocpulseini('INTERNAL');
} else {
        print "Error: This script can be run only on monitoring backend.\n";
        exit 1;
}

if ($all) {
        print $ini->dump;
} elsif (@groups and !$set_param) {
        foreach my $group (@groups) {
                print $ini->dump_group($group), "\n\n";
        }
}
if (@macros) {
        my $list = $ini->fetch_macros;
        my %DESCRIPTION;
        foreach my $macro (@$list) {
                $DESCRIPTION{$macro->{'NAME'}} = $macro->{'DESCRIPTION'};
        }
        foreach my $macro (@macros) {
                if ($ini->macrodb->{$macro}) {
                        print "Macro $macro - $DESCRIPTION{$macro}\nexpands to: ", $ini->macrodb->{$macro}, "\n";
                } else {
                        print "Macro $macro is not defined.\n";
                }
        }
}
if ($set_macro) {
        my $sql = qq|
                UPDATE rhn_config_macro
                SET definition=?
                WHERE (environment, name) = ( SELECT macro.environment, macro.name
                                FROM db_environment dbenv, config_macro macro
                                WHERE UPPER(sys_context('userenv', 'db_name')) = UPPER(dbenv.db_name)
                                AND  DECODE(macro.environment, 'ALL', dbenv.environment,
                                        macro.environment) = dbenv.environment
                                AND macro.name = ?
                        )
                |;
        my $sth = $ini->dbh->prepare($sql);
        $sth->execute($new_value, $set_macro);
        print $sth->rows, " record updated.\n";
        $save = 1;
} elsif ($set_param) {
        if (!@groups or scalar(@groups) != 1) {
                print "Error: You have to specify exactly one group, to which parameter belongs.\n";
                exit 2;
        }
        my $sql = qq|
                UPDATE config_parameter
                SET value = ?
                WHERE group_name = ?
                        AND name = ?
                |;
        my $sth = $ini->dbh->prepare($sql);
        $sth->execute($new_value, $groups[0], $set_param);
        print $sth->rows, " record updated.\n";
        $save = 1;
}

if ($save) {
        $ini->fetch_nocpulseini('INTERNAL');
        $ini->save;
}

