#!/usr/bin/perl
use NOCpulse::Config;

my $config = NOCpulse::Config->new('/etc/rc.d/np.d/SysV.ini');

my ($stepName,$whoBy) = @ARGV;
$stepName =~ s/(.*)\.pm/$1/g;
my $regdir = $config->val('SysVStep','registry');
my $filename = $regdir.'/'.$stepName;
if ( ! -f $filename ) {
	open(FILE,">$filename");
} else {
	open(FILE,">>$filename");
}
print FILE $whoBy."\n";
close(FILE);
