#!/usr/bin/perl
use NOCpulse::Object;
use lib qw(/etc/rc.d/np.d);
use NOCpulse::Config;
use PhysCluster;
$NOCpulse::Object::config = NOCpulse::Config->new('/etc/rc.d/np.d/SysV.ini');
NOCpulse::Object->defaultDebugObject->addstream(LEVEL=>1);
NOCpulse::Object->dprint(0,"Parsing configuration file...\n\n");
my $config = PhysCluster->newInitialized;
NOCpulse::Object->dprint(0,"\nVerifying validity of system configuration...\n\n");
if ( $config->isValid() ) {
	NOCpulse::Object->dprint(0,"\nConfiguration is valid\n\n");
} else {
	NOCpulse::Object->dprint(0,"\nConfiguration is INVALID\n\n");
}
