=head1 NAME

spacewalk-service - Script to control Spacewalk server.

=head2 SYNOPSIS

B<spacewalk-service> {B<start>|B<stop>|B<status>|B<reload>|B<restart>|B<enable>|B<disable>|B<list>}

=head2 DESCRIPTION

Spacewalk server consist from several services. While each of such service has its own init.d script
and you can start/stop each service separately, you usually want to control all services together.
This script does exactly this.

=head1 OPTIONS

=over 5

=item B<start>|B<stop>|B<status>|B<reload>|B<restart>

Behave exactly as B<service> for every Spacewalk service.

=item B<list>

List all Spacewalk services and if it is enabled or disabled.

=item B<--no-wait-for-tomcat>

By default, spacewalk-service wait until tomcat is able to answer requests.
If you specify this option, spacewalk-service will continue immediately when
tomcat service will start.

=item B<--exclude> SERVICE

It will not start/stop SERVICE.

=item B<--level> LEVEL

Pass LEVEL to chkconfig when you specify option B<enable>.

=head1 SEE ALSO

B<rhn-schema-version>(8), B<rmchannel>(8), B<satellite-debug>(8), B<send-satellite-debug>(8), B<rhnpush>(8), B<satellite-sync>(8), B<db-control>(1) (embedded satellite only),
B<rhn-ssl-tool>(1), B<rhn-charsets>(8), B<rhn-satellite-activate>(8),
B<service>(8)
