=head1 NAME

validate-sat-cert - utility that checks XML parse sanity and GPG validates an
RHN Satellite certificate.

=head2 SYNOPSIS

B<validate-sat-cert> [B<--keyring /path/to/keyring.gpg>] [B<--quiet>]
[B<--nosig>] [B<--required-version VERSION> CERTFILE]

=head1 OPTIONS

=over 5

=item B<--keyring>

Specify the keyring to use for GPG signature validation.

=item B<--quiet>

Suppress some messages; meant for scripted operation.

=item B<--nosig>

GPG signature not checked.

=item B<--required-version>

VERSION will enforce that the RHN certificate's version matches.

=item B<--help>

Display reference to this man page. :)

=back

=head1 SEE ALSO

B<rhn-schema-version>(8), B<rmchannel>(8), B<satellite-debug>(8), B<send-satellite-debug>(8), B<rhnpush>(8), B<satellite-sync>(8), B<db-control>(1) (embedded satellite only),
B<rhn-ssl-tool>(1), B<rhn-charsets>(8), B<rhn-satellite-activate>(8)
