--
-- Copyright (c) 2008 Red Hat, Inc.
--
-- This software is licensed to you under the GNU General Public License,
-- version 2 (GPLv2). There is NO WARRANTY for this software, express or
-- implied, including the implied warranties of MERCHANTABILITY or FITNESS
-- FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
-- along with this software; if not, see
-- http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
-- 
-- Red Hat trademarks are not licensed under GPLv2. No permission is
-- granted to use or replicate Red Hat trademarks that are incorporated
-- in this software or its documentation. 
--
--
-- $Id$
--
-- EXCLUDE: all
-- EXCLUDE: all
--
-- synonym fro web_customer in production

create synonym web_customer for web.web_customer;

-- $Log$
-- Revision 1.2  2003/11/05 16:43:20  pjones
-- bugzilla: 106071 -- these synonyms aren't useful any more.  For now, just
-- exclude them, but probably kill them later.
--
-- Revision 1.1  2002/05/10 15:36:46  pjones
-- synonyms are now handles like everything else.
--
