# Makefile for the sat module
#
# $Id: Makefile 108736 2007-01-09 21:02:46Z jbowes $

TOP	= ../../..
SUBDIR	= server/handlers/sat

FILES	= __init__ auth cert get_handler kickstart packages rhnPackage

include $(TOP)/Makefile.defs
