# Makefile for installation of the httpd configuration files
#
# $Id: Makefile,v 1.1 2002/08/20 20:58:17 misa Exp $

TOP	= ..

INSTALL_FILES	= $(wildcard *.conf)
INSTALL_DEST	= /etc/httpd/conf.d

EXTRA_DIRS  =

include $(TOP)/Makefile.defs
