# Makefile for installation of the RHN Package Manager configuration files
#

# what is the backend top dir
TOP	= ../..

INSTALL_FILES	= $(wildcard *.conf)
INSTALL_DEST	= /usr/share/rhn/config-defaults

include $(TOP)/Makefile.defs

install :: $(PREFIX)$(INSTALL_DEST)
