# Makefile for installation of the RHN server configuration files

# what is the backend top dir
TOP	= ..

INSTALL_FILES	= sqlnet.ora
INSTALL_LINKS	= tnsnames.ora
INSTALL_DEST	= /etc/rhn/tns_admin/osa-dispatcher

include $(TOP)/Makefile.defs
