
LABELS  = \
            rhel-i386-3 \
            rhel-ia64-3 \
            rhel-i386-2.1AS \
            rhel-i386-2.1-ES-WS \
            rhel-ia64-2.1 \
#            redhat-linux-i386-9 \
#            redhat-linux-i386-6.2 \
#            redhat-linux-i386-7.1 \
#            redhat-linux-i386-7.2 \
#            redhat-linux-i386-7.3 \
#            redhat-linux-i386-8.0 

APP_SERVER  = http://scripts1.back-rdu.redhat.com/SAT-DUMP-INTERNAL

all_labels  = $(shell bash get-channels.sh)
channels_for_label = $(shell bash get-channels.sh $1)
label_for_channel = $(shell bash get-channels.sh --label $1)
all_channels = $(shell bash get-channels.sh $1)

CHANNELS    = $(call all_channels,$(LABELS))

##
## Direcories
##
# Special-case TOPDIR for rsync
TOPDIR	    = /root/satellite-data
REP_DIR	    = $(TOPDIR)/satellite-dump-repository
ISO_DIR	    = $(TOPDIR)/satellite-isos
DUMP_DIR    = $(TOPDIR)/satellite-temp

PYTHONPATH  = PYTHONPATH=..
EXPORTER_DIR    = exporter
EXPORTER    = $(PYTHONPATH) python $(EXPORTER_DIR)/exporter.py -m $(REP_DIR) \
    --server $(APP_SERVER) $(EXPORTER_FLAGS)

INSTALL_DIR = install -d -m 755 --verbose

GENISO      = $(PYTHONPATH) python geniso.py  
GENTREE	    = $(PYTHONPATH) python gentree.py -m $(REP_DIR)

# All the channels, separated with plus signs (+)
ALL_LABELS = $(shell echo $(strip $(LABELS)) | sed 's/ /+/g')

dump:
	@echo Please read HOWTO.dumps

export:
	$(EXPORTER) $(addprefix -c ,$(CHANNELS)) --force --channels
	$(EXPORTER) $(addprefix -c ,$(CHANNELS))

geniso-all: $(ISO_DIR)/isos-$(ALL_LABELS) gentree-all
	@rm -fv $</*
	$(GENISO) -m $(DUMP_DIR)/dump-$(ALL_LABELS) -o $<

geniso:	$(addprefix geniso_,$(LABELS))

geniso_%: $(ISO_DIR)/isos-% gentree_% verify_%
	@echo rm -fv $</*
	$(GENISO) -m $(DUMP_DIR)/dump-$* -o $< --file-prefix $*
	@(cd $<; md5sum *.iso > MD5SUM)

export-channel-families-%:
	$(EXPORTER) $(addprefix -c ,$(call channels_for_label,$*)) --channelfamilies --force

gentree: $(addprefix gentree_,$(LABELS))

gentree_%: $(DUMP_DIR)/dump-% export-channel-families-%
	$(GENTREE) -o $(DUMP_DIR)/dump-$* $(addprefix -c ,$(call channels_for_label,$*))

verify_%: $(DUMP_DIR)/dump-%
	@echo "Verifying $</packages_short"
	@find $</packages_short -type f -exec xmllint {} > /dev/null \;
	@echo "Verifying $</packages"
	@find $</packages -type f -exec xmllint {} > /dev/null \;
	@echo "Verifying $</rpms"
	@find $</rpms -type f -exec rpm -qp {} > /dev/null \;
	
# Target to create directories
$(REP_DIR) $(ISO_DIR) $(DUMP_DIR):
	$(INSTALL_DIR) $@

$(ISO_DIR)/% $(DUMP_DIR)/% $(REP_DIR)/%:
	$(INSTALL_DIR) $@

export-all: export	
	$(EXPORTER) $(addprefix -c ,$(CHANNELS)) --force --channelfamilies
	
gentree-all: export-all
	$(GENTREE) $(addprefix -c ,$(CHANNELS)) -o $(DUMP_DIR)/dump-$(ALL_LABELS)

test-lookup:
	@echo $(all_labels)
	@echo $(call channels_for_label,rhel-i386-3)
	@echo $(call label_for_channel,rhel-i386-as-3)

test-all-channels:
	@echo $(CHANNELS)

# To prevent the removal of intermediate targets
.PRECIOUS: $(ISO_DIR)/% $(DUMP_DIR)/%

.PHONY: geniso geniso_% gentree gentree_%
