--
-- Copyright (c) 2008 Red Hat, Inc.
--
-- This software is licensed to you under the GNU General Public License,
-- version 2 (GPLv2). There is NO WARRANTY for this software, express or
-- implied, including the implied warranties of MERCHANTABILITY or FITNESS
-- FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
-- along with this software; if not, see
-- http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
-- 
-- Red Hat trademarks are not licensed under GPLv2. No permission is
-- granted to use or replicate Red Hat trademarks that are incorporated
-- in this software or its documentation. 
--
--
-- $Id$
-- EXCLUDE: all
--
-- table to stor tomcat sessions in db.
-- the code which uses this can be found at: http://cvs.apache.org/viewcvs.cgi/jakarta-tomcat-catalina/catalina/src/share/org/apache/catalina/session/JDBCStore.java?annotate=1.10

-- XXX This schema has some problems:
-- 1) id is a 100 character string, generated by the tomcat code.
--    It should be number from a sequence in the db.
-- 2) valid should be constrained to ('Y','N') rather than 0/1.
-- 3) max_inactive needs a noun in the name, so we can tell what it does by
--    looking at it.
-- 4) last_access should be a date column
-- 5) app_name is completely useless to us, so we're not indexing it as the
--    original code has.  This is even more broken -- really, the code uses
--    id + app_name as the unique data for this table (although id itself is
--    also unique).  The lookup code selects on id first, though, so our pk 
--    index should be sufficient.
-- 6) data should be in a tablespace designed for this.

create table
tomcat_session
(
	id		varchar(100)
			constraint tomcat_session_id_nn not null,
	valid		char(1)
			constraint tomcat_session_valid_nn not null
			constraint tomcat_session_valid_ck
				check (valid in ('0','1')),
	max_inactive	number
			constraint tomcat_session_mi_nn not null,
	last_access	number
			constraint tomcat_session_la_nn not null,
	app_name	varchar2(255),
	data		blob
)
	storage ( freelists 16 )
	initrans 32;

create index tomcat_session_id_idx
	on tomcat_session( id )
	tablespace [[8m_tbs]]
	storage ( freelists 16 )
	initrans 32;
alter table tomcat_session add constraint tomcat_session_id_pk
	primary key ( id );

-- $Log$
-- Revision 1.5  2004/09/21 19:39:47  pjones
-- bugzilla: 132982 -- rename everything that's configurable and I don't like ;)
--
-- Revision 1.4  2004/09/21 19:10:50  pjones
-- bugzilla: 132982 -- added long gripe about quality of this schema.
--
-- Revision 1.3  2004/09/21 18:40:53  pjones
-- bugzilla: 132982 -- add grants and synonyms, fix a typo.
--
-- Revision 1.2  2004/09/21 18:32:31  pjones
-- bugzilla: 132982 -- add tablespace information, as well as constraint and
-- index names
--
-- Revision 1.1  2004/09/21 14:53:45  rbb
-- Add table for tomcat sessions.
--
