# Makefile for spacewalk backend
#

# what is the backend top dir
TOP     = ..

# Specific stuff
SUBDIR		= osad
FILES           = __init__ dispatcher_client jabber_lib osa_dispatcher \
                  osad_client osad osad_config rhn_log

include $(TOP)/Makefile.defs
