-- created by Oraschemadoc Mon Aug 31 10:53:53 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHN_SCHEDULE_WEEKS" 
   (	"RECID" NUMBER(12,0) NOT NULL ENABLE, 
	"SCHEDULE_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"COMPONENT_SCHEDULE_ID" NUMBER(12,0), 
	"ORD" NUMBER(3,0), 
	"LAST_UPDATE_USER" VARCHAR2(40), 
	"LAST_UPDATE_DATE" DATE, 
	 CONSTRAINT "RHN_SCHWK_RECID_CK" CHECK (recid > 0) ENABLE, 
	 CONSTRAINT "RHN_SCHWK_RECID_PK" PRIMARY KEY ("RECID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SCHWK_SCHED_COMP_SCHED_FK" FOREIGN KEY ("COMPONENT_SCHEDULE_ID")
	  REFERENCES "MIM1"."RHN_SCHEDULES" ("RECID") ENABLE, 
	 CONSTRAINT "RHN_SCHWK_SCHED_SCHED_ID_FK" FOREIGN KEY ("SCHEDULE_ID")
	  REFERENCES "MIM1"."RHN_SCHEDULES" ("RECID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
