-- created by Oraschemadoc Mon Aug 31 10:53:49 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHN_DB_ENVIRONMENT" 
   (	"DB_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"ENVIRONMENT" VARCHAR2(255), 
	 CONSTRAINT "RHN_DBENV_DB_NAME_PK" PRIMARY KEY ("DB_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_DBENV_ENVIR_ENVIRONMENT_FK" FOREIGN KEY ("ENVIRONMENT")
	  REFERENCES "MIM1"."RHN_ENVIRONMENT" ("NAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
