-- created by Oraschemadoc Mon Aug 31 10:53:50 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHN_INTERFACE_MONITORING" 
   (	"SERVER_ID" NUMBER NOT NULL ENABLE, 
	"SERVER_NAME" VARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_MONIF_SERVER_PK" PRIMARY KEY ("SERVER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_MONIF_SERVER_NAME_FK" FOREIGN KEY ("SERVER_ID", "SERVER_NAME")
	  REFERENCES "MIM1"."RHNSERVERNETINTERFACE" ("SERVER_ID", "NAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
