-- created by Oraschemadoc Mon Aug 31 10:53:50 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHN_METRICS" 
   (	"METRIC_ID" VARCHAR2(40) NOT NULL ENABLE, 
	"STORAGE_UNIT_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200), 
	"LAST_UPDATE_USER" VARCHAR2(40), 
	"LAST_UPDATE_DATE" DATE, 
	"LABEL" VARCHAR2(40), 
	"COMMAND_CLASS" VARCHAR2(255) DEFAULT ('nothing') NOT NULL ENABLE, 
	 CONSTRAINT "RHN_METRC_CMD_CL_METRIC_ID_PK" PRIMARY KEY ("COMMAND_CLASS", "METRIC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_METRC_COMCL_CMD_CLASS_FK" FOREIGN KEY ("COMMAND_CLASS")
	  REFERENCES "MIM1"."RHN_COMMAND_CLASS" ("CLASS_NAME") ENABLE, 
	 CONSTRAINT "RHN_METRC_UTS_STOR_UT_ID_FK" FOREIGN KEY ("STORAGE_UNIT_ID")
	  REFERENCES "MIM1"."RHN_UNITS" ("UNIT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
