-- created by Oraschemadoc Mon Aug 31 10:53:48 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHN_COMMAND_QUEUE_EXECS_BK" 
   (	"INSTANCE_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"NETSAINT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"DATE_ACCEPTED" DATE, 
	"DATE_EXECUTED" DATE, 
	"EXIT_STATUS" NUMBER(5,0), 
	"EXECUTION_TIME" NUMBER(10,0), 
	"STDOUT" VARCHAR2(4000), 
	"STDERR" VARCHAR2(4000), 
	"LAST_UPDATE_DATE" DATE, 
	"TARGET_TYPE" VARCHAR2(10) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
