-- created by Oraschemadoc Mon Aug 31 10:53:17 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHNACTIONTRANSACTIONS" 
   (	"ACTION_ID" NUMBER NOT NULL ENABLE, 
	"FROM_TRANS_ID" NUMBER NOT NULL ENABLE, 
	"TO_TRANS_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_AT_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "MIM1"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_AT_FTID_FK" FOREIGN KEY ("FROM_TRANS_ID")
	  REFERENCES "MIM1"."RHNTRANSACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_AT_TTID_FK" FOREIGN KEY ("TO_TRANS_ID")
	  REFERENCES "MIM1"."RHNTRANSACTION" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
