-- created by Oraschemadoc Mon Aug 31 10:53:22 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHNCONFIGFILE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CONFIG_CHANNEL_ID" NUMBER NOT NULL ENABLE, 
	"CONFIG_FILE_NAME_ID" NUMBER NOT NULL ENABLE, 
	"LATEST_CONFIG_REVISION_ID" NUMBER, 
	"STATE_ID" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CONFFILE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CONFFILE_CCID_CFNID_UQ" UNIQUE ("CONFIG_CHANNEL_ID", "CONFIG_FILE_NAME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CONFFILE_CCID_FK" FOREIGN KEY ("CONFIG_CHANNEL_ID")
	  REFERENCES "MIM1"."RHNCONFIGCHANNEL" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CONFFILE_CFNID_FK" FOREIGN KEY ("CONFIG_FILE_NAME_ID")
	  REFERENCES "MIM1"."RHNCONFIGFILENAME" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CONFFILE_SID_FK" FOREIGN KEY ("STATE_ID")
	  REFERENCES "MIM1"."RHNCONFIGFILESTATE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CONFFILE_LCRID_FK" FOREIGN KEY ("LATEST_CONFIG_REVISION_ID")
	  REFERENCES "MIM1"."RHNCONFIGREVISION" ("ID") ON DELETE SET NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
