-- created by Oraschemadoc Mon Aug 31 10:53:21 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHNCHANNELNEWESTPACKAGE" 
   (	"CHANNEL_ID" NUMBER NOT NULL ENABLE, 
	"NAME_ID" NUMBER NOT NULL ENABLE, 
	"EVR_ID" NUMBER NOT NULL ENABLE, 
	"PACKAGE_ARCH_ID" NUMBER NOT NULL ENABLE, 
	"PACKAGE_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CNP_CID_NID_UQ" UNIQUE ("CHANNEL_ID", "NAME_ID", "PACKAGE_ARCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CNP_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "MIM1"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_CNP_NID_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "MIM1"."RHNPACKAGENAME" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CNP_EID_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "MIM1"."RHNPACKAGEEVR" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CNP_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "MIM1"."RHNPACKAGEARCH" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CNP_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "MIM1"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
