-- created by Oraschemadoc Mon Aug 31 10:53:24 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHNDOWNLOADS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CHANNEL_FAMILY_ID" NUMBER NOT NULL ENABLE, 
	"FILE_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(128) NOT NULL ENABLE, 
	"ORDERING" NUMBER NOT NULL ENABLE, 
	"DOWNLOAD_TYPE" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"RELEASE_NOTES_URL" VARCHAR2(512), 
	 CONSTRAINT "RHN_DL_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_DL_CFID_FK" FOREIGN KEY ("CHANNEL_FAMILY_ID")
	  REFERENCES "MIM1"."RHNCHANNELFAMILY" ("ID") ENABLE, 
	 CONSTRAINT "RHN_DL_FID_FK" FOREIGN KEY ("FILE_ID")
	  REFERENCES "MIM1"."RHNFILE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_DL_DLTYPE_FK" FOREIGN KEY ("DOWNLOAD_TYPE")
	  REFERENCES "MIM1"."RHNDOWNLOADTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
