-- created by Oraschemadoc Mon Aug 31 10:53:32 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHNPACKAGEFILE" 
   (	"PACKAGE_ID" NUMBER NOT NULL ENABLE, 
	"CAPABILITY_ID" NUMBER NOT NULL ENABLE, 
	"DEVICE" NUMBER NOT NULL ENABLE, 
	"INODE" NUMBER NOT NULL ENABLE, 
	"FILE_MODE" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(32) NOT NULL ENABLE, 
	"GROUPNAME" VARCHAR2(32) NOT NULL ENABLE, 
	"RDEV" NUMBER NOT NULL ENABLE, 
	"FILE_SIZE" NUMBER NOT NULL ENABLE, 
	"MTIME" DATE NOT NULL ENABLE, 
	"MD5" VARCHAR2(32), 
	"LINKTO" VARCHAR2(256), 
	"FLAGS" NUMBER NOT NULL ENABLE, 
	"VERIFYFLAGS" NUMBER NOT NULL ENABLE, 
	"LANG" VARCHAR2(32), 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_PACKAGE_FILE_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "MIM1"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_PACKAGE_FILE_CID_FK" FOREIGN KEY ("CAPABILITY_ID")
	  REFERENCES "MIM1"."RHNPACKAGECAPABILITY" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
