-- created by Oraschemadoc Mon Aug 31 10:53:36 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHNREGTOKENORGDEFAULT" 
   (	"ORG_ID" NUMBER NOT NULL ENABLE, 
	"REG_TOKEN_ID" NUMBER, 
	 CONSTRAINT "RHN_REG_TOKEN_DEF_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "MIM1"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_REG_TOKEN_DEF_TOKID_FK" FOREIGN KEY ("REG_TOKEN_ID")
	  REFERENCES "MIM1"."RHNREGTOKEN" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
