-- created by Oraschemadoc Mon Aug 31 10:53:37 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHNSAVEDSEARCH" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"WEB_CONTACT_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(16) NOT NULL ENABLE, 
	"TYPE" NUMBER NOT NULL ENABLE, 
	"SEARCH_STRING" VARCHAR2(4000) NOT NULL ENABLE, 
	"SEARCH_SET" VARCHAR2(16) NOT NULL ENABLE, 
	"SEARCH_FIELD" VARCHAR2(128) NOT NULL ENABLE, 
	"INVERT" CHAR(1) DEFAULT ('N') NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SAVEDSEARCH_SSET_CK" CHECK (search_set in ( 'all' , 'system_list' )) ENABLE, 
	 CONSTRAINT "RHN_SAVEDSEARCH_INVERT_CK" CHECK (invert in ( 'Y' , 'N' )) ENABLE, 
	 CONSTRAINT "RHN_SAVEDSEARCH_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SAVEDSEARCH_NAME_WCID_UQ" UNIQUE ("NAME", "WEB_CONTACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SAVEDSEARCH_WCID_FK" FOREIGN KEY ("WEB_CONTACT_ID")
	  REFERENCES "MIM1"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SAVEDSEARCH_TYPE_FK" FOREIGN KEY ("TYPE")
	  REFERENCES "MIM1"."RHNSAVEDSEARCHTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
