-- created by Oraschemadoc Mon Aug 31 10:53:41 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHNSNAPSHOTCONFIGREVISION" 
   (	"SNAPSHOT_ID" NUMBER NOT NULL ENABLE, 
	"CONFIG_REVISION_ID" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SNAPSHOTCR_SID_FK" FOREIGN KEY ("SNAPSHOT_ID")
	  REFERENCES "MIM1"."RHNSNAPSHOT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SNAPSHOTCR_CRID_FK" FOREIGN KEY ("CONFIG_REVISION_ID")
	  REFERENCES "MIM1"."RHNCONFIGREVISION" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
