-- created by Oraschemadoc Mon Aug 31 10:53:42 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHNSOLARISPATCHEDPACKAGE" 
   (	"SERVER_ID" NUMBER NOT NULL ENABLE, 
	"PATCH_ID" NUMBER NOT NULL ENABLE, 
	"PACKAGE_NEVRA_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SOLARIS_PATCHEDP_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "MIM1"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SOLARIS_PATCHEDP_PID_FK" FOREIGN KEY ("PATCH_ID")
	  REFERENCES "MIM1"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SOLARIS_PATCHEDP_PNID_FK" FOREIGN KEY ("PACKAGE_NEVRA_ID")
	  REFERENCES "MIM1"."RHNPACKAGENEVRA" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
