-- created by Oraschemadoc Mon Aug 31 10:53:42 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHNSOLARISPATCHPACKAGES" 
   (	"PATCH_ID" NUMBER NOT NULL ENABLE, 
	"PACKAGE_NEVRA_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SOLARIS_PP_FK" FOREIGN KEY ("PATCH_ID")
	  REFERENCES "MIM1"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SOLARIS_PNID_FK" FOREIGN KEY ("PACKAGE_NEVRA_ID")
	  REFERENCES "MIM1"."RHNPACKAGENEVRA" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
