-- created by Oraschemadoc Mon Aug 31 10:53:43 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHNTASKQUEUE" 
   (	"ORG_ID" NUMBER NOT NULL ENABLE, 
	"TASK_NAME" VARCHAR2(64) NOT NULL ENABLE, 
	"TASK_DATA" NUMBER, 
	"PRIORITY" NUMBER DEFAULT (0), 
	"EARLIEST" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_TASK_QUEUE_ORG_ID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "MIM1"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
