-- created by Oraschemadoc Mon Aug 31 10:53:45 2009
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "MIM1"."RHNUSERINFO" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"NO_CLEAR_SETS" NUMBER DEFAULT (0) NOT NULL ENABLE, 
	"PAGE_SIZE" NUMBER DEFAULT (20) NOT NULL ENABLE, 
	"EMAIL_NOTIFY" NUMBER DEFAULT (1) NOT NULL ENABLE, 
	"BAD_EMAIL" NUMBER DEFAULT (0) NOT NULL ENABLE, 
	"TZ_OFFSET" NUMBER DEFAULT (-5) NOT NULL ENABLE, 
	"TIMEZONE_ID" NUMBER, 
	"SHOW_APPLIED_ERRATA" CHAR(1) DEFAULT ('N') NOT NULL ENABLE, 
	"SHOW_SYSTEM_GROUP_LIST" CHAR(1) DEFAULT ('N') NOT NULL ENABLE, 
	"AGREED_TO_TERMS" CHAR(1) DEFAULT ('N') NOT NULL ENABLE, 
	"USE_PAM_AUTHENTICATION" CHAR(1) DEFAULT ('N') NOT NULL ENABLE, 
	"LAST_LOGGED_IN" DATE, 
	"AGREED_TO_WS_TERMS" CHAR(1), 
	"AGREED_TO_ES_TERMS" CHAR(1), 
	"CREATED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"PREFERRED_LOCALE" VARCHAR2(8), 
	 CONSTRAINT "RHN_USER_INFO_TZOFFSET_CK" CHECK (tz_offset >= -11 and tz_offset <= 13) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_SEA_CK" CHECK (show_applied_errata in ( 'Y' , 'N' )) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_SSGL_CK" CHECK (show_system_group_list in ( 'Y' , 'N' )) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_AGREED_CK" CHECK (agreed_to_terms in ( 'Y' , 'N' )) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_PAM_CK" CHECK (use_pam_authentication in ( 'Y' , 'N' )) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_WS_CK" CHECK (agreed_to_ws_terms is null or agreed_to_ws_terms in ( 'Y' , 'N' )) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_ES_CK" CHECK (agreed_to_es_terms is null or agreed_to_es_terms in ( 'Y' , 'N' )) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_UID_UQ" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "MIM1"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_TZID_FK" FOREIGN KEY ("TIMEZONE_ID")
	  REFERENCES "MIM1"."RHNTIMEZONE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE ROW MOVEMENT 
 
/
