# Makefile for building rhn proxy snapshots
#
# $Id: Makefile,v 1.145 2002/10/16 23:14:18 misa Exp $

all: version MANIFEST
	@echo "Hi there!"
	@echo "It would be nice if you read some documentation first."

# Documentation directory
DOCS_DIR        = proxy/docs
# product installer..
include ../Makefile.installer
