# Makefile for installation of the httpd configuration files
#
# $Id$

# what is the backend top dir
TOP	= ..

INSTALL_FILES	= $(wildcard *.conf)
INSTALL_DEST	= /etc/httpd/conf.d

include $(TOP)/Makefile.defs
