#!/usr/bin/perl

# Test using Gritch with a Debug object

use NOCpulse::Gritch;
my $SLEEP = 2;

# Set up the Debug object
my $debug = new NOCpulse::Debug;
my $out   = $debug->addstream(LEVEL => 1);      # uses STDOUT

# Set up the Gritch object
my $gritchdb  = "gripes.db";
my $soapbox = new NOCpulse::Gritch($gritchdb);
$soapbox->setDebug(9);

# set some testing parameters
$soapbox->recipient($out);
$soapbox->timeinterval(60);
$soapbox->countinterval(5);

while (1) {
  $out->dprint(1, "+++ Gritching ...\n");
  $soapbox->gritch('***GRITCH SUBJECT***',
                     '*** GRITCH BODY  ***  at ' .
                     scalar(localtime(time)), "\n");

  $out->dprint(1, "(sleeping $SLEEP seconds)\n");
  sleep $SLEEP;
  $out->dprint(1, "\n");
}

