#!/usr/bin/perl

# Mail test script for Gritch.pm

use NOCpulse::Gritch;
my $SLEEP = 2;

my $gritchdb  = "gripes.db";
my $soapbox = new NOCpulse::Gritch($gritchdb);
$soapbox->setDebug(9);

# set some testing parameters
$soapbox->recipient('nobody@nocpulse.com');
$soapbox->timeinterval(60);
$soapbox->countinterval(5);

while (1) {
  $soapbox->gritch('***GRITCH SUBJECT***',
                     '*** GRITCH BODY  ***  at ' .
                     scalar(localtime(time)), "\n");

  $soapbox->dprint(1, "(sleeping $SLEEP seconds)\n");
  sleep $SLEEP;
  $soapbox->dprint(1, "\n");
}

