-- created by Oraschemadoc Fri Jun 13 14:06:07 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE UNIQUE INDEX "RHNSAT"."RHN_URLPS_URL_PR_ID_STP_N_UQ" ON "RHNSAT"."RHN_URL_PROBE_STEP" ("URL_PROBE_ID", "STEP_NUMBER") 
  PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
