#!/bin/sh
# chkconfig: 2345 99 99
# description: Reports this guest's UUID to the satellite upon boot.

. /etc/rc.d/init.d/functions

PYTHONPATH="/usr/share/rhn:/usr/share/rhn/virtualization"
SCRIPTPATH="/usr/share/rhn/virtualization"

start() {
    python $SCRIPTPATH/report_uuid.py
    RETVAL=$?

    echo -n "Reporting guest UUID to RHN:"
    if [ $RETVAL -eq 0 ]; then echo_success; else echo_failure; fi
    echo

    return $RETVAL
}

case $1 in
    "start")
        start
        ;;
    *)
        echo "Usage: service rhn-virtualization-guest [start]"
        ;;
esac
