-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."DB_CHANGE_SCRIPT_EXPANDED" 
   (	"BUG_ID" NUMBER CONSTRAINT "DC_SCRIPTEXPANDED_BID_NN" NOT NULL ENABLE, 
	"SEQ_NO" NUMBER CONSTRAINT "DC_SCRIPTEXPANDED_SN_NN" NOT NULL ENABLE, 
	"LINE_NO" NUMBER CONSTRAINT "DC_SCRIPTEXPANDED_LN_NN" NOT NULL ENABLE, 
	"LINE" VARCHAR2(1000) CONSTRAINT "DC_SCRIPTEXPANDED_L_NN" NOT NULL ENABLE, 
	 CONSTRAINT "DC_SCRIPTEXPANDED_BID_SN_FK" FOREIGN KEY ("BUG_ID", "SEQ_NO")
	  REFERENCES "RHNSAT"."DB_CHANGE_SCRIPT" ("BUG_ID", "SEQ_NO") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
