-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."DB_CHANGE_RESOURCE_NAMES" 
   (	"RESOURCE_TYPE" VARCHAR2(255) CONSTRAINT "DC_RESOURCENAME_RT_NN" NOT NULL ENABLE, 
	"RESOURCE_NAME" VARCHAR2(255) CONSTRAINT "DC_RESOURCENAME_RN_NN" NOT NULL ENABLE, 
	 CONSTRAINT "DC_RESOURCENAME_RT_RN_PK" PRIMARY KEY ("RESOURCE_TYPE", "RESOURCE_NAME")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "DC_RESOURCENAME_RT_FK" FOREIGN KEY ("RESOURCE_TYPE")
	  REFERENCES "RHNSAT"."DB_CHANGE_RESOURCE_TYPES" ("RESOURCE_TYPE") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
