-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."DB_CHANGE_SCRIPT_PARSED" 
   (	"BUG_ID" NUMBER(12,0) CONSTRAINT "DB_CSP_BID_NN" NOT NULL ENABLE, 
	"SEQ_NO" NUMBER(12,0) CONSTRAINT "DB_CSP_SNO_NN" NOT NULL ENABLE, 
	"STMT_NO" NUMBER(12,0) CONSTRAINT "DB_CSP_STNO_NN" NOT NULL ENABLE, 
	"LINE_NO" NUMBER(12,0) CONSTRAINT "DB_CSP_LNO_NN" NOT NULL ENABLE, 
	"LINE" VARCHAR2(1000) CONSTRAINT "DB_CSP_LINE_NN" NOT NULL ENABLE, 
	 CONSTRAINT "DBCSP_DBCSC_BUG_ID_SEQ_NO_FK" FOREIGN KEY ("BUG_ID", "SEQ_NO")
	  REFERENCES "RHNSAT"."DB_CHANGE_SCRIPT" ("BUG_ID", "SEQ_NO") ON DELETE CASCADE ENABLE NOVALIDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
