-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."DB_CHANGE_LOCK" 
   (	"LOCKED" CHAR(1) CONSTRAINT "DC_LOCK_LOCKED_NN" NOT NULL ENABLE, 
	"BUG_ID" NUMBER CONSTRAINT "DC_LOCK_BID_NN" NOT NULL ENABLE, 
	"SEQ_NO" NUMBER CONSTRAINT "DC_LOCK_SN_NN" NOT NULL ENABLE, 
	"OWNER" VARCHAR2(255) CONSTRAINT "DC_LOCK_OWNER_NN" NOT NULL ENABLE, 
	"LOCK_DATE" DATE CONSTRAINT "DC_LOCK_LD_NN" NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
