-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."DB_CHANGE_RESOURCES" 
   (	"BUG_ID" NUMBER CONSTRAINT "DC_RESOURCES_BID_NN" NOT NULL ENABLE, 
	"SEQ_NO" NUMBER CONSTRAINT "DC_RESOURCES_SN_NN" NOT NULL ENABLE, 
	"RESOURCE_TYPE" VARCHAR2(255) CONSTRAINT "DC_RESOURCES_RT_NN" NOT NULL ENABLE, 
	"RESOURCE_NAME" VARCHAR2(255) CONSTRAINT "DC_RESOURCES_RN_NN" NOT NULL ENABLE, 
	"CHANGE_TYPE" VARCHAR2(255) CONSTRAINT "DC_RESOURCES_CT_NN" NOT NULL ENABLE, 
	 CONSTRAINT "DC_RESOURCES_BID_SN_FK" FOREIGN KEY ("BUG_ID", "SEQ_NO")
	  REFERENCES "RHNSAT"."DB_CHANGE_SCRIPT" ("BUG_ID", "SEQ_NO") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "DC_RESOURCES_RT_RN_FK" FOREIGN KEY ("RESOURCE_TYPE", "RESOURCE_NAME")
	  REFERENCES "RHNSAT"."DB_CHANGE_RESOURCE_NAMES" ("RESOURCE_TYPE", "RESOURCE_NAME") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "DC_RESOURCES_CT_FK" FOREIGN KEY ("CHANGE_TYPE")
	  REFERENCES "RHNSAT"."DB_CHANGE_RESOURCE_CHANGES" ("CHANGE_TYPE") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
