-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_HOST_PROBE" 
   (	"PROBE_ID" NUMBER(12,0) CONSTRAINT "RHN_HSTPB_PROBE_ID_NN" NOT NULL ENABLE, 
	"PROBE_TYPE" VARCHAR2(12) DEFAULT 'host' CONSTRAINT "RHN_HSTPB_PROBE_TYPE_NN" NOT NULL ENABLE, 
	"HOST_ID" NUMBER(12,0) CONSTRAINT "RHN_HSTPB_HOST_ID_NN" NOT NULL ENABLE, 
	"SAT_CLUSTER_ID" NUMBER(12,0) CONSTRAINT "RHN_HSTPB_SAT_CL_ID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_HSTPB_PROBE_TYPE_CK" CHECK ( probe_type='host' ) ENABLE, 
	 CONSTRAINT "RHN_HSTPB_PROBE_ID_PK" PRIMARY KEY ("PROBE_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_HSTPB_HOST_ID_FK" FOREIGN KEY ("HOST_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_HSTPB_PROBE_PROBE_ID_FK" FOREIGN KEY ("PROBE_ID", "PROBE_TYPE")
	  REFERENCES "RHNSAT"."RHN_PROBE" ("RECID", "PROBE_TYPE") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_HSTPB_SATCL_ID_FK" FOREIGN KEY ("SAT_CLUSTER_ID")
	  REFERENCES "RHNSAT"."RHN_SAT_CLUSTER" ("RECID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
