-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_COMMAND_PARAMETER" 
   (	"COMMAND_ID" NUMBER(12,0) CONSTRAINT "RHN_CPARM_COMMAND_ID_NN" NOT NULL ENABLE, 
	"PARAM_NAME" VARCHAR2(40) CONSTRAINT "RHN_CPARM_PARAM_NAME_NN" NOT NULL ENABLE, 
	"PARAM_TYPE" VARCHAR2(10) DEFAULT 'config' CONSTRAINT "RHN_CPARM_PARAM_TYPE_NN" NOT NULL ENABLE, 
	"DATA_TYPE_NAME" VARCHAR2(10) CONSTRAINT "RHN_CPARM_DATA_TYPE_NAME_NN" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(80) CONSTRAINT "RHN_CPARM_DESCRIPTION_NN" NOT NULL ENABLE, 
	"MANDATORY" CHAR(1) DEFAULT '0' CONSTRAINT "RHN_CPARM_MANDATORY_NN" NOT NULL ENABLE, 
	"DEFAULT_VALUE" VARCHAR2(1024), 
	"MIN_VALUE" NUMBER, 
	"MAX_VALUE" NUMBER, 
	"FIELD_ORDER" NUMBER CONSTRAINT "RHN_CPARM_FIELD_ORDER_NN" NOT NULL ENABLE, 
	"FIELD_WIDGET_NAME" VARCHAR2(20) CONSTRAINT "RHN_CPARM_FIELD_WIDGET_NAME_NN" NOT NULL ENABLE, 
	"FIELD_VISIBLE_LENGTH" NUMBER, 
	"FIELD_MAXIMUM_LENGTH" NUMBER, 
	"FIELD_VISIBLE" CHAR(1) DEFAULT '1' CONSTRAINT "RHN_CPARM_FIELD_VISIBLE_NN" NOT NULL ENABLE, 
	"DEFAULT_VALUE_VISIBLE" CHAR(1) DEFAULT '1' CONSTRAINT "RHN_CPARM_DEF_VALUE_VIS_NN" NOT NULL ENABLE, 
	"LAST_UPDATE_USER" VARCHAR2(40), 
	"LAST_UPDATE_DATE" DATE, 
	 CONSTRAINT "RHN_CPARM_ID_PARM_NAME_PK" PRIMARY KEY ("COMMAND_ID", "PARAM_NAME")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CPARM_ID_P_NAME_P_TYPE_UQ" UNIQUE ("COMMAND_ID", "PARAM_NAME", "PARAM_TYPE")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CPARM_ID_FIELD_ORDE_UQ" UNIQUE ("COMMAND_ID", "FIELD_ORDER")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CPARM_CMD_COMMAND_ID_FK" FOREIGN KEY ("COMMAND_ID")
	  REFERENCES "RHNSAT"."RHN_COMMAND" ("RECID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_CPARM_SDTYP_NAME_FK" FOREIGN KEY ("DATA_TYPE_NAME")
	  REFERENCES "RHNSAT"."RHN_SEMANTIC_DATA_TYPE" ("NAME") ENABLE, 
	 CONSTRAINT "RHN_CPARM_WDGT_FLD_WDGT_N_FK" FOREIGN KEY ("FIELD_WIDGET_NAME")
	  REFERENCES "RHNSAT"."RHN_WIDGET" ("NAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
