-- created by Oraschemadoc Fri Jun 13 14:05:58 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_REDIRECT_GROUP_TARGETS" 
   (	"REDIRECT_ID" NUMBER(12,0) CONSTRAINT "RHN_RDRGT_REDIRECT_ID_NN" NOT NULL ENABLE, 
	"CONTACT_GROUP_ID" NUMBER(12,0) CONSTRAINT "RHN_RDRGT_GROUP_ID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_RDRGT_PK" PRIMARY KEY ("REDIRECT_ID", "CONTACT_GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_RDRGT_RDRCT_REDIRECT_ID_FK" FOREIGN KEY ("REDIRECT_ID")
	  REFERENCES "RHNSAT"."RHN_REDIRECTS" ("RECID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
