-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_DB_ENVIRONMENT" 
   (	"DB_NAME" VARCHAR2(20) CONSTRAINT "RHN_DBENV_DB_NAME_NN" NOT NULL ENABLE, 
	"ENVIRONMENT" VARCHAR2(255), 
	 CONSTRAINT "RHN_DBENV_DB_NAME_PK" PRIMARY KEY ("DB_NAME")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_DBENV_ENVIR_ENVIRONMENT_FK" FOREIGN KEY ("ENVIRONMENT")
	  REFERENCES "RHNSAT"."RHN_ENVIRONMENT" ("NAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
