-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_COMMAND_QUEUE_EXECS_BK" 
   (	"INSTANCE_ID" NUMBER(12,0) CONSTRAINT "RHN_CQCMDBK_INSTANCE_ID_NN" NOT NULL ENABLE, 
	"NETSAINT_ID" NUMBER(12,0) CONSTRAINT "RHN_CQCMDBK_NETSAINT_ID_NN" NOT NULL ENABLE, 
	"DATE_ACCEPTED" DATE, 
	"DATE_EXECUTED" DATE, 
	"EXIT_STATUS" NUMBER(5,0), 
	"EXECUTION_TIME" NUMBER(10,0), 
	"STDOUT" VARCHAR2(4000), 
	"STDERR" VARCHAR2(4000), 
	"LAST_UPDATE_DATE" DATE, 
	"TARGET_TYPE" VARCHAR2(10) CONSTRAINT "RHN_CQCMDBK_TARGET_TYPE_NN" NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
