-- created by Oraschemadoc Fri Jun 13 14:05:58 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_URL_PROBE_STEP" 
   (	"RECID" NUMBER(12,0) CONSTRAINT "RHN_URLPS_RECID_NN" NOT NULL ENABLE, 
	"URL_PROBE_ID" NUMBER(12,0) CONSTRAINT "RHN_URLPS_URL_PROB_ID_NN" NOT NULL ENABLE, 
	"STEP_NUMBER" NUMBER(3,0) CONSTRAINT "RHN_URLPS_URL_STEP_NO_NN" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255), 
	"URL" VARCHAR2(2000) CONSTRAINT "RHN_URLPS_URL_NN" NOT NULL ENABLE, 
	"PROTOCOL_METHOD" VARCHAR2(12) CONSTRAINT "RHN_URLPS_PROTOCOL_NN" NOT NULL ENABLE, 
	"VERIFY_LINKS" CHAR(1) DEFAULT 0 CONSTRAINT "RHN_URLPS_VER_LINKS_NN" NOT NULL ENABLE, 
	"LOAD_SUBSIDIARY" CHAR(1) DEFAULT 0 CONSTRAINT "RHN_URLPS_LOAD_SUB_NN" NOT NULL ENABLE, 
	"PATTERN" VARCHAR2(255), 
	"VPATTERN" VARCHAR2(255), 
	"POST_CONTENT" VARCHAR2(4000), 
	"POST_CONTENT_TYPE" VARCHAR2(255), 
	"CONNECT_WARN" NUMBER(10,3) DEFAULT 0 CONSTRAINT "RHN_URLPS_CONN_WARN_NN" NOT NULL ENABLE, 
	"CONNECT_CRIT" NUMBER(10,3) DEFAULT 0 CONSTRAINT "RHN_URLPS_CONN_CRIT_NN" NOT NULL ENABLE, 
	"LATENCY_WARN" NUMBER(10,3) DEFAULT 0 CONSTRAINT "RHN_URLPS_LATE_WARN_NN" NOT NULL ENABLE, 
	"LATENCY_CRIT" NUMBER(10,3) DEFAULT 0 CONSTRAINT "RHN_URLPS_LATE_CRIT_NN" NOT NULL ENABLE, 
	"DNS_WARN" NUMBER(10,3) DEFAULT 0 CONSTRAINT "RHN_URLPS_DNS_WARN_NN" NOT NULL ENABLE, 
	"DNS_CRIT" NUMBER(10,3) DEFAULT 0 CONSTRAINT "RHN_URLPS_DNS_CRIT_NN" NOT NULL ENABLE, 
	"TOTAL_WARN" NUMBER(10,3) DEFAULT 0 CONSTRAINT "RHN_URLPS_TOTAL_WARN_NN" NOT NULL ENABLE, 
	"TOTAL_CRIT" NUMBER(10,3) DEFAULT 0 CONSTRAINT "RHN_URLPS_TOTAL_CRIT_NN" NOT NULL ENABLE, 
	"TRANS_WARN" NUMBER(12,0) DEFAULT 0 CONSTRAINT "RHN_URLPS_TRANS_WARN_NN" NOT NULL ENABLE, 
	"TRANS_CRIT" NUMBER(12,0) DEFAULT 0 CONSTRAINT "RHN_URLPS_TRANS_CRIT_NN" NOT NULL ENABLE, 
	"THROUGH_WARN" NUMBER(12,0) DEFAULT 0 CONSTRAINT "RHN_URLPS_THRU_WARN_NN" NOT NULL ENABLE, 
	"THROUGH_CRIT" NUMBER(12,0) DEFAULT 0 CONSTRAINT "RHN_URLPS_THRU_CRIT_NN" NOT NULL ENABLE, 
	"COOKIE_KEY" VARCHAR2(255), 
	"COOKIE_VALUE" VARCHAR2(255), 
	"COOKIE_PATH" VARCHAR2(255), 
	"COOKIE_DOMAIN" VARCHAR2(255), 
	"COOKIE_PORT" NUMBER(5,0), 
	"COOKIE_SECURE" CHAR(1) DEFAULT 0 CONSTRAINT "RHN_URLPS_COOKIE_SEC_NN" NOT NULL ENABLE, 
	"COOKIE_MAXAGE" NUMBER(9,0), 
	 CONSTRAINT "RHN_URLPS_VER_LINKS_CK" CHECK (verify_links in ('0','1')) ENABLE, 
	 CONSTRAINT "RHN_URLPS_LOAD_SUB_CK" CHECK (load_subsidiary in ('0','1')) ENABLE, 
	 CONSTRAINT "RHN_URLPS_COOKIE_SEC_CK" CHECK (cookie_secure in ('0','1')) ENABLE, 
	 CONSTRAINT "RHN_URLPS_RECID_PK" PRIMARY KEY ("RECID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_URLPS_URLPB_URL_PR_ID_FK" FOREIGN KEY ("URL_PROBE_ID")
	  REFERENCES "RHNSAT"."RHN_URL_PROBE" ("PROBE_ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
