-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_INTERFACE_MONITORING" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_MONIF_SERVER_ID_NN" NOT NULL ENABLE, 
	"SERVER_NAME" VARCHAR2(32) CONSTRAINT "RHN_MONIF_SERVER_NAME_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_MONIF_SERVER_PK" PRIMARY KEY ("SERVER_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_MONIF_SERVER_NAME_FK" FOREIGN KEY ("SERVER_ID", "SERVER_NAME")
	  REFERENCES "RHNSAT"."RHNSERVERNETINTERFACE" ("SERVER_ID", "NAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
