-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_COMMAND_QUEUE_INSTANCES" 
   (	"RECID" NUMBER(12,0) CONSTRAINT "RHN_CQINS_RECID_NN" NOT NULL ENABLE, 
	"COMMAND_ID" NUMBER(12,0) CONSTRAINT "RHN_CQINS_COMMAND_ID_NN" NOT NULL ENABLE, 
	"NOTES" VARCHAR2(2000), 
	"DATE_SUBMITTED" DATE CONSTRAINT "RHN_CQINS_DATE_SUBMITTED_NN" NOT NULL ENABLE, 
	"EXPIRATION_DATE" DATE CONSTRAINT "RHN_CQINS_EXPIRATION_DATE_NN" NOT NULL ENABLE, 
	"NOTIFY_EMAIL" VARCHAR2(50), 
	"TIMEOUT" NUMBER(5,0), 
	"LAST_UPDATE_USER" VARCHAR2(40), 
	"LAST_UPDATE_DATE" DATE, 
	 CONSTRAINT "RHN_CQINS_RECID_PK" PRIMARY KEY ("RECID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CQINS_CQCMD_COMMAND_ID_FK" FOREIGN KEY ("COMMAND_ID")
	  REFERENCES "RHNSAT"."RHN_COMMAND_QUEUE_COMMANDS" ("RECID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
