-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_CONTACT_GROUP_MEMBERS" 
   (	"CONTACT_GROUP_ID" NUMBER CONSTRAINT "RHN_CNTGM_CGID_NN" NOT NULL ENABLE, 
	"ORDER_NUMBER" NUMBER CONSTRAINT "RHN_CNTGM_ON_NN" NOT NULL ENABLE, 
	"MEMBER_CONTACT_METHOD_ID" NUMBER, 
	"MEMBER_CONTACT_GROUP_ID" NUMBER, 
	"LAST_UPDATE_USER" VARCHAR2(40) CONSTRAINT "RHN_CNTGM_LAST_USER_NN" NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE CONSTRAINT "RHN_CNTGM_LAST_DATE_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CNTGM_CGID_ORDER_PK" PRIMARY KEY ("CONTACT_GROUP_ID", "ORDER_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CNTGM_CGID_FK" FOREIGN KEY ("CONTACT_GROUP_ID")
	  REFERENCES "RHNSAT"."RHN_CONTACT_GROUPS" ("RECID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_CNTGM_MCMID_FK" FOREIGN KEY ("MEMBER_CONTACT_METHOD_ID")
	  REFERENCES "RHNSAT"."RHN_CONTACT_METHODS" ("RECID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_CNTGM_MCGID_FK" FOREIGN KEY ("MEMBER_CONTACT_GROUP_ID")
	  REFERENCES "RHNSAT"."RHN_CONTACT_GROUPS" ("RECID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
