-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_CHECK_SUITES" 
   (	"RECID" NUMBER(12,0) CONSTRAINT "RHN_CKSUT_RECID_NN" NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER(12,0) CONSTRAINT "RHN_CKSUT_CUSTID_NN" NOT NULL ENABLE, 
	"SUITE_NAME" VARCHAR2(40) CONSTRAINT "RHN_CKSUT_SUITE_NAME_NN" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255), 
	"LAST_UPDATE_USER" VARCHAR2(40) CONSTRAINT "RHN_CKSUT_LAST_USER_NN" NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE CONSTRAINT "RHN_CKSUT_LAST_DATE_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CKSUT_RECID_PK" PRIMARY KEY ("RECID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CKSUT_CSTMR_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
