-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_PROBE" 
   (	"RECID" NUMBER(12,0) CONSTRAINT "RHN_PROBE_RECID_NN" NOT NULL ENABLE, 
	"PROBE_TYPE" VARCHAR2(15) CONSTRAINT "RHN_PROBE_PROBE_TYPE_NN" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255) CONSTRAINT "RHN_PROBE_DESCRIPTION_NN" NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER(12,0) CONSTRAINT "RHN_PROBE_CUST_ID_NN" NOT NULL ENABLE, 
	"COMMAND_ID" NUMBER(16,0) CONSTRAINT "RHN_PROBE_COMMAND_ID_NN" NOT NULL ENABLE, 
	"CONTACT_GROUP_ID" NUMBER(12,0), 
	"NOTIFY_CRITICAL" CHAR(1), 
	"NOTIFY_WARNING" CHAR(1), 
	"NOTIFY_UNKNOWN" CHAR(1), 
	"NOTIFY_RECOVERY" CHAR(1), 
	"NOTIFICATION_INTERVAL_MINUTES" NUMBER(16,0) CONSTRAINT "RHN_PROBE_NOTIF_INT_NN" NOT NULL ENABLE, 
	"CHECK_INTERVAL_MINUTES" NUMBER(16,0) CONSTRAINT "RHN_PROBE_CHK_INT_NN" NOT NULL ENABLE, 
	"RETRY_INTERVAL_MINUTES" NUMBER(16,0) CONSTRAINT "RHN_PROBE_RETRY_INT_NN" NOT NULL ENABLE, 
	"MAX_ATTEMPTS" NUMBER(16,0), 
	"LAST_UPDATE_USER" VARCHAR2(40), 
	"LAST_UPDATE_DATE" DATE, 
	 CONSTRAINT "RHN_PROBE_RECID_PK" PRIMARY KEY ("RECID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_PROBE_RECID_PROBE_TYPE_UQ" UNIQUE ("RECID", "PROBE_TYPE")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_PROBE_CMMND_COMMAND_ID_FK" FOREIGN KEY ("COMMAND_ID")
	  REFERENCES "RHNSAT"."RHN_COMMAND" ("RECID") ENABLE, 
	 CONSTRAINT "RHN_PROBE_CSTMR_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_PROBE_PRBTP_PROBE_TYPE_FK" FOREIGN KEY ("PROBE_TYPE")
	  REFERENCES "RHNSAT"."RHN_PROBE_TYPES" ("PROBE_TYPE") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
