-- created by Oraschemadoc Fri Jun 13 14:05:58 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_TIME_ZONE_NAMES" 
   (	"RECID" NUMBER(12,0) CONSTRAINT "RHN_TZNMS_RECID_NN" NOT NULL ENABLE, 
	"JAVA_ID" VARCHAR2(40) CONSTRAINT "RHN_TZNMS_JAVA_ID_NN" NOT NULL ENABLE, 
	"DISPLAY_NAME" VARCHAR2(60) CONSTRAINT "RHN_TZNMS_DISPLAY_NAME_NN" NOT NULL ENABLE, 
	"GMT_OFFSET_MINUTES" NUMBER(4,0) CONSTRAINT "RHN_TZNMS_GMT_OFFSET_NN" NOT NULL ENABLE, 
	"USE_DAYLIGHT_TIME" CHAR(1) CONSTRAINT "RHN_TZNMS_USE_DST_NN" NOT NULL ENABLE, 
	"LAST_UPDATE_USER" VARCHAR2(40), 
	"LAST_UPDATE_DATE" DATE, 
	 CONSTRAINT "RHN_TZNMS_JAVA_ID_PK" PRIMARY KEY ("JAVA_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_TIME_ZONE_NAMES_UQ" UNIQUE ("DISPLAY_NAME")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
