-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_CURRENT_STATE_SUMMARIES" 
   (	"CUSTOMER_ID" NUMBER(12,0) CONSTRAINT "RHN_CURSU_CUST_ID_NN" NOT NULL ENABLE, 
	"TEMPLATE_ID" VARCHAR2(10) CONSTRAINT "RHN_CURSU_TEMPLATE_ID_NN" NOT NULL ENABLE, 
	"STATE" VARCHAR2(20) CONSTRAINT "RHN_CURSU_STATE_NN" NOT NULL ENABLE, 
	"STATE_COUNT" NUMBER(9,0), 
	"LAST_CHECK" DATE, 
	 CONSTRAINT "RHN_CURRENT_STATE_SUMMARIES_PK" PRIMARY KEY ("CUSTOMER_ID", "TEMPLATE_ID", "STATE")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
