-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_COMMAND_QUEUE_INSTANCES_BK" 
   (	"RECID" NUMBER(12,0) CONSTRAINT "RHN_CQINSBK_RECID_NN" NOT NULL ENABLE, 
	"COMMAND_ID" NUMBER(12,0) CONSTRAINT "RHN_CQINSBK_COMMAND_ID_NN" NOT NULL ENABLE, 
	"NOTES" VARCHAR2(2000), 
	"DATE_SUBMITTED" DATE CONSTRAINT "RHN_CQINSBK_DATE_SUB_NN" NOT NULL ENABLE, 
	"EXPIRATION_DATE" DATE CONSTRAINT "RHN_CQINSBK_EXP_DATE_NN" NOT NULL ENABLE, 
	"NOTIFY_EMAIL" VARCHAR2(50), 
	"TIMEOUT" NUMBER(5,0), 
	"LAST_UPDATE_USER" VARCHAR2(40), 
	"LAST_UPDATE_DATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
