-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_COMMAND" 
   (	"RECID" NUMBER(12,0) CONSTRAINT "RHN_CMMND_RECID_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(40) CONSTRAINT "RHN_CMMND_NAME_NN" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(80) CONSTRAINT "RHN_CMMND_DESC_NN" NOT NULL ENABLE, 
	"GROUP_NAME" VARCHAR2(40), 
	"ALLOWED_IN_SUITE" CHAR(1) DEFAULT '1' CONSTRAINT "RHN_CMMND_ALLOWED_NN" NOT NULL ENABLE, 
	"COMMAND_CLASS" VARCHAR2(255) DEFAULT '/opt/home/nocpulse/libexec/plugin' CONSTRAINT "RHN_CMMND_CLASS_NN" NOT NULL ENABLE, 
	"ENABLED" CHAR(1) DEFAULT '1' CONSTRAINT "RHN_CMMND_ENABLED_NN" NOT NULL ENABLE, 
	"FOR_HOST_PROBE" CHAR(1) DEFAULT '0' CONSTRAINT "RHN_CMMND_HOST_PROBE_NN" NOT NULL ENABLE, 
	"LAST_UPDATE_USER" VARCHAR2(40), 
	"LAST_UPDATE_DATE" DATE, 
	"SYSTEM_REQUIREMENTS" VARCHAR2(40), 
	"VERSION_SUPPORT" VARCHAR2(1024), 
	"HELP_URL" VARCHAR2(1024), 
	 CONSTRAINT "RHN_CMMND_RECID_PK" PRIMARY KEY ("RECID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CMMND_NAME_UQ" UNIQUE ("RECID", "COMMAND_CLASS")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CMMND_CMDGR_GROUP_NAME_FK" FOREIGN KEY ("GROUP_NAME")
	  REFERENCES "RHNSAT"."RHN_COMMAND_GROUPS" ("GROUP_NAME") ENABLE, 
	 CONSTRAINT "RHN_CMMND_COMCL_CLASS_NAME_FK" FOREIGN KEY ("COMMAND_CLASS")
	  REFERENCES "RHNSAT"."RHN_COMMAND_CLASS" ("CLASS_NAME") ENABLE, 
	 CONSTRAINT "RHN_CMMND_SYS_REQS_FK" FOREIGN KEY ("SYSTEM_REQUIREMENTS")
	  REFERENCES "RHNSAT"."RHN_COMMAND_REQUIREMENTS" ("NAME") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
