-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_COMMAND_QUEUE_COMMANDS" 
   (	"RECID" NUMBER(12,0) CONSTRAINT "RHN_CQCMD_RECID_NN" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(40) CONSTRAINT "RHN_CQCMD_DESCRIPTION_NN" NOT NULL ENABLE, 
	"NOTES" VARCHAR2(2000), 
	"COMMAND_LINE" VARCHAR2(2000) CONSTRAINT "RHN_CQCMD_COMMAND_LINE_NN" NOT NULL ENABLE, 
	"PERMANENT" CHAR(1) CONSTRAINT "RHN_CQCMD_PERMANENT_NN" NOT NULL ENABLE, 
	"RESTARTABLE" CHAR(1) CONSTRAINT "RHN_CQCMD_RESTARTABLE_NN" NOT NULL ENABLE, 
	"EFFECTIVE_USER" VARCHAR2(40) CONSTRAINT "RHN_CQCMD_EFFECTIVE_USR_NN" NOT NULL ENABLE, 
	"EFFECTIVE_GROUP" VARCHAR2(40) CONSTRAINT "RHN_CQCMD_EFFECTIVE_GRP_NN" NOT NULL ENABLE, 
	"LAST_UPDATE_USER" VARCHAR2(40), 
	"LAST_UPDATE_DATE" DATE, 
	 CONSTRAINT "RHN_CQCMD_RECID_PK" PRIMARY KEY ("RECID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
