-- created by Oraschemadoc Fri Jun 13 14:05:58 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_SERVICE_PROBE_ORIGINS" 
   (	"SERVICE_PROBE_ID" NUMBER(12,0) CONSTRAINT "RHN_SRVPO_SERV_P_ID_NN" NOT NULL ENABLE, 
	"ORIGIN_PROBE_ID" NUMBER(12,0), 
	"DECOUPLED" CHAR(1) DEFAULT '0' CONSTRAINT "RHN_SRVPO_DECOUPLED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SRVPO_SERV_PR_ID_ORIG_UQ" UNIQUE ("SERVICE_PROBE_ID", "ORIGIN_PROBE_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SRVPO_CHKPB_ORIG_PR_ID_FK" FOREIGN KEY ("ORIGIN_PROBE_ID")
	  REFERENCES "RHNSAT"."RHN_CHECK_SUITE_PROBE" ("PROBE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SRVPO_PR_SERV_PR_FK" FOREIGN KEY ("SERVICE_PROBE_ID")
	  REFERENCES "RHNSAT"."RHN_PROBE" ("RECID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
