-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_CONTACT_GROUPS" 
   (	"RECID" NUMBER(12,0) CONSTRAINT "RHN_CNTGP_RECID_NN" NOT NULL ENABLE, 
	"CONTACT_GROUP_NAME" VARCHAR2(30) CONSTRAINT "RHN_CNTGP_GROUP_NAME_NN" NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER(12,0) CONSTRAINT "RHN_CNTGP_CUST_ID_NN" NOT NULL ENABLE, 
	"STRATEGY_ID" NUMBER(12,0) CONSTRAINT "RHN_CNTGP_STRAT_ID_NN" NOT NULL ENABLE, 
	"ACK_WAIT" NUMBER(4,0) CONSTRAINT "RHN_CNTGP_ACK_WAIT_NN" NOT NULL ENABLE, 
	"ROTATE_FIRST" CHAR(1) CONSTRAINT "RHN_CNTGP_ROTATE_F_NN" NOT NULL ENABLE, 
	"LAST_UPDATE_USER" VARCHAR2(40) CONSTRAINT "RHN_CNTGP_LAST_USER_NN" NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE CONSTRAINT "RHN_CNTGP_LAST_DATE_NN" NOT NULL ENABLE, 
	"NOTIFICATION_FORMAT_ID" NUMBER(12,0) DEFAULT 4 CONSTRAINT "RHN_CNTGP_NOTIF_FMT_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CNTGP_RECID_NOTZERO" CHECK (recid > 0) ENABLE, 
	 CONSTRAINT "RHN_CNTGP_ACK_WAIT_CK" CHECK ( ack_wait < 20160 ) ENABLE, 
	 CONSTRAINT "RHN_CNTGP_ROTATE_F_CK" CHECK (rotate_first in (0,1)) ENABLE, 
	 CONSTRAINT "RHN_CNTGP_RECID_PK" PRIMARY KEY ("RECID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CNTGP_CSTMR_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CNTGP_STRAT_STRATEGY_ID_FK" FOREIGN KEY ("STRATEGY_ID")
	  REFERENCES "RHNSAT"."RHN_STRATEGIES" ("RECID") ENABLE, 
	 CONSTRAINT "RHN_NTFMT_CNTGP_ID_FK" FOREIGN KEY ("NOTIFICATION_FORMAT_ID")
	  REFERENCES "RHNSAT"."RHN_NOTIFICATION_FORMATS" ("RECID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
