-- created by Oraschemadoc Fri Jun 13 14:05:58 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_URL_PROBE" 
   (	"USERNAME" VARCHAR2(40), 
	"PASSWORD" VARCHAR2(255), 
	"COOKIE_ENABLED" CHAR(1) DEFAULT 0 CONSTRAINT "RHN_URLPB_COOKIE_EN_NN" NOT NULL ENABLE, 
	"MULTI_STEP" CHAR(1) DEFAULT 0 CONSTRAINT "RHN_URLPB_MULTI_STEP_NN" NOT NULL ENABLE, 
	"RUN_ON_SCOUTS" CHAR(1) DEFAULT ('1') CONSTRAINT "RHN_URLPB_RUN_ON_SCOUTS_NN" NOT NULL ENABLE, 
	"PROBE_ID" NUMBER(12,0) CONSTRAINT "RHN_URLPB_PROBE_ID_NN" NOT NULL ENABLE, 
	"PROBE_TYPE" VARCHAR2(12) DEFAULT 'url' CONSTRAINT "RHN_URLPB_PROBE_TYPE_NN" NOT NULL ENABLE, 
	"SAT_CLUSTER_ID" NUMBER(12,0), 
	"SCOUT_WARNING_THRESHOLD_IS_ALL" CHAR(1) DEFAULT '1' CONSTRAINT "RHN_URLPB_SCOUT_WARN_ISALL_NN" NOT NULL ENABLE, 
	"SCOUT_CRIT_THRESHOLD_IS_ALL" CHAR(1) DEFAULT '1' CONSTRAINT "RHN_URLPB_SCOUT_CRIT_ISALL_NN" NOT NULL ENABLE, 
	"SCOUT_WARNING_THRESHOLD" NUMBER(12,0) DEFAULT -1, 
	"SCOUT_CRITICAL_THRESHOLD" NUMBER(12,0) DEFAULT -1, 
	 CONSTRAINT "RHN_URLPB_MULTI_STEP_CK" CHECK (multi_step in ('0','1')) ENABLE, 
	 CONSTRAINT "RHN_URLPB_RUN_ON_SCOUTS_CK" CHECK (run_on_scouts in ('0','1')) ENABLE, 
	 CONSTRAINT "RHN_URLPB_PROBE_TYPE_CK" CHECK (probe_type='url') ENABLE, 
	 CONSTRAINT "RHN_URLPB_PROBE_ID_PK" PRIMARY KEY ("PROBE_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_URLPB_PROBE_PR_ID_PR_FK" FOREIGN KEY ("PROBE_ID", "PROBE_TYPE")
	  REFERENCES "RHNSAT"."RHN_PROBE" ("RECID", "PROBE_TYPE") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
