-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_LL_NETSAINT" 
   (	"NETSAINT_ID" NUMBER CONSTRAINT "RHN_LLNET_NETSAINT_ID_NN" NOT NULL ENABLE, 
	"CITY" VARCHAR2(255), 
	 CONSTRAINT "RHN_LLNTS_SAT_CLUSTER_IDFK" FOREIGN KEY ("NETSAINT_ID")
	  REFERENCES "RHNSAT"."RHN_SAT_CLUSTER" ("RECID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
