-- created by Oraschemadoc Fri Jun 13 14:05:57 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_CONFIG_MACRO" 
   (	"ENVIRONMENT" VARCHAR2(255) CONSTRAINT "RHN_CONFM_ENV_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) CONSTRAINT "RHN_CONFM_NAME_NN" NOT NULL ENABLE, 
	"DEFINITION" VARCHAR2(255), 
	"DESCRIPTION" VARCHAR2(255), 
	"EDITABLE" CHAR(1) DEFAULT 0 CONSTRAINT "RHN_CONFM_EDITABLE_NN" NOT NULL ENABLE, 
	"LAST_UPDATE_USER" VARCHAR2(40), 
	"LAST_UPDATE_DATE" DATE, 
	 CONSTRAINT "RHN_CONFM_ENVIRONMENT_NAME_PK" PRIMARY KEY ("ENVIRONMENT", "NAME")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CONFM_ENVIR_ENVIRONMENT_FK" FOREIGN KEY ("ENVIRONMENT")
	  REFERENCES "RHNSAT"."RHN_ENVIRONMENT" ("NAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
