-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_CHECK_SUITE_PROBE" 
   (	"PROBE_ID" NUMBER(12,0) CONSTRAINT "RHN_CKSPB_PROBE_ID_NN" NOT NULL ENABLE, 
	"PROBE_TYPE" VARCHAR2(12) DEFAULT 'suite' CONSTRAINT "RHN_CKSPB_PROBE_TYPE_NN" NOT NULL ENABLE, 
	"CHECK_SUITE_ID" NUMBER(12,0) CONSTRAINT "RHN_CKSPB_CHECK_SUITE_ID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CKSPB_PROBE_TYPE_CK" CHECK ( probe_type = 'suite' ) ENABLE, 
	 CONSTRAINT "RHN_CKSPB_PROBE_ID_PK" PRIMARY KEY ("PROBE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CKSPB_CKSUT_CK_SUITE_ID_FK" FOREIGN KEY ("CHECK_SUITE_ID")
	  REFERENCES "RHNSAT"."RHN_CHECK_SUITES" ("RECID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
