-- created by Oraschemadoc Fri Jun 13 14:05:58 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHN_SAT_NODE_PROBE" 
   (	"PROBE_ID" NUMBER(12,0) CONSTRAINT "RHN_SNDPB_PROBE_ID_NN" NOT NULL ENABLE, 
	"PROBE_TYPE" VARCHAR2(12) DEFAULT 'satnode' CONSTRAINT "RHN_SNDPB_PROBE_TYPE_NN" NOT NULL ENABLE, 
	"SAT_NODE_ID" NUMBER(12,0) CONSTRAINT "RHN_SNDPB_SAT_NODE_ID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SNDPB_PROBE_TYPE_CK" CHECK (probe_type='satnode') ENABLE, 
	 CONSTRAINT "RHN_SNDPB_PROBE_ID_PK" PRIMARY KEY ("PROBE_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SNDPB_PR_RECID_PR_TYP_FK" FOREIGN KEY ("PROBE_ID", "PROBE_TYPE")
	  REFERENCES "RHNSAT"."RHN_PROBE" ("RECID", "PROBE_TYPE") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SNDPB_SATND_SAT_ND_ID_FK" FOREIGN KEY ("SAT_NODE_ID")
	  REFERENCES "RHNSAT"."RHN_SAT_NODE" ("RECID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
