-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNACTION" 
   (	"ID" NUMBER CONSTRAINT "RHN_ACTION_ID_NN" NOT NULL ENABLE, 
	"ORG_ID" NUMBER CONSTRAINT "RHN_ACTION_OID_NN" NOT NULL ENABLE, 
	"ACTION_TYPE" NUMBER CONSTRAINT "RHN_ACTION_AT_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(128), 
	"SCHEDULER" NUMBER, 
	"EARLIEST_ACTION" DATE CONSTRAINT "RHN_ACTION_EA_NN" NOT NULL ENABLE, 
	"VERSION" NUMBER DEFAULT 0 CONSTRAINT "RHN_ACTION_VERSION_NN" NOT NULL ENABLE, 
	"ARCHIVED" NUMBER DEFAULT 0 CONSTRAINT "RHN_ACTION_ARCHIVED_NN" NOT NULL ENABLE, 
	"PREREQUISITE" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTION_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTION_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACTION_ARCHIVED_CK" CHECK (archived in (0, 1)) ENABLE, 
	 CONSTRAINT "RHN_ACTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_ACTION_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ACTION_AT_FK" FOREIGN KEY ("ACTION_TYPE")
	  REFERENCES "RHNSAT"."RHNACTIONTYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_ACTION_SCHEDULER_FK" FOREIGN KEY ("SCHEDULER")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_ACTION_PREREQ_FK" FOREIGN KEY ("PREREQUISITE")
	  REFERENCES "RHNSAT"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
