-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNACTIONDAEMONCONFIG" 
   (	"ACTION_ID" NUMBER CONSTRAINT "RHN_ACTIONDC_AID_NN" NOT NULL ENABLE, 
	"INTERVAL" NUMBER CONSTRAINT "RHN_ACTIONDC_INT_NN" NOT NULL ENABLE, 
	"RESTART" CHAR(1) DEFAULT 'Y' CONSTRAINT "RHN_ACTIONDC_REST_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTIONDC_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTIONDC_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACTIONDC_REST_CK" CHECK (restart in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_ACTIONDC_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RHNSAT"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
