-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNACTIONCONFIGFILENAME" 
   (	"ACTION_ID" NUMBER CONSTRAINT "RHN_ACTIONCF_NAME_AID_NN" NOT NULL ENABLE, 
	"SERVER_ID" NUMBER CONSTRAINT "RHN_ACTIONCF_NAME_SID_NN" NOT NULL ENABLE, 
	"CONFIG_FILE_NAME_ID" NUMBER CONSTRAINT "RHN_ACTIONCF_NAME_CFNID_NN" NOT NULL ENABLE, 
	"CONFIG_REVISION_ID" NUMBER, 
	"FAILURE_ID" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTIONCF_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTIONCF_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACTIONCF_NAME_CFNID_FK" FOREIGN KEY ("CONFIG_FILE_NAME_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGFILENAME" ("ID") ENABLE, 
	 CONSTRAINT "RHN_ACTIONCF_NAME_CRID_FK" FOREIGN KEY ("CONFIG_REVISION_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGREVISION" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_ACTIONCF_FAILURE_ID_FK" FOREIGN KEY ("FAILURE_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGFILEFAILURE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_ACTIONCF_NAME_AID_SID_FK" FOREIGN KEY ("SERVER_ID", "ACTION_ID")
	  REFERENCES "RHNSAT"."RHNSERVERACTION" ("SERVER_ID", "ACTION_ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
