-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNACTIONPACKAGEORDER" 
   (	"ACTION_PACKAGE_ID" NUMBER CONSTRAINT "RHN_ACT_PKG_APID_NN" NOT NULL ENABLE, 
	"PACKAGE_ORDER" NUMBER CONSTRAINT "RHN_ACT_PKG_ORDER_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACT_PKG_APID_FK" FOREIGN KEY ("ACTION_PACKAGE_ID")
	  REFERENCES "RHNSAT"."RHNACTIONPACKAGE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
