-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNACTIONTYPE" 
   (	"ID" NUMBER CONSTRAINT "RHN_ACTION_TYPE_ID_NN" NOT NULL ENABLE, 
	"LABEL" VARCHAR2(48) CONSTRAINT "RHN_ACTION_TYPE_LABEL_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(96) CONSTRAINT "RHN_ACTION_TYPE_NAME_NN" NOT NULL ENABLE, 
	"TRIGGER_SNAPSHOT" CHAR(1) DEFAULT ('N') CONSTRAINT "RHN_ACTION_TYPE_TRIGSNAP_NN" NOT NULL ENABLE, 
	"UNLOCKED_ONLY" CHAR(1) DEFAULT ('N') CONSTRAINT "RHN_ACTION_TYPE_UNLCK_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACTION_TYPE_TRIGSNAP_CK" CHECK (trigger_snapshot in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_ACTION_TYPE_UNLCK_CK" CHECK (unlocked_only in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_ACTION_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
