-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNARCHTYPEACTIONS" 
   (	"ARCH_TYPE_ID" NUMBER CONSTRAINT "RHN_ARCHTYPEACTS_ATID_NN" NOT NULL ENABLE, 
	"ACTION_STYLE" VARCHAR2(64) CONSTRAINT "RHN_ARCHTYPEACTS_AS_NN" NOT NULL ENABLE, 
	"ACTION_TYPE_ID" NUMBER CONSTRAINT "RHN_ARCHTYPEACTS_ACTID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ARCHTYPEACTS_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ARCHTYPEACTS_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ARCHTYPEACTS_ATID_FK" FOREIGN KEY ("ARCH_TYPE_ID")
	  REFERENCES "RHNSAT"."RHNARCHTYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_ARCHTYPEACTS_ACTID_FK" FOREIGN KEY ("ACTION_TYPE_ID")
	  REFERENCES "RHNSAT"."RHNACTIONTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
