-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNAPPINSTALLINSTANCE" 
   (	"ID" NUMBER CONSTRAINT "RHN_APPINST_INSTANCE_ID_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(128) CONSTRAINT "RHN_APPINST_INSTANCE_NAME_NN" NOT NULL ENABLE, 
	"LABEL" VARCHAR2(128) CONSTRAINT "RHN_APPINST_INSTANCE_LABEL_NN" NOT NULL ENABLE, 
	"VERSION" VARCHAR2(32) CONSTRAINT "RHN_APPINST_INSTANCE_VERS_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_APPINST_INSTANCE_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_APPINST_INSTANCE_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_APPINST_INSTANCE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_APPINST_INSTANCE_LV_UQ" UNIQUE ("LABEL", "VERSION")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
