-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNACTIONPACKAGEREMOVALFAILURE" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_APR_FAILURE_SID_NN" NOT NULL ENABLE, 
	"ACTION_ID" NUMBER CONSTRAINT "RHN_APR_FAILURE_AID_NN" NOT NULL ENABLE, 
	"NAME_ID" NUMBER CONSTRAINT "RHN_APR_FAILURE_NID_NN" NOT NULL ENABLE, 
	"EVR_ID" NUMBER CONSTRAINT "RHN_APR_FAILURE_EID_NN" NOT NULL ENABLE, 
	"CAPABILITY_ID" NUMBER CONSTRAINT "RHN_APR_FAILURE_CAPID_NN" NOT NULL ENABLE, 
	"FLAGS" NUMBER CONSTRAINT "RHN_APR_FAILURE_FLAGS_NN" NOT NULL ENABLE, 
	"SUGGESTED" NUMBER, 
	"SENSE" NUMBER CONSTRAINT "RHN_APR_FAILURE_SENSE_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_APR_FAILURE_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_APR_FAILURE_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RHNSAT"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_APR_FAILURE_NID_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGENAME" ("ID") ENABLE, 
	 CONSTRAINT "RHN_APR_FAILURE_EID_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGEEVR" ("ID") ENABLE, 
	 CONSTRAINT "RHN_APR_FAILURE_CAPID_FK" FOREIGN KEY ("CAPABILITY_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGECAPABILITY" ("ID") ENABLE, 
	 CONSTRAINT "RHN_APR_FAILURE_SUGGESTED_FK" FOREIGN KEY ("SUGGESTED")
	  REFERENCES "RHNSAT"."RHNPACKAGENAME" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
