-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNAPPINSTALLSESSION" 
   (	"ID" NUMBER CONSTRAINT "RHN_APPINST_SESSION_ID_NN" NOT NULL ENABLE, 
	"INSTANCE_ID" NUMBER CONSTRAINT "RHN_APPINST_SESSION_IID_NN" NOT NULL ENABLE, 
	"MD5SUM" VARCHAR2(64), 
	"PROCESS_NAME" VARCHAR2(32), 
	"STEP_NUMBER" NUMBER, 
	"USER_ID" NUMBER CONSTRAINT "RHN_APPINST_SESSION_UID_NN" NOT NULL ENABLE, 
	"SERVER_ID" NUMBER CONSTRAINT "RHN_APPINST_SESSION_SID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_APPINST_SESSION_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_APPINST_SESSION_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_APPINST_SESSIOND_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_APPINST_SESSION_IID_FK" FOREIGN KEY ("INSTANCE_ID")
	  REFERENCES "RHNSAT"."RHNAPPINSTALLINSTANCE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_APPINST_SESSION_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ENABLE, 
	 CONSTRAINT "RHN_APPINST_SESSION_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
