-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNACTIONCONFIGDATEFILE" 
   (	"ACTION_ID" NUMBER CONSTRAINT "RHN_ACTIONCD_FILE_AID_NN" NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(512) CONSTRAINT "RHN_ACTIONCD_FILE_FN_NN" NOT NULL ENABLE, 
	"FILE_TYPE" CHAR(1) CONSTRAINT "RHN_ACTIONCD_FILE_FT_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTIONCD_FILE_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTIONCD_FILE_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACTIONCD_FILE_FT_CK" CHECK (file_type in ('W','B')) ENABLE, 
	 CONSTRAINT "RHN_ACTIONCD_FILE_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RHNSAT"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
