-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNACTIONKICKSTARTFILELIST" 
   (	"ACTION_KS_ID" NUMBER CONSTRAINT "RHN_ACTIONKSFL_AKSID_NN" NOT NULL ENABLE, 
	"FILE_LIST_ID" NUMBER CONSTRAINT "RHN_ACTIONKSFL_FLID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTIONKSFL_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTIONKSFL_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACTIONKSFL_ASKID_FK" FOREIGN KEY ("ACTION_KS_ID")
	  REFERENCES "RHNSAT"."RHNACTIONKICKSTART" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ACTIONKSFL_FLID_FK" FOREIGN KEY ("FILE_LIST_ID")
	  REFERENCES "RHNSAT"."RHNFILELIST" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
