-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNACTIVATIONKEY" 
   (	"TOKEN" VARCHAR2(48) CONSTRAINT "RHN_ACT_KEY_TOKEN_NN" NOT NULL ENABLE, 
	"REG_TOKEN_ID" NUMBER CONSTRAINT "RHN_ACT_KEY_REG_TID_NN" NOT NULL ENABLE, 
	"KS_SESSION_ID" NUMBER, 
	"CREATED" DATE DEFAULT sysdate CONSTRAINT "RHN_ACT_KEY_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT sysdate CONSTRAINT "RHN_ACT_KEY_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACT_KEY_TOKEN_UQ" UNIQUE ("TOKEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_ACT_KEY_REG_TID_FK" FOREIGN KEY ("REG_TOKEN_ID")
	  REFERENCES "RHNSAT"."RHNREGTOKEN" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ACT_KEY_KS_SID_FK" FOREIGN KEY ("KS_SESSION_ID")
	  REFERENCES "RHNSAT"."RHNKICKSTARTSESSION" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
