-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNACTIONTRANSACTIONS" 
   (	"ACTION_ID" NUMBER CONSTRAINT "RHN_AT_AID_NN" NOT NULL ENABLE, 
	"FROM_TRANS_ID" NUMBER CONSTRAINT "RHN_AT_FTID_NN" NOT NULL ENABLE, 
	"TO_TRANS_ID" NUMBER CONSTRAINT "RHN_AT_TTID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_AT_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RHNSAT"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_AT_FTID_FK" FOREIGN KEY ("FROM_TRANS_ID")
	  REFERENCES "RHNSAT"."RHNTRANSACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_AT_TTID_FK" FOREIGN KEY ("TO_TRANS_ID")
	  REFERENCES "RHNSAT"."RHNTRANSACTION" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
