-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNACTIONKICKSTARTGUEST" 
   (	"ID" NUMBER CONSTRAINT "RHN_ACTIONKS_XENGUEST_ID_NN" NOT NULL ENABLE, 
	"ACTION_ID" NUMBER CONSTRAINT "RHN_ACTIONKS_XENGUEST_AID_NN" NOT NULL ENABLE, 
	"APPEND_STRING" VARCHAR2(1024), 
	"KS_SESSION_ID" NUMBER, 
	"KSTREE_ID" NUMBER CONSTRAINT "RHN_ACTIONKS_XENGUEST_KSTID_NN" NOT NULL ENABLE, 
	"GUEST_NAME" VARCHAR2(256), 
	"MEM_KB" NUMBER, 
	"VCPUS" NUMBER, 
	"DISK_GB" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTIONKS_XENGUEST_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTIONKS_XENGUEST_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACTIONKS_XENGUEST_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_ACTIONKS_XENGUEST_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RHNSAT"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ACTIONKS_XENGUEST_KSID_FK" FOREIGN KEY ("KS_SESSION_ID")
	  REFERENCES "RHNSAT"."RHNKICKSTARTSESSION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ACTIONKS_XENGUEST_KSTID_FK" FOREIGN KEY ("KSTREE_ID")
	  REFERENCES "RHNSAT"."RHNKICKSTARTABLETREE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
