-- created by Oraschemadoc Fri Jun 13 14:05:49 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNACTIONCONFIGREVISIONRESULT" 
   (	"ACTION_CONFIG_REVISION_ID" NUMBER CONSTRAINT "RHN_ACTIONCFR_ACRID_NN" NOT NULL ENABLE, 
	"RESULT" BLOB, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTIONCFR_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ACTIONCFR_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACTIONCFR_ACRID_FK" FOREIGN KEY ("ACTION_CONFIG_REVISION_ID")
	  REFERENCES "RHNSAT"."RHNACTIONCONFIGREVISION" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 LOB ("RESULT") STORE AS (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 
/
