-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNBLACKLISTOBSOLETES" 
   (	"NAME_ID" NUMBER CONSTRAINT "RHN_BL_OBS_NID_NN" NOT NULL ENABLE, 
	"EVR_ID" NUMBER CONSTRAINT "RHN_BL_OBS_EID_NN" NOT NULL ENABLE, 
	"PACKAGE_ARCH_ID" NUMBER CONSTRAINT "RHN_BL_OBS_PAID_NN" NOT NULL ENABLE, 
	"IGNORE_NAME_ID" NUMBER CONSTRAINT "RHN_BL_OBS_INID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_BL_OBS_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_BL_OBS_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_BL_OBS_NEPI_UQ" UNIQUE ("NAME_ID", "EVR_ID", "PACKAGE_ARCH_ID", "IGNORE_NAME_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_BL_OBS_NID_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGENAME" ("ID") ENABLE, 
	 CONSTRAINT "RHN_BL_OBS_EID_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGEEVR" ("ID") ENABLE, 
	 CONSTRAINT "RHN_BL_OBS_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGEARCH" ("ID") ENABLE, 
	 CONSTRAINT "RHN_BL_OBS_INID_FK" FOREIGN KEY ("IGNORE_NAME_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGENAME" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
