-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNBEEHIVEPATHMAP" 
   (	"PATH" VARCHAR2(128) CONSTRAINT "RHN_BEEHIVE_PATH_MAP_P_NN" NOT NULL ENABLE, 
	"BEEHIVE_PATH" VARCHAR2(128) CONSTRAINT "RHN_BEEHIVE_PATH_MAP_BP_NN" NOT NULL ENABLE, 
	"FTP_PATH" VARCHAR2(128) CONSTRAINT "RHN_BEEHIVE_PATH_MAP_FP_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT SYSDATE, 
	"MODIFIED" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "RHN_BEEHIVE_PATH_MAP_P_PK" PRIMARY KEY ("PATH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
