-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCONFIGINFO" 
   (	"ID" NUMBER CONSTRAINT "RHN_CONFINFO_ID_NN" NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(32) CONSTRAINT "RHN_CONFINFO_USERNAME_NN" NOT NULL ENABLE, 
	"GROUPNAME" VARCHAR2(32) CONSTRAINT "RHN_CONFINFO_GROUPNAME_NN" NOT NULL ENABLE, 
	"FILEMODE" NUMBER CONSTRAINT "RHN_CONFINFO_FILEMODE_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CONFINFO_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CONFINFO_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CONFINFO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
