-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCHANNELFAMILYLICENSECONSENT" 
   (	"CHANNEL_FAMILY_ID" NUMBER CONSTRAINT "RHN_CFL_CONSENT_CFID_NN" NOT NULL ENABLE, 
	"USER_ID" NUMBER CONSTRAINT "RHN_CFL_CONSENT_UID_NN" NOT NULL ENABLE, 
	"SERVER_ID" NUMBER CONSTRAINT "RHN_CFL_CONSENT_SID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CFL_CONSENT_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CFL_CONSENT_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CFL_CONSENT_CFID_FK" FOREIGN KEY ("CHANNEL_FAMILY_ID")
	  REFERENCES "RHNSAT"."RHNCHANNELFAMILY" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_CFL_CONSENT_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_CFL_CONSENT_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
