-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCONFIGREVISION" 
   (	"ID" NUMBER CONSTRAINT "RHN_CONFREVISION_ID_NN" NOT NULL ENABLE, 
	"REVISION" NUMBER CONSTRAINT "RHN_CONFREVISION_REV_NN" NOT NULL ENABLE, 
	"CONFIG_FILE_ID" NUMBER CONSTRAINT "RHN_CONFREVISION_CFID_NN" NOT NULL ENABLE, 
	"CONFIG_CONTENT_ID" NUMBER CONSTRAINT "RHN_CONFREVISION_CCID_NN" NOT NULL ENABLE, 
	"CONFIG_INFO_ID" NUMBER CONSTRAINT "RHN_CONFREVISION_CIID_NN" NOT NULL ENABLE, 
	"DELIM_START" VARCHAR2(16) CONSTRAINT "RHN_CONFREVISION_DSTART_NN" NOT NULL ENABLE, 
	"DELIM_END" VARCHAR2(16) CONSTRAINT "RHN_CONFREVISION_DEND_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CONFREVISION_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CONFREVISION_MOD_NN" NOT NULL ENABLE, 
	"CONFIG_FILE_TYPE_ID" NUMBER DEFAULT 1 CONSTRAINT "RHN_CONF_REV_CFTI_NN" NOT NULL ENABLE, 
	"CHANGED_BY_ID" NUMBER DEFAULT null, 
	 CONSTRAINT "RHN_CONFREVISION_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CONFREVISION_CFID_FK" FOREIGN KEY ("CONFIG_FILE_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGFILE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CONFREVISION_CCID_FK" FOREIGN KEY ("CONFIG_CONTENT_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGCONTENT" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CONFREVISION_CIID_FK" FOREIGN KEY ("CONFIG_INFO_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGINFO" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CONF_REV_CFTI_FK" FOREIGN KEY ("CONFIG_FILE_TYPE_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGFILETYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CONFREVISION_CID_FK" FOREIGN KEY ("CHANGED_BY_ID")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
