-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCPU" 
   (	"ID" NUMBER CONSTRAINT "RHN_CPU_ID_NN" NOT NULL ENABLE, 
	"SERVER_ID" NUMBER CONSTRAINT "RHN_CPU_SERVER_NN" NOT NULL ENABLE, 
	"CPU_ARCH_ID" NUMBER CONSTRAINT "RHN_CPU_CAID_NN" NOT NULL ENABLE, 
	"BOGOMIPS" VARCHAR2(16), 
	"CACHE" VARCHAR2(16), 
	"FAMILY" VARCHAR2(32), 
	"MHZ" VARCHAR2(16), 
	"STEPPING" VARCHAR2(16), 
	"FLAGS" VARCHAR2(2048), 
	"MODEL" VARCHAR2(64), 
	"VERSION" VARCHAR2(32), 
	"VENDOR" VARCHAR2(32), 
	"NRCPU" NUMBER DEFAULT 1, 
	"ACPIVERSION" VARCHAR2(64), 
	"APIC" VARCHAR2(32), 
	"APMVERSION" VARCHAR2(32), 
	"CHIPSET" VARCHAR2(64), 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CPU_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CPU_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CPU_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CPU_SERVER_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CPU_CAID_FK" FOREIGN KEY ("CPU_ARCH_ID")
	  REFERENCES "RHNSAT"."RHNCPUARCH" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
