-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCONFIGCHANNEL" 
   (	"ID" NUMBER CONSTRAINT "RHN_CONFCHAN_ID_NN" NOT NULL ENABLE, 
	"ORG_ID" NUMBER CONSTRAINT "RHN_CONFCHAN_OID_NN" NOT NULL ENABLE, 
	"CONFCHAN_TYPE_ID" NUMBER CONSTRAINT "RHN_CONFCHAN_CTID_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(128) CONSTRAINT "RHN_CONFCHAN_NAME_NN" NOT NULL ENABLE, 
	"LABEL" VARCHAR2(64) CONSTRAINT "RHN_CONFCHAN_LABEL_NN" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1024) CONSTRAINT "RHN_CONFCHAN_DESC_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CONFCHAN_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CONFCHAN_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CONFCHAN_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CONFCHAN_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CONFCHAN_CTID_FK" FOREIGN KEY ("CONFCHAN_TYPE_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGCHANNELTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
