-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCHANNELPARENT" 
   (	"CHANNEL" NUMBER CONSTRAINT "RHN_CP_CH_NN" NOT NULL ENABLE, 
	"PARENT_CHANNEL" NUMBER CONSTRAINT "RHN_CP_PARENT_CH_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CHP_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CHP_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CP_CH_FK" FOREIGN KEY ("CHANNEL")
	  REFERENCES "RHNSAT"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_CP_PARENT_CH_FK" FOREIGN KEY ("PARENT_CHANNEL")
	  REFERENCES "RHNSAT"."RHNCHANNEL" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
