-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCUSTOMDATAKEY" 
   (	"ID" NUMBER CONSTRAINT "RHN_CDATAKEY_ID_NN" NOT NULL ENABLE, 
	"ORG_ID" NUMBER CONSTRAINT "RHN_CDATAKEY_OID_NN" NOT NULL ENABLE, 
	"LABEL" VARCHAR2(64) CONSTRAINT "RHN_CDATAKEY_LABEL_NN" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000) CONSTRAINT "RHN_CDATAKEY_DESC_NN" NOT NULL ENABLE, 
	"CREATED_BY" NUMBER, 
	"LAST_MODIFIED_BY" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CDATAKEY_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CDATAKEY_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CDATAKEY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CDATAKEY_OID_LABEL_UQ" UNIQUE ("ORG_ID", "LABEL")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CDATAKEY_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_CDATAKEY_CB_FK" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_CDATAKEY_LMB_FK" FOREIGN KEY ("LAST_MODIFIED_BY")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
