-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCHANNELPACKAGEARCHCOMPAT" 
   (	"CHANNEL_ARCH_ID" NUMBER CONSTRAINT "RHN_CP_AC_CAID_NN" NOT NULL ENABLE, 
	"PACKAGE_ARCH_ID" NUMBER CONSTRAINT "RHN_CP_AC_PAID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CP_AC_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CP_AC_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CP_AC_CAID_PAID_UQ" UNIQUE ("CHANNEL_ARCH_ID", "PACKAGE_ARCH_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CP_AC_CAID_FK" FOREIGN KEY ("CHANNEL_ARCH_ID")
	  REFERENCES "RHNSAT"."RHNCHANNELARCH" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CP_AC_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGEARCH" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
