-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCONFIGFILE" 
   (	"ID" NUMBER CONSTRAINT "RHN_CONFFILE_ID_NN" NOT NULL ENABLE, 
	"CONFIG_CHANNEL_ID" NUMBER CONSTRAINT "RHN_CONFFILE_CCID_NN" NOT NULL ENABLE, 
	"CONFIG_FILE_NAME_ID" NUMBER CONSTRAINT "RHN_CONFFILE_CFNID_NN" NOT NULL ENABLE, 
	"LATEST_CONFIG_REVISION_ID" NUMBER, 
	"STATE_ID" NUMBER CONSTRAINT "RHN_CONFFILE_SID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CONFFILE_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CONFFILE_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CONFFILE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CONFFILE_CCID_CFNID_UQ" UNIQUE ("CONFIG_CHANNEL_ID", "CONFIG_FILE_NAME_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CONFFILE_CCID_FK" FOREIGN KEY ("CONFIG_CHANNEL_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGCHANNEL" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CONFFILE_CFNID_FK" FOREIGN KEY ("CONFIG_FILE_NAME_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGFILENAME" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CONFFILE_SID_FK" FOREIGN KEY ("STATE_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGFILESTATE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CONFFILE_LCRID_FK" FOREIGN KEY ("LATEST_CONFIG_REVISION_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGREVISION" ("ID") ON DELETE SET NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
