-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCHANNEL" 
   (	"ID" NUMBER CONSTRAINT "RHN_CHANNEL_ID_NN" NOT NULL ENABLE, 
	"PARENT_CHANNEL" NUMBER, 
	"ORG_ID" NUMBER, 
	"CHANNEL_ARCH_ID" NUMBER CONSTRAINT "RHN_CHANNEL_CAID_NN" NOT NULL ENABLE, 
	"LABEL" VARCHAR2(128) CONSTRAINT "RHN_CHANNEL_LABEL_NN" NOT NULL ENABLE, 
	"BASEDIR" VARCHAR2(256) CONSTRAINT "RHN_CHANNEL_BASEDIR_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(64) CONSTRAINT "RHN_CHANNEL_NAME_NN" NOT NULL ENABLE, 
	"SUMMARY" VARCHAR2(500) CONSTRAINT "RHN_CHANNEL_SUMMARY_NN" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"PRODUCT_NAME_ID" NUMBER, 
	"GPG_KEY_URL" VARCHAR2(256), 
	"GPG_KEY_ID" VARCHAR2(14), 
	"GPG_KEY_FP" VARCHAR2(50), 
	"END_OF_LIFE" DATE, 
	"RECEIVING_UPDATES" CHAR(1) DEFAULT 'Y' CONSTRAINT "RHN_CHANNEL_RU_NN" NOT NULL ENABLE, 
	"LAST_MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CHANNEL_LM_NN" NOT NULL ENABLE, 
	"CHANNEL_PRODUCT_ID" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CHANNEL_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CHANNEL_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CHANNEL_RU_CK" CHECK (receiving_updates in ('Y', 'N')) ENABLE, 
	 CONSTRAINT "RHN_CHANNEL_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CHANNEL_PARENT_CH_FK" FOREIGN KEY ("PARENT_CHANNEL")
	  REFERENCES "RHNSAT"."RHNCHANNEL" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CHANNEL_ORG_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CHANNEL_CAID_FK" FOREIGN KEY ("CHANNEL_ARCH_ID")
	  REFERENCES "RHNSAT"."RHNCHANNELARCH" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CHANNEL_PRODUCT_NAME_CH_FK" FOREIGN KEY ("PRODUCT_NAME_ID")
	  REFERENCES "RHNSAT"."RHNPRODUCTNAME" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CHANNEL_CPID_FK" FOREIGN KEY ("CHANNEL_PRODUCT_ID")
	  REFERENCES "RHNSAT"."RHNCHANNELPRODUCT" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
