-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCHANNELFAMILYVIRTSUBLEVEL" 
   (	"CHANNEL_FAMILY_ID" NUMBER CONSTRAINT "RHN_CFVSL_CFID_NN" NOT NULL ENABLE, 
	"VIRT_SUB_LEVEL_ID" NUMBER CONSTRAINT "RHN_CFVSL_VSLID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT sysdate CONSTRAINT "RHN_CFVSL_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT sysdate CONSTRAINT "RHN_CFVSL_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CFVSL_CFID_FK" FOREIGN KEY ("CHANNEL_FAMILY_ID")
	  REFERENCES "RHNSAT"."RHNCHANNELFAMILY" ("ID") ENABLE, 
	 CONSTRAINT "RHN_CFVSL_VSLID_FK" FOREIGN KEY ("VIRT_SUB_LEVEL_ID")
	  REFERENCES "RHNSAT"."RHNVIRTSUBLEVEL" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
