-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCONFIGCONTENT" 
   (	"ID" NUMBER CONSTRAINT "RHN_CONFCONTENT_ID_NN" NOT NULL ENABLE, 
	"CONTENTS" BLOB, 
	"FILE_SIZE" NUMBER, 
	"MD5SUM" VARCHAR2(64) CONSTRAINT "RHN_CONFCONTENT_MD5_NN" NOT NULL ENABLE, 
	"IS_BINARY" CHAR(1) DEFAULT ('N') CONSTRAINT "RHN_CONFCONTENT_ISBIN_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CONFCONTENT_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CONFCONTENT_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CONFCONTENT_ISBIN_CK" CHECK (is_binary in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_CONFCONTENT_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 LOB ("CONTENTS") STORE AS (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 
/
