-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCRYPTOKEYKICKSTART" 
   (	"CRYPTO_KEY_ID" NUMBER CONSTRAINT "RHN_CKEY_KS_CKID_NN" NOT NULL ENABLE, 
	"KSDATA_ID" NUMBER CONSTRAINT "RHN_CKEY_KS_KSD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CKEY_KS_CKID_FK" FOREIGN KEY ("CRYPTO_KEY_ID")
	  REFERENCES "RHNSAT"."RHNCRYPTOKEY" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_CKEY_KS_KSD_FK" FOREIGN KEY ("KSDATA_ID")
	  REFERENCES "RHNSAT"."RHNKSDATA" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
