-- created by Oraschemadoc Fri Jun 13 14:05:50 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNCHANNELFAMILY" 
   (	"ID" NUMBER CONSTRAINT "RHN_CHANNEL_FAMILY_ID_NN" NOT NULL ENABLE, 
	"ORG_ID" NUMBER, 
	"NAME" VARCHAR2(128) CONSTRAINT "RHN_CHANNEL_FAMILY_NAME_NN" NOT NULL ENABLE, 
	"LABEL" VARCHAR2(128) CONSTRAINT "RHN_CHANNEL_FAMILY_LABEL_NN" NOT NULL ENABLE, 
	"PRODUCT_URL" VARCHAR2(128) DEFAULT 'http://www.redhat.com/products/' CONSTRAINT "RHN_CHANNEL_FAMILY_URL_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CHANNEL_FAMILY_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_CHANNEL_FAMILY_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CHANNEL_FAMILY_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_CHANNEL_FAMILY_ORG_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
