-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNDISTCHANNELMAP" 
   (	"OS" VARCHAR2(64) CONSTRAINT "RHN_DCM_OS_NN" NOT NULL ENABLE, 
	"RELEASE" VARCHAR2(64) CONSTRAINT "RHN_DCM_RELEASE_NN" NOT NULL ENABLE, 
	"CHANNEL_ARCH_ID" NUMBER CONSTRAINT "RHN_DCM_CAID_NN" NOT NULL ENABLE, 
	"CHANNEL_ID" NUMBER CONSTRAINT "RHN_DCM_CID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_DCM_OS_RELEASE_CAID_UQ" UNIQUE ("OS", "RELEASE", "CHANNEL_ARCH_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_DCM_CAID_FK" FOREIGN KEY ("CHANNEL_ARCH_ID")
	  REFERENCES "RHNSAT"."RHNCHANNELARCH" ("ID") ENABLE, 
	 CONSTRAINT "RHN_DCM_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "RHNSAT"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
