-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNDOWNLOADS" 
   (	"ID" NUMBER CONSTRAINT "RHN_DL_ID_NN" NOT NULL ENABLE, 
	"CHANNEL_FAMILY_ID" NUMBER CONSTRAINT "RHN_DL_CFID_NN" NOT NULL ENABLE, 
	"FILE_ID" NUMBER CONSTRAINT "RHN_DL_FID_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(128) CONSTRAINT "RHN_DL_NAME_NN" NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(128) CONSTRAINT "RHN_DL_CAT_NN" NOT NULL ENABLE, 
	"ORDERING" NUMBER CONSTRAINT "RHN_DL_ORD_NN" NOT NULL ENABLE, 
	"DOWNLOAD_TYPE" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_DL_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_DL_MODIFIED_NN" NOT NULL ENABLE, 
	"RELEASE_NOTES_URL" VARCHAR2(512), 
	 CONSTRAINT "RHN_DL_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_DL_CFID_FK" FOREIGN KEY ("CHANNEL_FAMILY_ID")
	  REFERENCES "RHNSAT"."RHNCHANNELFAMILY" ("ID") ENABLE, 
	 CONSTRAINT "RHN_DL_FID_FK" FOREIGN KEY ("FILE_ID")
	  REFERENCES "RHNSAT"."RHNFILE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_DL_DLTYPE_FK" FOREIGN KEY ("DOWNLOAD_TYPE")
	  REFERENCES "RHNSAT"."RHNDOWNLOADTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
