-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNENTITLEMENTLOG" 
   (	"RUN_TIME" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ENTITLEMENT_LOG_RT_NN" NOT NULL ENABLE, 
	"BDATE" DATE CONSTRAINT "RHN_ENTITLEMENT_LOG_BDATE_NN" NOT NULL ENABLE, 
	"EDATE" DATE CONSTRAINT "RHN_ENTITLEMENT_LOG_EDATE_NN" NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
