-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNEMAILADDRESSLOG" 
   (	"USER_ID" NUMBER CONSTRAINT "RHN_EADDRESSLOG_UID_NN" NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(128) CONSTRAINT "RHN_EADDRESSLOG_A_NN" NOT NULL ENABLE, 
	"REASON" VARCHAR2(4000), 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_EADDRESSLOG_CREATED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_EADDRESSLOG_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
