-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNERRATABUGLISTTMP" 
   (	"ERRATA_ID" NUMBER CONSTRAINT "RHN_ERRATA_BUGLISTTMP_EID_NN" NOT NULL ENABLE, 
	"BUG_ID" NUMBER CONSTRAINT "RHN_ERRATA_BUGLISTTMP_BID_NN" NOT NULL ENABLE, 
	"SUMMARY" VARCHAR2(4000), 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ERRATA_BUGLISTTMP_C_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ERRATA_BUGLISTTMP_M_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ERRATA_BUGLISTTMP_EID_FK" FOREIGN KEY ("ERRATA_ID")
	  REFERENCES "RHNSAT"."RHNERRATATMP" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
