-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNEMAILADDRESS" 
   (	"ID" NUMBER CONSTRAINT "RHN_EADDRESS_ID_NN" NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(128) CONSTRAINT "RHN_EADDRESS_A_NN" NOT NULL ENABLE, 
	"USER_ID" NUMBER CONSTRAINT "RHN_EADDRESS_UID_NN" NOT NULL ENABLE, 
	"STATE_ID" NUMBER CONSTRAINT "RHN_EADDRESS_SID_NN" NOT NULL ENABLE, 
	"NEXT_ACTION" DATE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_EADDRESS_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_EADDRESS_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_EADDRESS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_EADDRESS_UID_SID_UQ" UNIQUE ("USER_ID", "STATE_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_EADDRESS_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_EADDRESS_SID_FK" FOREIGN KEY ("STATE_ID")
	  REFERENCES "RHNSAT"."RHNEMAILADDRESSSTATE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
