-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNERRATAFILECHANNEL" 
   (	"CHANNEL_ID" NUMBER CONSTRAINT "RHN_EFILEC_CID_NN" NOT NULL ENABLE, 
	"ERRATA_FILE_ID" NUMBER CONSTRAINT "RHN_EFILEC_EID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_EFILEC_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_EFILEC_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_EFILEC_EFID_CID_UQ" UNIQUE ("ERRATA_FILE_ID", "CHANNEL_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_EFILEC_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "RHNSAT"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_EFILEC_EID_FK" FOREIGN KEY ("ERRATA_FILE_ID")
	  REFERENCES "RHNSAT"."RHNERRATAFILE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
