-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNERRATAFILETMP" 
   (	"ID" NUMBER CONSTRAINT "RHN_ERRATAFILETMP_ID_NN" NOT NULL ENABLE, 
	"ERRATA_ID" NUMBER CONSTRAINT "RHN_ERRATAFILETMP_ERRATA_NN" NOT NULL ENABLE, 
	"TYPE" NUMBER CONSTRAINT "RHN_ERRATAFILETMP_TYPE_NN" NOT NULL ENABLE, 
	"MD5SUM" VARCHAR2(64) CONSTRAINT "RHN_ERRATAFILETMP_MD5_NN" NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(128) CONSTRAINT "RHN_ERRATAFILETMP_NAME_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ERRATAFILETMP_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ERRATAFILETMP_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ERRATAFILETMP_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_ERRATAFILETMP_EID_FILE_UQ" UNIQUE ("ERRATA_ID", "FILENAME")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_ERRATAFILETMP_ERRATA_FK" FOREIGN KEY ("ERRATA_ID")
	  REFERENCES "RHNSAT"."RHNERRATATMP" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ERRATAFILETMP_TYPE_FK" FOREIGN KEY ("TYPE")
	  REFERENCES "RHNSAT"."RHNERRATAFILETYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
