-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNERRATACVE" 
   (	"ERRATA_ID" NUMBER CONSTRAINT "RHN_ERR_CVE_EID_NN" NOT NULL ENABLE, 
	"CVE_ID" NUMBER CONSTRAINT "RHN_ERR_CVE_CID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ERR_CVE_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ERR_CVE_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ERR_CVE_EID_FK" FOREIGN KEY ("ERRATA_ID")
	  REFERENCES "RHNSAT"."RHNERRATA" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ERR_CVE_CID_FK" FOREIGN KEY ("CVE_ID")
	  REFERENCES "RHNSAT"."RHNCVE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
