-- created by Oraschemadoc Fri Jun 13 14:05:51 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNERRATAFILEPACKAGESOURCE" 
   (	"PACKAGE_ID" NUMBER CONSTRAINT "RHN_EFILEPS_PID_NN" NOT NULL ENABLE, 
	"ERRATA_FILE_ID" NUMBER CONSTRAINT "RHN_EFILEPS_FILEID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_EFILEPS_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_EFILEPS_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_EFILEPS_EFID_UQ" UNIQUE ("ERRATA_FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_EFILEPS_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGESOURCE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_EFILEPS_FILEID_FK" FOREIGN KEY ("ERRATA_FILE_ID")
	  REFERENCES "RHNSAT"."RHNERRATAFILE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
