-- created by Oraschemadoc Fri Jun 13 14:05:52 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNFAQ" 
   (	"ID" NUMBER CONSTRAINT "RHN_FAQ_ID_NN" NOT NULL ENABLE, 
	"CLASS_ID" NUMBER, 
	"SUBJECT" VARCHAR2(200), 
	"DETAILS" VARCHAR2(4000), 
	"PRIVATE" NUMBER DEFAULT (0) CONSTRAINT "RHN_FAQ_PRIVATE_NN" NOT NULL ENABLE, 
	"USAGE_COUNT" NUMBER DEFAULT (0) CONSTRAINT "RHN_FAQ_USAGE_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_FAQ_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_FAQ_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_FAQ_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_FAQ_CLASS_FK" FOREIGN KEY ("CLASS_ID")
	  REFERENCES "RHNSAT"."RHNFAQCLASS" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
