-- created by Oraschemadoc Fri Jun 13 14:05:52 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNGRAILCOMPONENTCHOICES" 
   (	"USER_ID" NUMBER CONSTRAINT "RHN_GRAIL_COMP_CH_NN" NOT NULL ENABLE, 
	"ORDERING" NUMBER CONSTRAINT "RHN_GRAIL_COMP_CH_ORDER_NN" NOT NULL ENABLE, 
	"COMPONENT_PKG" VARCHAR2(64) CONSTRAINT "RHN_GRAIL_COMP_CH_PKG_NN" NOT NULL ENABLE, 
	"COMPONENT_MODE" VARCHAR2(64) CONSTRAINT "RHN_GRAIL_COMP_CH_MODE_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_GRAIL_COMP_CH_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
