-- created by Oraschemadoc Fri Jun 13 14:05:52 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNKICKSTARTDEFAULTS" 
   (	"KICKSTART_ID" NUMBER CONSTRAINT "RHN_KSD_KSID_NN" NOT NULL ENABLE, 
	"KSTREE_ID" NUMBER CONSTRAINT "RHN_KSD_KSTID_NN" NOT NULL ENABLE, 
	"SERVER_PROFILE_ID" NUMBER, 
	"CFG_MANAGEMENT_FLAG" CHAR(1) DEFAULT ('Y') CONSTRAINT "RHN_KSD_CMF_NN" NOT NULL ENABLE, 
	"REMOTE_COMMAND_FLAG" CHAR(1) DEFAULT ('N') CONSTRAINT "RHN_KSD_RMF_NN" NOT NULL ENABLE, 
	"VIRTUALIZATION_TYPE" NUMBER CONSTRAINT "RHN_KSD_KVT_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KSD_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KSD_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_KSD_CMF_CK" CHECK (cfg_management_flag in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_KSD_RMF_CK" CHECK (remote_command_flag in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_KSD_KSID_UQ" UNIQUE ("KICKSTART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_KSD_KSID_FK" FOREIGN KEY ("KICKSTART_ID")
	  REFERENCES "RHNSAT"."RHNKSDATA" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_KSD_KSTID_FK" FOREIGN KEY ("KSTREE_ID")
	  REFERENCES "RHNSAT"."RHNKICKSTARTABLETREE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_KSD_SPID_FK" FOREIGN KEY ("SERVER_PROFILE_ID")
	  REFERENCES "RHNSAT"."RHNSERVERPROFILE" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_KSD_KVT_FK" FOREIGN KEY ("VIRTUALIZATION_TYPE")
	  REFERENCES "RHNSAT"."RHNKICKSTARTVIRTUALIZATIONTYPE" ("ID") ON DELETE SET NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
