-- created by Oraschemadoc Fri Jun 13 14:05:52 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNKICKSTARTSESSION" 
   (	"ID" NUMBER CONSTRAINT "RHN_KS_SESSION_ID_NN" NOT NULL ENABLE, 
	"KICKSTART_ID" NUMBER, 
	"KICKSTART_MODE" VARCHAR2(32), 
	"KSTREE_ID" NUMBER, 
	"ORG_ID" NUMBER CONSTRAINT "RHN_KS_SESSION_OID_NN" NOT NULL ENABLE, 
	"SCHEDULER" NUMBER, 
	"OLD_SERVER_ID" NUMBER, 
	"NEW_SERVER_ID" NUMBER, 
	"HOST_SERVER_ID" NUMBER, 
	"ACTION_ID" NUMBER, 
	"STATE_ID" NUMBER CONSTRAINT "RHN_KS_SESSION_KSSSID_NN" NOT NULL ENABLE, 
	"SERVER_PROFILE_ID" NUMBER, 
	"LAST_ACTION" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KS_SESSION_LAST_ACTION_NN" NOT NULL ENABLE, 
	"PACKAGE_FETCH_COUNT" NUMBER DEFAULT 0 CONSTRAINT "RHN_KS_SESSION_PFC_NN" NOT NULL ENABLE, 
	"LAST_FILE_REQUEST" VARCHAR2(2048), 
	"SYSTEM_RHN_HOST" VARCHAR2(256), 
	"KICKSTART_FROM_HOST" VARCHAR2(256), 
	"DEPLOY_CONFIGS" CHAR(1) DEFAULT ('N') CONSTRAINT "RHN_KS_SESSION_DC_NN" NOT NULL ENABLE, 
	"VIRTUALIZATION_TYPE" NUMBER CONSTRAINT "RHN_KSS_KVT_NN" NOT NULL ENABLE, 
	"CLIENT_IP" VARCHAR2(15), 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KS_SESSION_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KS_SESSION_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_KS_SESSION_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_KS_SESSION_KSID_FK" FOREIGN KEY ("KICKSTART_ID")
	  REFERENCES "RHNSAT"."RHNKSDATA" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_KS_SESSION_KSTID_FK" FOREIGN KEY ("KSTREE_ID")
	  REFERENCES "RHNSAT"."RHNKICKSTARTABLETREE" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_KS_SESSION_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_KS_SESSION_SCHED_FK" FOREIGN KEY ("SCHEDULER")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_KS_SESSION_OSID_FK" FOREIGN KEY ("OLD_SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_KS_SESSION_NSID_FK" FOREIGN KEY ("NEW_SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_KS_SESSION_HSID_FK" FOREIGN KEY ("HOST_SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_KS_SESSION_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RHNSAT"."RHNACTION" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_KS_SESSION_KSSSID_FK" FOREIGN KEY ("STATE_ID")
	  REFERENCES "RHNSAT"."RHNKICKSTARTSESSIONSTATE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_KS_SESSION_SPID_FK" FOREIGN KEY ("SERVER_PROFILE_ID")
	  REFERENCES "RHNSAT"."RHNSERVERPROFILE" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_KSS_KVT_FK" FOREIGN KEY ("VIRTUALIZATION_TYPE")
	  REFERENCES "RHNSAT"."RHNKICKSTARTVIRTUALIZATIONTYPE" ("ID") ON DELETE SET NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
