-- created by Oraschemadoc Fri Jun 13 14:05:52 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNKICKSTARTSESSIONHISTORY" 
   (	"ID" NUMBER CONSTRAINT "RHN_KS_SESSIONHIST_ID_NN" NOT NULL ENABLE, 
	"KICKSTART_SESSION_ID" NUMBER CONSTRAINT "RHN_KS_SESSIONHIST_KSID_NN" NOT NULL ENABLE, 
	"ACTION_ID" NUMBER, 
	"STATE_ID" NUMBER CONSTRAINT "RHN_KS_SESSIONHIST_STAT_NN" NOT NULL ENABLE, 
	"TIME" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KS_SESSIONHIST_TIME_NN" NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(4000), 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KS_SESSIONHIST_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KS_SESSIONHIST_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_KS_SESSIONHIST_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_KS_SESSIONHIST_KSID_FK" FOREIGN KEY ("KICKSTART_SESSION_ID")
	  REFERENCES "RHNSAT"."RHNKICKSTARTSESSION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_KS_SESSIONHIST_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RHNSAT"."RHNACTION" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_KS_SESSIONHIST_STAT_FK" FOREIGN KEY ("STATE_ID")
	  REFERENCES "RHNSAT"."RHNKICKSTARTSESSIONSTATE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
