-- created by Oraschemadoc Fri Jun 13 14:05:52 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNKSDATA" 
   (	"ID" NUMBER CONSTRAINT "RHN_KS_ID_NN" NOT NULL ENABLE, 
	"ORG_ID" NUMBER CONSTRAINT "RHN_KS_OID_NN" NOT NULL ENABLE, 
	"IS_ORG_DEFAULT" CHAR(1) DEFAULT ('N') CONSTRAINT "RHN_KS_DEFAULT_NN" NOT NULL ENABLE, 
	"LABEL" VARCHAR2(64) CONSTRAINT "RHN_KS_LABEL_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(128) CONSTRAINT "RHN_KS_NAME_NN" NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(4000), 
	"ACTIVE" CHAR(1) DEFAULT ('Y') CONSTRAINT "RHN_KS_ACTIVE_NN" NOT NULL ENABLE, 
	"POSTLOG" CHAR(1) DEFAULT ('N') CONSTRAINT "RHN_KS_POST_LOG_NN" NOT NULL ENABLE, 
	"PRE" BLOB, 
	"POST" BLOB, 
	"NOCHROOT_POST" BLOB, 
	"STATIC_DEVICE" VARCHAR2(32), 
	"KERNEL_PARAMS" VARCHAR2(128), 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KS_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KS_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_KS_DEFAULT_CK" CHECK (is_org_default in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_KS_ACTIVE_CK" CHECK (active in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_KS_POST_LOG_CK" CHECK (postLog in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_KS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_KS_OID_LABEL_UQ" UNIQUE ("ORG_ID", "LABEL")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_KS_OID_NAME_UQ" UNIQUE ("ORG_ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_KS_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 LOB ("PRE") STORE AS (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("POST") STORE AS (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("NOCHROOT_POST") STORE AS (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 
/
