-- created by Oraschemadoc Fri Jun 13 14:05:52 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNKSTREEFILE" 
   (	"KSTREE_ID" NUMBER CONSTRAINT "RHN_KSTREEFILE_KID_NN" NOT NULL ENABLE, 
	"RELATIVE_FILENAME" VARCHAR2(256) CONSTRAINT "RHN_KSTREEFILE_RFN_NN" NOT NULL ENABLE, 
	"MD5SUM" VARCHAR2(64) CONSTRAINT "RHN_KSTREEFILE_MD5SUM_NN" NOT NULL ENABLE, 
	"FILE_SIZE" NUMBER CONSTRAINT "RHN_KSTREEFILE_FILE_SIZE_NN" NOT NULL ENABLE, 
	"LAST_MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KSTREEFILE_LASTMOD_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KSTREEFILE_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KSTREEFILE_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_KSTREEFILE_KID_FK" FOREIGN KEY ("KSTREE_ID")
	  REFERENCES "RHNSAT"."RHNKICKSTARTABLETREE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
