-- created by Oraschemadoc Fri Jun 13 14:05:52 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNKICKSTARTPRESERVEFILELIST" 
   (	"KICKSTART_ID" NUMBER CONSTRAINT "RHN_KSPRESERVEFL_KSID_NN" NOT NULL ENABLE, 
	"FILE_LIST_ID" NUMBER CONSTRAINT "RHN_KSPRESERVEFL_FLID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KSPRESERVEFL_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_KSPRESERVEFL_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_KSPRESERVEFL_KSID_FK" FOREIGN KEY ("KICKSTART_ID")
	  REFERENCES "RHNSAT"."RHNKSDATA" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_KSPRESERVEFL_FLID_FK" FOREIGN KEY ("FILE_LIST_ID")
	  REFERENCES "RHNSAT"."RHNFILELIST" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
