-- created by Oraschemadoc Fri Jun 13 14:05:52 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNMESSAGE" 
   (	"ID" NUMBER CONSTRAINT "RHN_M_ID_NN" NOT NULL ENABLE, 
	"MESSAGE_TYPE" NUMBER CONSTRAINT "RHN_M_MT_NN" NOT NULL ENABLE, 
	"PRIORITY" NUMBER DEFAULT 0 CONSTRAINT "RHN_M_PRIORITY_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_M_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_M_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_M_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_M_MT_FK" FOREIGN KEY ("MESSAGE_TYPE")
	  REFERENCES "RHNSAT"."RHNMESSAGETYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_M_PRIORITY_FK" FOREIGN KEY ("PRIORITY")
	  REFERENCES "RHNSAT"."RHNMESSAGEPRIORITY" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
