-- created by Oraschemadoc Fri Jun 13 14:05:53 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNMONITOR" 
   (	"BATCH_ID" NUMBER CONSTRAINT "RHN_MONITOR_BID_NN" NOT NULL ENABLE, 
	"SERVER_ID" NUMBER CONSTRAINT "RHN_MONITOR_SID_NN" NOT NULL ENABLE, 
	"PROBE_ID" NUMBER CONSTRAINT "RHN_MONITOR_PROBE_NN" NOT NULL ENABLE, 
	"COMPONENT" VARCHAR2(128), 
	"FIELD" VARCHAR2(128), 
	"TIMESTAMP" DATE CONSTRAINT "RHN_MONITOR_TS_NN" NOT NULL ENABLE, 
	"GRANULARITY" NUMBER CONSTRAINT "RHN_MONITOR_GRANULARITY_NN" NOT NULL ENABLE, 
	"VALUE" VARCHAR2(4000), 
	 CONSTRAINT "RHN_MONITOR_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_MONITOR_GRANULARITY_FK" FOREIGN KEY ("GRANULARITY")
	  REFERENCES "RHNSAT"."RHNMONITORGRANULARITY" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
