-- created by Oraschemadoc Fri Jun 13 14:05:53 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNORGENTITLEMENTS" 
   (	"ORG_ID" NUMBER CONSTRAINT "RHN_ORG_ENT_NN" NOT NULL ENABLE, 
	"ENTITLEMENT_ID" NUMBER CONSTRAINT "RHN_ORG_ENT_EID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ORG_ENT_CRE_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ORG_ENT_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ORG_ENT_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ORG_ENT_EID_FK" FOREIGN KEY ("ENTITLEMENT_ID")
	  REFERENCES "RHNSAT"."RHNORGENTITLEMENTTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
