-- created by Oraschemadoc Fri Jun 13 14:05:53 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNORGCHANNELSETTINGS" 
   (	"ORG_ID" NUMBER CONSTRAINT "RHN_ORGCSETTINGS_OID_NN" NOT NULL ENABLE, 
	"CHANNEL_ID" NUMBER CONSTRAINT "RHN_ORGCSETTINGS_CID_NN" NOT NULL ENABLE, 
	"SETTING_ID" NUMBER CONSTRAINT "RHN_ORGCSETTINGS_SID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ORGCSETTINGS_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ORGCSETTINGS_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ORGCSETTINGS_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ORGCSETTINGS_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "RHNSAT"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ORGCSETTINGS_SID_FK" FOREIGN KEY ("SETTING_ID")
	  REFERENCES "RHNSAT"."RHNORGCHANNELSETTINGSTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
