-- created by Oraschemadoc Fri Jun 13 14:05:53 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNORGINFO" 
   (	"ORG_ID" NUMBER CONSTRAINT "RHN_ORGINFO_OID_NN" NOT NULL ENABLE, 
	"DEFAULT_GROUP_TYPE" NUMBER DEFAULT (2) CONSTRAINT "RHN_ORGINFO_DGT_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ORGINFO_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ORGINFO_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ORGINFO_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_ORGINFO_DGT_FK" FOREIGN KEY ("DEFAULT_GROUP_TYPE")
	  REFERENCES "RHNSAT"."RHNSERVERGROUPTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
