-- created by Oraschemadoc Fri Jun 13 14:05:53 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNORGQUOTA" 
   (	"ORG_ID" NUMBER CONSTRAINT "RHN_ORGQUOTA_OID_NN" NOT NULL ENABLE, 
	"TOTAL" NUMBER DEFAULT (0) CONSTRAINT "RHN_ORGQUOTA_TOTAL_NN" NOT NULL ENABLE, 
	"BONUS" NUMBER DEFAULT (0) CONSTRAINT "RHN_ORGQUOTA_BONUS_NN" NOT NULL ENABLE, 
	"USED" NUMBER DEFAULT (0) CONSTRAINT "RHN_ORGQUOTA_USED_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ORGQUOTA_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ORGQUOTA_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ORGQUOTA_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
