-- created by Oraschemadoc Fri Jun 13 14:05:53 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNPRODUCT" 
   (	"ID" NUMBER CONSTRAINT "RHN_PRODUCT_ID_NN" NOT NULL ENABLE, 
	"LABEL" VARCHAR2(128) CONSTRAINT "RHN_PRODUCT_LABEL_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(128) CONSTRAINT "RHN_PRODUCT_NAME_NN" NOT NULL ENABLE, 
	"PRODUCT_LINE_ID" NUMBER CONSTRAINT "RHN_PRODUCT_CAT_NN" NOT NULL ENABLE, 
	"LAST_MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_PRODUCT_LM_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_PRODUCT_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_PRODUCT_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_PRODUCT_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_PRODUCT_LABEL_UQ" UNIQUE ("LABEL")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_PRODUCT_NAME_UQ" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_PRODUCT_CAT_FK" FOREIGN KEY ("PRODUCT_LINE_ID")
	  REFERENCES "RHNSAT"."RHNPRODUCTLINE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
