-- created by Oraschemadoc Fri Jun 13 14:05:53 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNPATHCHANNELMAP" 
   (	"PATH" VARCHAR2(128) CONSTRAINT "RHN_PATH_CHANNEL_MAP_P_NN" NOT NULL ENABLE, 
	"CHANNEL_ID" NUMBER CONSTRAINT "RHN_PATH_CHANNEL_MAP_CID_NN" NOT NULL ENABLE, 
	"IS_SOURCE" VARCHAR2(1), 
	"CREATED" DATE DEFAULT SYSDATE, 
	"MODIFIED" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "RHN_PATH_CHANNEL_MAP_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "RHNSAT"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
