-- created by Oraschemadoc Fri Jun 13 14:05:53 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNPACKAGESENSEMAP" 
   (	"SENSE" NUMBER CONSTRAINT "RHN_PKG_SENSEMAP_SENSE_NN" NOT NULL ENABLE, 
	"SENSE_ID" NUMBER CONSTRAINT "RHN_PKG_SENSEMAP_SID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_PKG_SENSEMAP_SID_FK" FOREIGN KEY ("SENSE_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGESENSE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
