-- created by Oraschemadoc Fri Jun 13 14:05:53 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNPACKAGECHANGELOG" 
   (	"PACKAGE_ID" NUMBER CONSTRAINT "RHN_PKG_CHANGELOG_PID_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(128) CONSTRAINT "RHN_PKG_CHANGELOG_NAME" NOT NULL ENABLE, 
	"TEXT" VARCHAR2(3000) CONSTRAINT "RHN_PKG_CHANGELOG_TEXT" NOT NULL ENABLE, 
	"TIME" DATE CONSTRAINT "RHN_PKG_CHANGELOG_TIME" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_PKG_CHANGELOG_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_PKG_CHANGELOG_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_PKG_CHANGELOG_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
