-- created by Oraschemadoc Fri Jun 13 14:05:53 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNPACKAGEFILE" 
   (	"PACKAGE_ID" NUMBER CONSTRAINT "RHN_PACKAGE_FILE_PID_NN" NOT NULL ENABLE, 
	"CAPABILITY_ID" NUMBER CONSTRAINT "RHN_PACKAGE_FILE_CID_NN" NOT NULL ENABLE, 
	"DEVICE" NUMBER CONSTRAINT "RHN_PACKAGE_FILE_DEVICES_NN" NOT NULL ENABLE, 
	"INODE" NUMBER CONSTRAINT "RHN_PACKAGE_FILE_INODE_NN" NOT NULL ENABLE, 
	"FILE_MODE" NUMBER CONSTRAINT "RHN_PACKAGE_FILE_MODE_NN" NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(32) CONSTRAINT "RHN_PACKAGE_FILE_USERNAME_NN" NOT NULL ENABLE, 
	"GROUPNAME" VARCHAR2(32) CONSTRAINT "RHN_PACKAGE_FILE_GROUPNAME_NN" NOT NULL ENABLE, 
	"RDEV" NUMBER CONSTRAINT "RHN_PACKAGE_FILE_DEV_NN" NOT NULL ENABLE, 
	"FILE_SIZE" NUMBER CONSTRAINT "RHN_PACKAGE_FILE_SIZE_NN" NOT NULL ENABLE, 
	"MTIME" DATE CONSTRAINT "RHN_PACKAGE_FILE_MTIME_NN" NOT NULL ENABLE, 
	"MD5" VARCHAR2(32), 
	"LINKTO" VARCHAR2(256), 
	"FLAGS" NUMBER CONSTRAINT "RHN_PACKAGE_FILE_FLAGS_NN" NOT NULL ENABLE, 
	"VERIFYFLAGS" NUMBER CONSTRAINT "RHN_PACKAGE_FILE_VERIFY_NN" NOT NULL ENABLE, 
	"LANG" VARCHAR2(32), 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_PACKAGE_FILE_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_PACKAGE_FILE_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_PACKAGE_FILE_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_PACKAGE_FILE_CID_FK" FOREIGN KEY ("CAPABILITY_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGECAPABILITY" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
