-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNPUSHDISPATCHER" 
   (	"ID" NUMBER CONSTRAINT "RHN_PUSHDISPATCH_ID_NN" NOT NULL ENABLE, 
	"JABBER_ID" VARCHAR2(128) CONSTRAINT "RHN_PUSHDISPATCH_JID_NN" NOT NULL ENABLE, 
	"LAST_CHECKIN" DATE DEFAULT sysdate CONSTRAINT "RHN_PUSHDISPATCH_LC_NN" NOT NULL ENABLE, 
	"HOSTNAME" VARCHAR2(256) CONSTRAINT "RHN_PUSHDISPATCH_HN_NN" NOT NULL ENABLE, 
	"PORT" NUMBER CONSTRAINT "RHN_PUSHDISPATCH_PORT_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT sysdate CONSTRAINT "RHN_PUSHDISPATCH_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT sysdate CONSTRAINT "RHN_PUSHDISPATCH_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_PUSHDISPATCH_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_PUSHDISPATCH_JID_UQ" UNIQUE ("JABBER_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
