-- created by Oraschemadoc Fri Jun 13 14:05:53 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNPACKAGESIGNATURE" 
   (	"ID" NUMBER CONSTRAINT "RHN_PKG_SIG_ID_NN" NOT NULL ENABLE, 
	"PACKAGE_ID" NUMBER CONSTRAINT "RHN_PKG_SIG_PID_NN" NOT NULL ENABLE, 
	"TYPE_ID" NUMBER CONSTRAINT "RHN_PKG_SIG_TID_NN" NOT NULL ENABLE, 
	"SIGNATURE" VARCHAR2(3000) CONSTRAINT "RHN_PKG_SIG_SIGNATURE_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_PKG_SIG_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_PKG_SIG_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_PKG_SIG_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_PKG_SIG_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_PKG_SIG_TID_FK" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGESIGTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
