-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNRELEASECHANNELMAP" 
   (	"PRODUCT" VARCHAR2(64) CONSTRAINT "RHN_RCM_PRODCT_NN" NOT NULL ENABLE, 
	"VERSION" VARCHAR2(64) CONSTRAINT "RHN_RCM_VERSN_NN" NOT NULL ENABLE, 
	"RELEASE" VARCHAR2(64) CONSTRAINT "RHN_RCM_RELSE_NN" NOT NULL ENABLE, 
	"CHANNEL_ARCH_ID" NUMBER CONSTRAINT "RHN_RCM_CAID_NN" NOT NULL ENABLE, 
	"CHANNEL_ID" NUMBER CONSTRAINT "RHN_RCM_CID_NN" NOT NULL ENABLE, 
	"IS_DEFAULT" CHAR(1) CONSTRAINT "RHN_RCM_DEFAULT_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_RCM_DEFAULT_CK" CHECK (is_default in ('Y', 'N')) ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
