-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNREGTOKENENTITLEMENT" 
   (	"REG_TOKEN_ID" NUMBER CONSTRAINT "RHN_REG_TOK_ENT_RTID_NN" NOT NULL ENABLE, 
	"SERVER_GROUP_TYPE_ID" NUMBER CONSTRAINT "RHN_REG_TOK_ENT_SGTID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_REG_TOK_ENT_RTID_FK" FOREIGN KEY ("REG_TOKEN_ID")
	  REFERENCES "RHNSAT"."RHNREGTOKEN" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_REG_TOK_ENT_SGTID_FK" FOREIGN KEY ("SERVER_GROUP_TYPE_ID")
	  REFERENCES "RHNSAT"."RHNSERVERGROUPTYPE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
