-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNREGTOKENCONFIGCHANNELS" 
   (	"TOKEN_ID" NUMBER CONSTRAINT "RHN_REGTOK_CONFCHAN_TID_NN" NOT NULL ENABLE, 
	"CONFIG_CHANNEL_ID" NUMBER CONSTRAINT "RHN_REGTOK_CONFCHAN_CCID_NN" NOT NULL ENABLE, 
	"POSITION" NUMBER CONSTRAINT "RHN_REGTOK_CONFCHAN_POS_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_REGTOK_CONFCHAN_TID_FK" FOREIGN KEY ("TOKEN_ID")
	  REFERENCES "RHNSAT"."RHNREGTOKEN" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_REGTOK_CONFCHAN_CCID_FK" FOREIGN KEY ("CONFIG_CHANNEL_ID")
	  REFERENCES "RHNSAT"."RHNCONFIGCHANNEL" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
