-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSGTYPEBASEADDONCOMPAT" 
   (	"BASE_ID" NUMBER CONSTRAINT "RHN_SGT_BAC_BID_NN" NOT NULL ENABLE, 
	"ADDON_ID" NUMBER CONSTRAINT "RHN_SGT_BAC_AID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SGT_BAC_BID_FK" FOREIGN KEY ("BASE_ID")
	  REFERENCES "RHNSAT"."RHNSERVERGROUPTYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SGT_BAC_AID_FK" FOREIGN KEY ("ADDON_ID")
	  REFERENCES "RHNSAT"."RHNSERVERGROUPTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
