-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSATELLITECHANNELFAMILY" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SAT_CF_SID_NN" NOT NULL ENABLE, 
	"CHANNEL_FAMILY_ID" NUMBER CONSTRAINT "RHN_SAT_CF_CFID_NN" NOT NULL ENABLE, 
	"QUANTITY" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SAT_CF_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SAT_CF_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SAT_CF_SID_CFID_UQ" UNIQUE ("SERVER_ID", "CHANNEL_FAMILY_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SAT_CF_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SAT_CF_CFID_FK" FOREIGN KEY ("CHANNEL_FAMILY_ID")
	  REFERENCES "RHNSAT"."RHNCHANNELFAMILY" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
