-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSATELLITESERVERGROUP" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SATSG_SID_NN" NOT NULL ENABLE, 
	"SERVER_GROUP_TYPE" NUMBER CONSTRAINT "RHN_SATSG_SGTYPE_NN" NOT NULL ENABLE, 
	"MAX_MEMBERS" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SATSG_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SATSG_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SATSG_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSATELLITEINFO" ("SERVER_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SATSG_SGTYPE_FK" FOREIGN KEY ("SERVER_GROUP_TYPE")
	  REFERENCES "RHNSAT"."RHNSERVERGROUPTYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
