-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERNEEDEDERRATACACHE" 
   (	"ORG_ID" NUMBER CONSTRAINT "RHN_SNEC_OID_NN" NOT NULL ENABLE, 
	"SERVER_ID" NUMBER CONSTRAINT "RHN_SNEC_SID_NN" NOT NULL ENABLE, 
	"ERRATA_ID" NUMBER, 
	 CONSTRAINT "RHN_SNEC_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SNEC_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SNEC_EID_FK" FOREIGN KEY ("ERRATA_ID")
	  REFERENCES "RHNSAT"."RHNERRATA" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
