-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERPROFILE" 
   (	"ID" NUMBER CONSTRAINT "RHN_SERVER_PROFILE_ID_NN" NOT NULL ENABLE, 
	"ORG_ID" NUMBER CONSTRAINT "RHN_SERVER_PROFILE_OID_NN" NOT NULL ENABLE, 
	"BASE_CHANNEL" NUMBER CONSTRAINT "RHN_SERVER_PROFILE_BCID_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(128), 
	"DESCRIPTION" VARCHAR2(256), 
	"INFO" VARCHAR2(128), 
	"PROFILE_TYPE_ID" NUMBER CONSTRAINT "RHN_SERVER_PROFILE_PTYPE_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SERVER_PROFILE_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SERVER_PROFILE_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SERVER_PROFILE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SERVER_PROFILE_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SERVER_PROFILE_BCID_FK" FOREIGN KEY ("BASE_CHANNEL")
	  REFERENCES "RHNSAT"."RHNCHANNEL" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SERVER_PROFILE_PTYPE_FK" FOREIGN KEY ("PROFILE_TYPE_ID")
	  REFERENCES "RHNSAT"."RHNSERVERPROFILETYPE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
