-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSNAPSHOT" 
   (	"ID" NUMBER CONSTRAINT "RHN_SNAPSHOT_ID_NN" NOT NULL ENABLE, 
	"ORG_ID" NUMBER CONSTRAINT "RHN_SNAPSHOT_OID_NN" NOT NULL ENABLE, 
	"INVALID" NUMBER, 
	"REASON" VARCHAR2(4000) CONSTRAINT "RHN_SNAPSHOT_REASON_NN" NOT NULL ENABLE, 
	"SERVER_ID" NUMBER CONSTRAINT "RHN_SNAPSHOT_SID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SNAPSHOT_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SNAPSHOT_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SNAPSHOT_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SNAPSHOT_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SNAPSHOT_INVALID_FK" FOREIGN KEY ("INVALID")
	  REFERENCES "RHNSAT"."RHNSNAPSHOTINVALIDREASON" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SNAPSHOT_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
