-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERGROUPNOTES" 
   (	"ID" NUMBER CONSTRAINT "RHN_SERVERGRP_NOTE_ID_NN" NOT NULL ENABLE, 
	"CREATOR" NUMBER, 
	"SERVER_GROUP_ID" NUMBER CONSTRAINT "RHN_SERVERGRP_NOTE_NN" NOT NULL ENABLE, 
	"SUBJECT" VARCHAR2(80) CONSTRAINT "RHN_SERVERGRP_NOTE_SUBJECT_NN" NOT NULL ENABLE, 
	"NOTE" VARCHAR2(4000) CONSTRAINT "RHN_SERVERGRP_NOTE_NOTE_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SERVERGRP_NOTE_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SERVERGRP_NOTE_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SERVERGRP_NOTE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SERVERGRP_NOTE_CREATOR_FK" FOREIGN KEY ("CREATOR")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_SERVERGRP_NOTE_FK" FOREIGN KEY ("SERVER_GROUP_ID")
	  REFERENCES "RHNSAT"."RHNSERVERGROUP" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
