-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERMESSAGE" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SM_SERVER_ID_NN" NOT NULL ENABLE, 
	"MESSAGE_ID" NUMBER CONSTRAINT "RHN_SM_MESSAGE_ID_NN" NOT NULL ENABLE, 
	"SERVER_EVENT" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SM_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SM_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SM_SERVER_ID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SM_MESSAGE_ID_FK" FOREIGN KEY ("MESSAGE_ID")
	  REFERENCES "RHNSAT"."RHNMESSAGE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SM_SE_FK" FOREIGN KEY ("SERVER_EVENT")
	  REFERENCES "RHNSAT"."RHNSERVEREVENT" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
