-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSNPERRATAQUEUE" 
   (	"ERRATA_ID" NUMBER CONSTRAINT "RHN_SNPERRQUEUE_EID_NN" NOT NULL ENABLE, 
	"PROCESSED" NUMBER DEFAULT (0) -- this should get a check as well?
			 CONSTRAINT "RHN_SNPERRQUEUE_PROCESSED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SNPERRQUEUE_EID_FK" FOREIGN KEY ("ERRATA_ID")
	  REFERENCES "RHNSAT"."RHNERRATA" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
