-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERACTION" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SERVER_ACTION_SID_NN" NOT NULL ENABLE, 
	"ACTION_ID" NUMBER CONSTRAINT "RHN_SERVER_ACTION_AID_NN" NOT NULL ENABLE, 
	"STATUS" NUMBER CONSTRAINT "RHN_SERVER_ACTION_STATUS_NN" NOT NULL ENABLE, 
	"RESULT_CODE" NUMBER, 
	"RESULT_MSG" VARCHAR2(1024), 
	"PICKUP_TIME" DATE, 
	"REMAINING_TRIES" NUMBER DEFAULT (5) CONSTRAINT "RHN_SERVER_ACTION_REMAINING_NN" NOT NULL ENABLE, 
	"COMPLETION_TIME" DATE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SERVER_ACTION_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SERVER_ACTION_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SERVER_ACTION_SID_AID_UQ" UNIQUE ("SERVER_ID", "ACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SERVER_ACTION_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SERVER_ACTION_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RHNSAT"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SERVER_ACTION_STATUS_FK" FOREIGN KEY ("STATUS")
	  REFERENCES "RHNSAT"."RHNACTIONSTATUS" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
