-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSOLARISPATCHEDPACKAGE" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SOLARIS_PATCHEDP_SID_NN" NOT NULL ENABLE, 
	"PATCH_ID" NUMBER CONSTRAINT "RHN_SOLARIS_PATCHEDP_PID_NN" NOT NULL ENABLE, 
	"PACKAGE_NEVRA_ID" NUMBER CONSTRAINT "RHN_SOLARIS_PATCHEDP_PNID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SOLARIS_PATCHEDP_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SOLARIS_PATCHEDP_PID_FK" FOREIGN KEY ("PATCH_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SOLARIS_PATCHEDP_PNID_FK" FOREIGN KEY ("PACKAGE_NEVRA_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGENEVRA" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
