-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERINFO" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SERVER_INFO_SID_NN" NOT NULL ENABLE, 
	"CHECKIN" DATE DEFAULT (sysdate), 
	"CHECKIN_COUNTER" NUMBER DEFAULT (0), 
	 CONSTRAINT "RHN_SERVER_INFO_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
