-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSOLARISPATCHSETMEMBERS" 
   (	"PATCH_ID" NUMBER CONSTRAINT "RHN_SOLARIS_PSM_PID_NN" NOT NULL ENABLE, 
	"PATCH_SET_ID" NUMBER CONSTRAINT "RHN_SOLARIS_PSM_PSID_NN" NOT NULL ENABLE, 
	"PATCH_ORDER" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SOLARIS_PSM_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SOLARIS_PSM_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SOLARIS_PSM_PID_FK" FOREIGN KEY ("PATCH_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SOLARIS_PSM_PSID_FK" FOREIGN KEY ("PATCH_SET_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
