-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERGROUP" 
   (	"ID" NUMBER CONSTRAINT "RHN_SERVERGROUP_ID_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(64) CONSTRAINT "RHN_SERVERGROUP_NAME_NN" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1024) CONSTRAINT "RHN_SERVERGROUP_DESC_NN" NOT NULL ENABLE, 
	"MAX_MEMBERS" NUMBER, 
	"CURRENT_MEMBERS" NUMBER DEFAULT 0 CONSTRAINT "RHN_SERVERGROUP_CURMEMBERS_NN" NOT NULL ENABLE, 
	"GROUP_TYPE" NUMBER, 
	"ORG_ID" NUMBER CONSTRAINT "RHN_SERVERGROUP_OID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SERVERGROUP_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SERVERGROUP_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SERVERGROUP_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SERVERGROUP_TYPE_FK" FOREIGN KEY ("GROUP_TYPE")
	  REFERENCES "RHNSAT"."RHNSERVERGROUPTYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SERVERGROUP_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
