-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERNETINTERFACE" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SRV_NET_IFACE_SID_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(32) CONSTRAINT "RHN_SRV_NET_IFACE_NAME_NN" NOT NULL ENABLE, 
	"IP_ADDR" VARCHAR2(64), 
	"NETMASK" VARCHAR2(64), 
	"BROADCAST" VARCHAR2(64), 
	"HW_ADDR" VARCHAR2(18), 
	"MODULE" VARCHAR2(128), 
	"CREATED" DATE DEFAULT sysdate CONSTRAINT "RHN_SRV_NET_IFACE_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT sysdate CONSTRAINT "RHN_SRV_NET_IFACE_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SRV_NET_IFACE_SID_NAME_UQ" UNIQUE ("SERVER_ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SRV_NET_IFACE_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
