-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSATELLITEINFO" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SATELLITE_INFO_SID_NN" NOT NULL ENABLE, 
	"EVR_ID" NUMBER, 
	"CERT" BLOB CONSTRAINT "RHN_SATELLITE_INFO_CERT_NN" NOT NULL ENABLE, 
	"PRODUCT" VARCHAR2(256) CONSTRAINT "RHN_SATELLITE_INFO_PRODUCT_NN" NOT NULL ENABLE, 
	"OWNER" VARCHAR2(256) CONSTRAINT "RHN_SATELLITE_INFO_OWNER_NN" NOT NULL ENABLE, 
	"ISSUED_STRING" VARCHAR2(256), 
	"EXPIRATION_STRING" VARCHAR2(256), 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SATELLITE_INFO_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SATELLITE_INFO_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SATELLITE_INFO_SID_UQ" UNIQUE ("SERVER_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SATELLITE_INFO_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SATELLITE_INFO_EID_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGEEVR" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 LOB ("CERT") STORE AS (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 
/
