-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSGTYPEVIRTSUBLEVEL" 
   (	"SERVER_GROUP_TYPE_ID" NUMBER CONSTRAINT "RHN_SGTVSL_SGTID_NN" NOT NULL ENABLE, 
	"VIRT_SUB_LEVEL_ID" NUMBER CONSTRAINT "RHN_SGTVSL_VSLID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT sysdate CONSTRAINT "RHN_SGTVSL_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT sysdate CONSTRAINT "RHN_SGTVSL_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SGTVSL_SGTID_FK" FOREIGN KEY ("SERVER_GROUP_TYPE_ID")
	  REFERENCES "RHNSAT"."RHNSERVERGROUPTYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SGTVSL_VSLID_FK" FOREIGN KEY ("VIRT_SUB_LEVEL_ID")
	  REFERENCES "RHNSAT"."RHNVIRTSUBLEVEL" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
