-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERGROUPTYPEFEATURE" 
   (	"SERVER_GROUP_TYPE_ID" NUMBER CONSTRAINT "RHN_SGT_SGTID_NN" NOT NULL ENABLE, 
	"FEATURE_ID" NUMBER CONSTRAINT "RHN_SGT_FID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SGT_FEAT_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SGT_FEAT_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SGT_SGID_FK" FOREIGN KEY ("SERVER_GROUP_TYPE_ID")
	  REFERENCES "RHNSAT"."RHNSERVERGROUPTYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SGT_FID_FK" FOREIGN KEY ("FEATURE_ID")
	  REFERENCES "RHNSAT"."RHNFEATURE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
