-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERPATH" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SERVERPATH_SID_NN" NOT NULL ENABLE, 
	"PROXY_SERVER_ID" NUMBER CONSTRAINT "RHN_SERVERPATH_PSID_NN" NOT NULL ENABLE, 
	"POSITION" NUMBER CONSTRAINT "RHN_SERVERPATH_POS_NN" NOT NULL ENABLE, 
	"HOSTNAME" VARCHAR2(256) CONSTRAINT "RHN_SERVERPATH_HOSTNAME_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SERVERPATH_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SERVERPATH_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SERVERPATH_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SERVERPATH_PSID_FK" FOREIGN KEY ("PROXY_SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
