-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERACTIONVERIFYRESULT" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SACTIONVR_SID_NN" NOT NULL ENABLE, 
	"ACTION_ID" NUMBER CONSTRAINT "RHN_SACTIONVR_AID_NN" NOT NULL ENABLE, 
	"PACKAGE_NAME_ID" NUMBER CONSTRAINT "RHN_SACTIONVR_PNID_NN" NOT NULL ENABLE, 
	"PACKAGE_EVR_ID" NUMBER CONSTRAINT "RHN_SACTIONVR_PEID_NN" NOT NULL ENABLE, 
	"PACKAGE_ARCH_ID" NUMBER CONSTRAINT "RHN_SACTIONVR_PAID_NN" NOT NULL ENABLE, 
	"PACKAGE_CAPABILITY_ID" NUMBER CONSTRAINT "RHN_SACTIONVR_PCID_NN" NOT NULL ENABLE, 
	"ATTRIBUTE" CHAR(1), 
	"SIZE_DIFFERS" CHAR(1) CONSTRAINT "RHN_SACTIONVR_SIZE_NN" NOT NULL ENABLE, 
	"MODE_DIFFERS" CHAR(1) CONSTRAINT "RHN_SACTIONVR_MODE_NN" NOT NULL ENABLE, 
	"MD5_DIFFERS" CHAR(1) CONSTRAINT "RHN_SACTIONVR_MD5_NN" NOT NULL ENABLE, 
	"DEVNUM_DIFFERS" CHAR(1) CONSTRAINT "RHN_SACTIONVR_DEVNUM_NN" NOT NULL ENABLE, 
	"READLINK_DIFFERS" CHAR(1) CONSTRAINT "RHN_SACTIONVR_READLINK_NN" NOT NULL ENABLE, 
	"UID_DIFFERS" CHAR(1) CONSTRAINT "RHN_SACTIONVR_UID_NN" NOT NULL ENABLE, 
	"GID_DIFFERS" CHAR(1) CONSTRAINT "RHN_SACTIONVR_GID_NN" NOT NULL ENABLE, 
	"MTIME_DIFFERS" CHAR(1) CONSTRAINT "RHN_SACTIONVR_MTIME_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SACTIONVR_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SACTIONVR_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_ATTR_CK" CHECK (attribute in ('c','d','g','l','r')) ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_SIZE_CK" CHECK (size_differs in ('Y','N','?')) ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_MODE_CK" CHECK (mode_differs in ('Y','N','?')) ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_MD5_CK" CHECK (md5_differs in ('Y','N','?')) ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_DEVNUM_CK" CHECK (devnum_differs in ('Y','N','?')) ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_READLINK_CK" CHECK (readlink_differs in ('Y','N','?')) ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_UID_CK" CHECK (uid_differs in ('Y','N','?')) ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_GID_CK" CHECK (gid_differs in ('Y','N','?')) ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_MTIME_CK" CHECK (mtime_differs in ('Y','N','?')) ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RHNSAT"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_PNID_FK" FOREIGN KEY ("PACKAGE_NAME_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGENAME" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_PEID_FK" FOREIGN KEY ("PACKAGE_EVR_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGEEVR" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGEARCH" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SACTIONVR_PCID_FK" FOREIGN KEY ("PACKAGE_CAPABILITY_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGECAPABILITY" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
