-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSET" 
   (	"USER_ID" NUMBER CONSTRAINT "RHN_SET_USER_NN" NOT NULL ENABLE, 
	"LABEL" VARCHAR2(32) CONSTRAINT "RHN_SET_LABEL_NN" NOT NULL ENABLE, 
	"ELEMENT" NUMBER CONSTRAINT "RHN_SET_ELEM_NN" NOT NULL ENABLE, 
	"ELEMENT_TWO" NUMBER, 
	 CONSTRAINT "RHN_SET_USER_LABEL_ELEM_UNQ" UNIQUE ("USER_ID", "LABEL", "ELEMENT", "ELEMENT_TWO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_SET_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
