-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERACTIONVERIFYMISSING" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SACTIONVM_SID_NN" NOT NULL ENABLE, 
	"ACTION_ID" NUMBER CONSTRAINT "RHN_SACTIONVM_AID_NN" NOT NULL ENABLE, 
	"PACKAGE_NAME_ID" NUMBER CONSTRAINT "RHN_SACTIONVM_PNID_NN" NOT NULL ENABLE, 
	"PACKAGE_EVR_ID" NUMBER CONSTRAINT "RHN_SACTIONVM_PEID_NN" NOT NULL ENABLE, 
	"PACKAGE_ARCH_ID" NUMBER CONSTRAINT "RHN_SACTIONVM_PAID_NN" NOT NULL ENABLE, 
	"PACKAGE_CAPABILITY_ID" NUMBER CONSTRAINT "RHN_SACTIONVM_PCID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SACTIONVM_CREAT_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SACTIONVM_MOD_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SACTIONVM_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SACTIONVM_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RHNSAT"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SACTIONVM_PNID_FK" FOREIGN KEY ("PACKAGE_NAME_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGENAME" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SACTIONVM_PEID_FK" FOREIGN KEY ("PACKAGE_EVR_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGEEVR" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SACTIONVM_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGEARCH" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SACTIONVM_PCID_FK" FOREIGN KEY ("PACKAGE_CAPABILITY_ID")
	  REFERENCES "RHNSAT"."RHNPACKAGECAPABILITY" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
