-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSNAPSHOTTAG" 
   (	"SNAPSHOT_ID" NUMBER CONSTRAINT "RHN_ST_SSID_NN" NOT NULL ENABLE, 
	"TAG_ID" NUMBER CONSTRAINT "RHN_ST_TID_NN" NOT NULL ENABLE, 
	"SERVER_ID" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ST_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_ST_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ST_SSID_FK" FOREIGN KEY ("SNAPSHOT_ID")
	  REFERENCES "RHNSAT"."RHNSNAPSHOT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ST_TID_FK" FOREIGN KEY ("TAG_ID")
	  REFERENCES "RHNSAT"."RHNTAG" ("ID") ENABLE, 
	 CONSTRAINT "RHN_ST_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
