-- created by Oraschemadoc Fri Jun 13 14:05:55 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERLOCK" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SERVER_LOCK_SID_NN" NOT NULL ENABLE, 
	"LOCKER_ID" NUMBER, 
	"REASON" VARCHAR2(4000), 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SERVER_LOCK_CREATED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SERVER_LOCK_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SERVER_LOCK_LID_FK" FOREIGN KEY ("LOCKER_ID")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
