-- created by Oraschemadoc Fri Jun 13 14:05:54 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNSERVERCUSTOMDATAVALUE" 
   (	"SERVER_ID" NUMBER CONSTRAINT "RHN_SCDV_SID_NN" NOT NULL ENABLE, 
	"KEY_ID" NUMBER CONSTRAINT "RHN_SCDV_KID_NN" NOT NULL ENABLE, 
	"VALUE" VARCHAR2(4000), 
	"CREATED_BY" NUMBER, 
	"LAST_MODIFIED_BY" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SCDV_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_SCDV_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SCDV_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "RHNSAT"."RHNSERVER" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SCDV_KID_FK" FOREIGN KEY ("KEY_ID")
	  REFERENCES "RHNSAT"."RHNCUSTOMDATAKEY" ("ID") ENABLE, 
	 CONSTRAINT "RHN_SCDV_CB_FK" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_SCDV_LMB_FK" FOREIGN KEY ("LAST_MODIFIED_BY")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
