-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNTRANSACTIONELEMENT" 
   (	"TRANSACTION_ID" NUMBER CONSTRAINT "RHN_TRANSELEM_TID_NN" NOT NULL ENABLE, 
	"TRANSACTION_PACKAGE_ID" NUMBER CONSTRAINT "RHN_TRANSELEM_TPID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_TRANSELEM_TID_FK" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "RHNSAT"."RHNTRANSACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_TRANSELEM_TPID_FK" FOREIGN KEY ("TRANSACTION_PACKAGE_ID")
	  REFERENCES "RHNSAT"."RHNTRANSACTIONPACKAGE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
