-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNTEXTMESSAGE" 
   (	"MESSAGE_ID" NUMBER CONSTRAINT "RHN_TM_MESSAGE_ID_NN" NOT NULL ENABLE, 
	"MESSAGE_BODY" VARCHAR2(4000) CONSTRAINT "RHN_TM_MESSAGE_BODY_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_TM_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_TM_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_TM_MESSAGE_ID_FK" FOREIGN KEY ("MESSAGE_ID")
	  REFERENCES "RHNSAT"."RHNMESSAGE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
