-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNTEMPLATESTRING" 
   (	"ID" NUMBER CONSTRAINT "RHN_TEMPLATE_STR_ID_NN" NOT NULL ENABLE, 
	"CATEGORY_ID" NUMBER CONSTRAINT "RHN_TEMPLATE_STR_CID_NN" NOT NULL ENABLE, 
	"LABEL" VARCHAR2(64) CONSTRAINT "RHN_TEMPLATE_STR_KEY_NN" NOT NULL ENABLE, 
	"VALUE" VARCHAR2(4000), 
	"DESCRIPTION" VARCHAR2(512) CONSTRAINT "RHN_TEMPLATE_STR_DESC_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_TEMPLATE_STR_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_TEMPLATE_STR_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_TEMPLATE_STR_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_TEMPLATE_STR_CID_LABEL_UQ" UNIQUE ("CATEGORY_ID", "LABEL")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_TEMPLATE_STR_CID_FK" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "RHNSAT"."RHNTEMPLATECATEGORY" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
