-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNTIMEZONE" 
   (	"ID" NUMBER CONSTRAINT "RHN_TIMEZONE_ID_NN" NOT NULL ENABLE, 
	"OLSON_NAME" VARCHAR2(128) CONSTRAINT "RHN_TIMEZONE_OLSON_NN" NOT NULL ENABLE, 
	"DISPLAY_NAME" VARCHAR2(128) CONSTRAINT "RHN_TIMEZONE_DISPLAY_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_TIMEZONE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
