-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNTASKQUEUE" 
   (	"ORG_ID" NUMBER CONSTRAINT "RHN_TASK_QUEUE_ORG_ID_NN" NOT NULL ENABLE, 
	"TASK_NAME" VARCHAR2(64) CONSTRAINT "RHN_TASK_QUEUE_TASK_NAME_NN" NOT NULL ENABLE, 
	"TASK_DATA" NUMBER, 
	"PRIORITY" NUMBER DEFAULT 0, 
	"EARLIEST" DATE DEFAULT sysdate CONSTRAINT "RHN_TASK_QUEUE_EARLIEST_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_TASK_QUEUE_ORG_ID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
