-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNTINYURL" 
   (	"TOKEN" VARCHAR2(64) CONSTRAINT "RHN_TU_TOKEN_NN" NOT NULL ENABLE, 
	"URL" VARCHAR2(512) CONSTRAINT "RHN_TU_URL_NN" NOT NULL ENABLE, 
	"ENABLED" VARCHAR2(1) CONSTRAINT "RHN_TU_ENABLED_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_TU_CREATED_NN" NOT NULL ENABLE, 
	"EXPIRES" DATE DEFAULT (sysdate) CONSTRAINT "RHN_TU_EXPIRES_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_TU_ENABLED_CK" CHECK (enabled in ('Y','N')) ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
