-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNUSERGROUPMEMBERS" 
   (	"USER_ID" NUMBER CONSTRAINT "RHN_UGMEMBERS_UID_NN" NOT NULL ENABLE, 
	"USER_GROUP_ID" NUMBER CONSTRAINT "RHN_UGMEMBERS_UGID_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_UGMEMBERS_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_UGMEMBERS_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_UGMEMBERS_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_UGMEMBERS_UGID_FK" FOREIGN KEY ("USER_GROUP_ID")
	  REFERENCES "RHNSAT"."RHNUSERGROUP" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
