-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNUSERINFOPANE" 
   (	"USER_ID" NUMBER CONSTRAINT "RHN_USR_INFO_PANE_UID_NN" NOT NULL ENABLE, 
	"PANE_ID" NUMBER CONSTRAINT "RHN_USR_INFO_PANE_PID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_USR_INFO_PANE_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_USR_INFO_PANE_PID_FK" FOREIGN KEY ("PANE_ID")
	  REFERENCES "RHNSAT"."RHNINFOPANE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
