-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNUSERMESSAGE" 
   (	"USER_ID" NUMBER CONSTRAINT "RHN_UM_USER_ID_NN" NOT NULL ENABLE, 
	"MESSAGE_ID" NUMBER CONSTRAINT "RHN_UM_MESSAGE_ID_NN" NOT NULL ENABLE, 
	"STATUS" NUMBER CONSTRAINT "RHN_UM_STATUS_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_UM_USER_ID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ENABLE, 
	 CONSTRAINT "RHN_UM_MESSAGE_ID_FK" FOREIGN KEY ("MESSAGE_ID")
	  REFERENCES "RHNSAT"."RHNMESSAGE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_UM_STATUS_FK" FOREIGN KEY ("STATUS")
	  REFERENCES "RHNSAT"."RHNUSERMESSAGESTATUS" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
