-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNUSERINFO" 
   (	"USER_ID" NUMBER CONSTRAINT "RHN_USER_INFO_USER_NN" NOT NULL ENABLE, 
	"NO_CLEAR_SETS" NUMBER DEFAULT (0) CONSTRAINT "RHN_USER_INFO_CLEARSETS_NN" NOT NULL ENABLE, 
	"PAGE_SIZE" NUMBER DEFAULT (20) CONSTRAINT "RHN_USER_INFO_PAGESIZE_NN" NOT NULL ENABLE, 
	"EMAIL_NOTIFY" NUMBER DEFAULT (1) CONSTRAINT "RHN_USER_INFO_NOTIFY_NN" NOT NULL ENABLE, 
	"BAD_EMAIL" NUMBER DEFAULT (0) CONSTRAINT "RHN_USER_INFO_BADEMAIL_NN" NOT NULL ENABLE, 
	"TZ_OFFSET" NUMBER DEFAULT (-5) CONSTRAINT "RHN_USER_INFO_TZOFFSET_NN" NOT NULL ENABLE, 
	"TIMEZONE_ID" NUMBER, 
	"SHOW_APPLIED_ERRATA" CHAR(1) DEFAULT ('N') CONSTRAINT "RHN_USER_INFO_SEA_NN" NOT NULL ENABLE, 
	"SHOW_SYSTEM_GROUP_LIST" CHAR(1) DEFAULT ('N') CONSTRAINT "RHN_USER_INFO_SSGL_NN" NOT NULL ENABLE, 
	"AGREED_TO_TERMS" CHAR(1) DEFAULT ('N') CONSTRAINT "RHN_USER_INFO_AGREED_NN" NOT NULL ENABLE, 
	"USE_PAM_AUTHENTICATION" CHAR(1) DEFAULT ('N') CONSTRAINT "RHN_USER_INFO_PAM_NN" NOT NULL ENABLE, 
	"LAST_LOGGED_IN" DATE, 
	"AGREED_TO_WS_TERMS" CHAR(1), 
	"AGREED_TO_ES_TERMS" CHAR(1), 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_USER_INFO_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_USER_INFO_MODIFIED_NN" NOT NULL ENABLE, 
	"PREFERRED_LOCALE" VARCHAR2(8), 
	 CONSTRAINT "RHN_USER_INFO_TZOFFSET_CK" CHECK (tz_offset >= -11 and tz_offset <= 13) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_SEA_CK" CHECK (show_applied_errata in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_SSGL_CK" CHECK (show_system_group_list in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_AGREED_CK" CHECK (agreed_to_terms in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_PAM_CK" CHECK (use_pam_authentication in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_WS_CK" CHECK (agreed_to_ws_terms is null or agreed_to_ws_terms in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_ES_CK" CHECK (agreed_to_es_terms is null or agreed_to_es_terms in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_UID_UQ" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 32 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "RHNSAT"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_USER_INFO_TZID_FK" FOREIGN KEY ("TIMEZONE_ID")
	  REFERENCES "RHNSAT"."RHNTIMEZONE" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
