-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNVIRTUALINSTANCEINSTALLLOG" 
   (	"ID" NUMBER CONSTRAINT "RHN_VIIL_ID_NN" NOT NULL ENABLE, 
	"LOG_MESSAGE" VARCHAR2(4000) CONSTRAINT "RHN_VIIL_LM_NN" NOT NULL ENABLE, 
	"KS_SESSION_ID" NUMBER, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_VIIL_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_VIIL_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_VIIL_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "RHN_VIIL_KS_SID_FK" FOREIGN KEY ("KS_SESSION_ID")
	  REFERENCES "RHNSAT"."RHNKICKSTARTSESSION" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
