-- created by Oraschemadoc Fri Jun 13 14:05:56 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."RHNVIRTUALINSTANCEINFO" 
   (	"NAME" VARCHAR2(128), 
	"INSTANCE_ID" NUMBER CONSTRAINT "RHN_VII_VIID_NN" NOT NULL ENABLE, 
	"INSTANCE_TYPE" NUMBER CONSTRAINT "RHN_VII_IT_NN" NOT NULL ENABLE, 
	"MEMORY_SIZE_K" NUMBER, 
	"VCPUS" NUMBER, 
	"STATE" NUMBER CONSTRAINT "RHN_VII_STATE_NN" NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_VII_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "RHN_VII_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "RHN_VII_VIID_FK" FOREIGN KEY ("INSTANCE_ID")
	  REFERENCES "RHNSAT"."RHNVIRTUALINSTANCE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_VII_IT_FK" FOREIGN KEY ("INSTANCE_TYPE")
	  REFERENCES "RHNSAT"."RHNVIRTUALINSTANCETYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_VII_STATE_FK" FOREIGN KEY ("STATE")
	  REFERENCES "RHNSAT"."RHNVIRTUALINSTANCESTATE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
