-- created by Oraschemadoc Fri Jun 13 14:05:58 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."STATE_CHANGE" 
   (	"O_ID" VARCHAR2(64) CONSTRAINT "STATE_CHANGE_O_ID_NN" NOT NULL ENABLE, 
	"ENTRY_TIME" NUMBER CONSTRAINT "STATE_CHANGE_ETIME_NN" NOT NULL ENABLE, 
	"DATA" VARCHAR2(4000)
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
