-- created by Oraschemadoc Fri Jun 13 14:05:58 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."TIME_SERIES" 
   (	"O_ID" VARCHAR2(64) CONSTRAINT "TIME_SERIES_O_ID_NN" NOT NULL ENABLE, 
	"ENTRY_TIME" NUMBER CONSTRAINT "TIME_SERIES_ETIME_NN" NOT NULL ENABLE, 
	"DATA" VARCHAR2(1024)
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
