-- created by Oraschemadoc Fri Jun 13 14:05:58 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."WEB_CUSTOMER" 
   (	"ID" NUMBER CONSTRAINT "WEB_CUSTOMER_ID_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(128) CONSTRAINT "WEB_CUSTOMER_NAME_NN" NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(48) CONSTRAINT "WEB_CUSTOMER_PW_NN" NOT NULL ENABLE, 
	"ORACLE_CUSTOMER_ID" NUMBER, 
	"ORACLE_CUSTOMER_NUMBER" NUMBER, 
	"CUSTOMER_TYPE" CHAR(1) DEFAULT ('P') CONSTRAINT "WEB_CUSTOMER_TYPE_NN" NOT NULL ENABLE, 
	"CREDIT_APPLICATION_COMPLETED" VARCHAR2(1), 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "WEB_CUSTOMER_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "WEB_CUSTOMER_MODIFIED_NN" NOT NULL ENABLE, 
	 CONSTRAINT "WEB_CUSTOMER_TYPE_LIST" CHECK (customer_type in ('B', 'P')) ENABLE, 
	 CONSTRAINT "WEB_CUSTOMER_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "WEB_CUSTOMER_OCID_UNQ" UNIQUE ("ORACLE_CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "WEB_CUSTOMER_OCN_UNQ" UNIQUE ("ORACLE_CUSTOMER_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
