-- created by Oraschemadoc Fri Jun 13 14:05:58 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."WEB_CUSTOMER_NOTIFICATION" 
   (	"ID" NUMBER CONSTRAINT "WEB_CUST_NOT_ID_NN" NOT NULL ENABLE, 
	"ORG_ID" NUMBER CONSTRAINT "WEB_CUST_NOT_OID_NN" NOT NULL ENABLE, 
	"CONTACT_EMAIL_ADDRESS" VARCHAR2(150) CONSTRAINT "WEB_CUST_NOT_EA_NN" NOT NULL ENABLE, 
	"CREATION_DATE" DATE CONSTRAINT "WEB_CUST_NOT_CREAT_NN" NOT NULL ENABLE, 
	 CONSTRAINT "WEB_CUST_NOT_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "WEB_CUST_NOT_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 32 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 16 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
