-- created by Oraschemadoc Fri Jun 13 14:05:58 2008
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "RHNSAT"."WEB_CONTACT" 
   (	"ID" NUMBER, 
	"ORG_ID" NUMBER CONSTRAINT "WEB_CONTACT_ORG_NN" NOT NULL ENABLE, 
	"LOGIN" VARCHAR2(64) CONSTRAINT "WEB_CONTACT_LOGIN_NN" NOT NULL ENABLE, 
	"LOGIN_UC" VARCHAR2(64) CONSTRAINT "WEB_CONTACT_LOGIN_UC_NN" NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(38) CONSTRAINT "WEB_CONTACT_PASSWORD_NN" NOT NULL ENABLE, 
	"OLD_PASSWORD" VARCHAR2(38), 
	"CREATED" DATE DEFAULT (sysdate) CONSTRAINT "WEB_CONTACT_CREATED_NN" NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (sysdate) CONSTRAINT "WEB_CONTACT_MODIFIED_NN" NOT NULL ENABLE, 
	"ORACLE_CONTACT_ID" NUMBER, 
	"IGNORE_FLAG" CHAR(1) DEFAULT ('N') CONSTRAINT "WEB_CONTACT_IGNORE_NN" NOT NULL ENABLE, 
	 CONSTRAINT "WEB_CONTACT_IGNORE_CK" CHECK (ignore_flag in ('N','Y')) ENABLE, 
	 CONSTRAINT "WEB_CONTACT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "WEB_CONTACT_LOGIN_UC_UNQ" UNIQUE ("LOGIN_UC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "WEB_CONTACT_OCID_UNQ" UNIQUE ("ORACLE_CONTACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE, 
	 CONSTRAINT "WEB_CONTACT_ORG_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "RHNSAT"."WEB_CUSTOMER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
