#!/usr/bin/perl
use Config::IniFiles;

$mode = uc($ARGV[0]);
if ($mode ne 'Y') {
	$mode = 'N';
}

$filename = '/etc/nocpulse/PlugFrame.ini';
$backupFilename = $filename.".backup";
if (system("cp -f $filename $backupFilename")>> 8) {
	die("Unable to backup config file - ending run\n");
} else {
	if ($cfg = new Config::IniFiles( -file => $filename)) {
		$cfg->setval('Plugin','enqueueMetrics',$mode);
		if ($cfg->WriteConfig($filename)) {
			print "Plugin->enqueueMetrics set to $mode\n";
		} else {
			print "WriteConfig failed - no changes made\n";
			if (system("cp -f $backupFilename $filename")>> 8) {
				die "BAD ERROR: UNABLE TO RESTORE BACKUP\n";
			} else {
				print "Backup restored OK\n";
			}
		}
	} else {
		print "Unable to read config file, no changes made\n";
	}
}
