#!/usr/bin/perl -w

use strict;

use Experimental::Sample;
use Test::Unit::Procedural;

use constant DEBUG => 0;

# code to be tested will be somewhere around here

# define tests, set_up and tear_down

sub test_ok_1 {
	assert(23 == 23);
}

sub test_ok_2 {
	assert(42 == 42);
}

sub test_ok_3 {
	my $sample = new Experimental::Sample();
        $sample->name( 'Joe' );
	assert( 'Joe' eq $sample->name() );
}

sub set_up {
	print "hello world\n" if DEBUG;
}

sub tear_down {
	print "leaving world again\n" if DEBUG;
}

# and run them

# This will not work, as the test methods were
# defined in package main:
#
# create_suite( 'Experimental::Sample' );
# run_suite();
#
# We need to create the default suite to pick 
# our test methods up - they just use the
# methods in Experimental::Sample ...
#
# The other way is to define the tests in
# package Experimental::Sample itself. 
# Then we can proceed as indicated above,
# but we obviously need to run the suite
# we created, not the default suite:

sub Experimental::Sample::test_ok_1 {
	assert(23 == 23);
}

sub Experimental::Sample::test_ok_2 {
	assert(42 == 42);
}

sub Experimental::Sample::test_ok_3 {
	my $sample = new Experimental::Sample();
        $sample->name( 'Joe' );
	assert( 'Joe' eq $sample->name() );
}

create_suite( 'Experimental::Sample' );
run_suite( 'Experimental::Sample' );
