# Makefile for the backend directory
#
# $Id: Makefile 111377 2007-02-20 17:12:07Z jbowes $

TOP         = ..
ROOT        = /usr/share/rhn
SUBDIR      = rhnkickstart
FILES       = __init__ \
			  kickstart \
			  lilo \
			  kickstart_exceptions \
			  common \
			  config

VIRT_FILES = kickstart_guest \
			 virtualization_kickstart_exceptions

# now include some Macros
include $(TOP)/Makefile.defs
