# Makefile for the satellite config files package
#
# $Id: Makefile,v 1.1 2002-08-20 22:11:09 gafton Exp $

DEST	= /etc/sysconfig/rhn-satellite-prep
INSTALL_DEST = $(PREFIX)/$(DEST)

FILES	= $(shell find etc -type f | grep -v "/CVS/")
RULES	= satellite-rules.conf

all : clean $(FILES) $(RULES)

# XXX: we should be putting here the rule to update the $(RULES) file
$(RULES) : $(FILES)

install : $(INSTALL_DEST) $(FILES) $(RULES)
	tar cf - $(FILES) | tar xvf - -C $(INSTALL_DEST)
	install -m 644 $(RULES) version $(INSTALL_DEST)

$(INSTALL_DEST) :
	install -d -m 755 $@

clean : 
	@find . -name \*~ -type f -exec rm -fv {} \;
