#!/bin/sh
#
# rhn-proxy      Startup script for RHN Proxy
#
#   chkconfig: - 74 26
#   description: start and stop the RHN Proxy Service

SERVICES="squid httpd jabberd MonitoringScout"

. /etc/init.d/functions

RETVAL=0

forward_services() {
    ACTION="$1"

    for service in $SERVICES; do
	if [ -e /etc/init.d/$service ]; then
	    /sbin/service $service $ACTION
	    let RETVAL=$RETVAL+$?
	fi
	if [ $RETVAL -gt 0 ]; then
	    RETVAL=1
	fi
    done
}

reverse_services() {
    ACTION="$1"

    for service in $(echo $SERVICES | tac -s" "); do
	if [ -e /etc/init.d/$service ]; then
	    /sbin/service $service $ACTION
            let RETVAL=$RETVAL+$?
        fi
        if [ $RETVAL -gt 0 ]; then
            RETVAL=1
        fi
    done
}

start() {
        echo "Starting rhn-proxy..."
	forward_services start
	echo "Done."

        [ $RETVAL = 0 ] && touch /var/lock/subsys/rhn-proxy
}

stop() {
        echo "Shutting down rhn-proxy..."
	reverse_services stop
	echo "Done."

        [ $RETVAL = 0 ] && rm -f /var/lock/subsys/rhn-proxy
}

status() {
    forward_services status
}

restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
	start
        ;;
    stop)
	stop
        ;;
    status)
	status
        ;;
    restart)
        restart
        ;;
    condrestart)
        [ -f /var/lock/subsys/rhn-proxy ] && restart || :
	;;
    *)
        echo "Usage: rhn-proxy {start|stop|status|restart|condrestart}"
        exit 1
        ;;
esac
exit $RETVAL
