# Makefile for the xmlrpc module
#
# $Id$

TOP	= ../../..
SUBDIR	= server/handlers/xmlrpc

FILES	= __init__ country queue registration states up2date errata \
	  getMethod proxy get_handler abrt scap

include $(TOP)/Makefile.defs

