-- created by Oraschemadoc Fri Mar  2 05:57:48 2012
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE INDEX "SPACEWALK"."RHN_SP_AC_SAID_PAID_PREF" ON "SPACEWALK"."RHNSERVERPACKAGEARCHCOMPAT" ("SERVER_ARCH_ID", "PACKAGE_ARCH_ID", "PREFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 
/
