-- created by Oraschemadoc Fri Mar  2 05:57:46 2012
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE UNIQUE INDEX "SPACEWALK"."RHN_SET_USER_LABEL_ELEM_UNQ" ON "SPACEWALK"."RHNSET" ("USER_ID", "LABEL", "ELEMENT", "ELEMENT_TWO", "ELEMENT_THREE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 
/
