-- created by Oraschemadoc Thu Apr 21 10:03:58 2011
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE UNIQUE INDEX "SPACEWALK"."RHN_ORGCSETTINGS_OID_CID_UQ" ON "SPACEWALK"."RHNORGCHANNELSETTINGS" ("ORG_ID", "CHANNEL_ID", "SETTING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 
/
