-- created by Oraschemadoc Fri Jan 22 13:40:31 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE INDEX "MIM_H1"."RHN_SP_AC_PAID_SAID_PREF" ON "MIM_H1"."RHNSERVERPACKAGEARCHCOMPAT" ("PACKAGE_ARCH_ID", "SERVER_ARCH_ID", "PREFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
