-- created by Oraschemadoc Fri Jan 22 13:40:23 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE UNIQUE INDEX "MIM_H1"."RHN_RTE_RTID_SGTID_UQ_IDX" ON "MIM_H1"."RHNREGTOKENENTITLEMENT" ("REG_TOKEN_ID", "SERVER_GROUP_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATA_TBS" 
 
/
