-- created by Oraschemadoc Thu Apr 21 10:03:49 2011
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE INDEX "SPACEWALK"."RHN_CF_MEMBER_CF_C_IDX" ON "SPACEWALK"."RHNCHANNELFAMILYMEMBERS" ("CHANNEL_FAMILY_ID", "CHANNEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 
/
