-- created by Oraschemadoc Tue Nov  2 08:32:56 2010
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE UNIQUE INDEX "SPACEWALK"."RHN_COPTR_ID_P_NAME_P_TYPE_PK" ON "SPACEWALK"."RHN_COMMAND_PARAM_THRESHOLD" ("COMMAND_ID", "PARAM_NAME", "PARAM_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 
/
