#!/usr/bin/python
#
# Wrapper for rhnpush.py
#
# $Id$

import os
import sys
sys.path.append("/usr/share/rhn/")

mod_name = os.path.basename(sys.argv[0])
try:
    mod = __import__("rhnpush." + mod_name)
except ImportError, e:
    sys.stderr.write("Unable to load module %s\n" % mod_name)
    sys.stderr.write(str(e) + "\n")
    sys.exit(1)
mod = getattr(mod, mod_name)

if __name__ == '__main__':
    try:
        sys.exit(mod.main() or 0)
    except KeyboardInterrupt, e:
        sys.stderr.write("\nUser interrupted process.\n")
        sys.exit(0)
    except SystemExit, e:
        sys.exit(e.code)
    except Exception, e:
        sys.stderr.write("\nERROR: unhandled exception occurred: (%s).\n" % e)
        sys.exit(-1)

