.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH rhn.conf 5 "1 March 2011" Linux "File Formats and Conventions"
.SH NAME
rhn.conf \- Configuration file for Spacewalk/Red Hat Satellite Server
.SH SYNOPSIS
.B /etc/rhn/rhn.conf
.SH DESCRIPTION
.B rhn.conf
is a configuration file used for several services in Spacewalk/Red Hat Satellite server.
.SH FORMAT
.P
Format of /etc/rhn/rhn.conf is very simple. Each line is either a comment or a directive.  Comment lines start with a # and are ignored. A directive line has the format below:
.TP
parameter = value
.SH OPTIONS
.P
Spacewalk/Red Hat Satellite includes dozens other options in \fB/usr/share/rhn/config-defaults/*.conf\fR which administrator can override in /etc/rhn/rhn.conf,
but \fB*** JUST CHANGE THOSE PARAMETERS IF YOU REALLY KNOW WHAT ARE YOU DOING! *** \fR

.P
The most important tunables parameters in \fB/etc/rhn/rhn.conf\fR are listed below:

.TP
.B "traceback_mail"
Define which mail address will be used to notify about reports, warnings and Web traceback errors.
Use commas to separate mail addresses.
.IP
.B Default:
none

.TP
.B "mount_point"
Define the directory used to store the RPM package files offered by software channels.
As a recommendation, we suggest at least 30 GB storage per software
channel (including Base and child channels).
.IP
.B Default:
/var/satellite

.TP
.B "kickstart_mount_point"
Define the directory used to store the kickstart trees.
.IP
.B Default:
/var/satellite

.TP
.B "repomd_cache_mount_point"
Define the directory used to store the packages, errata, channels, kickstart trees and also store the repositories metadata
cache information. It is generated when using Spacewalk/Red Hat Satellite on demand when the client asks for thoses files.
These cache files are stored in
.B /var/cache/rhn
and the storage needs of this directory will vary greatly. We suggest at least 10GB of space in
.B /var/cache/rhn
on Spacewalk/Red Hat Satellite server. Very large environments will need to increase the amount of space in
.B /var/cache/rhn
that directory.

.IP
.B Default:
/var/cache

.TP
.B "server.satellite.rhn_parent"
This parameter determines the parent RHN Classic/Red Hat Satellite whose packages will be downloaded or synced. This parameter usually points to RHN Hosted,
.B rhn.redhat.com
.IP
.B Default:
none

.TP
.B "server.satellite.http_proxy"
This parameter determines the HTTP proxy used to download or sync packages from. Enter the IP address or HTTP Proxy FQDN address.
.IP
.B Default:
none

.TP
.B "server.satellite.http_proxy_username"
This parameter determines the HTTP proxy username.
.IP
.B Default:
none

.TP
.B "server.satellite.http_proxy_password"
This parameter determines the HTTP proxy password.
.IP
.B Default:
none

.TP
.B "server.satellite.ca_chain"
This parameter specify the SSL certificate used for communicationg with
.B server.satellite.rhn_parent.
The default SSL CA certificate points to RHN Hosted.
.IP
.B Default:
/usr/share/rhn/RHNS-CA-CERT

.TP
.B "debug"
.P
.RS
This parameter determines debug level used by Spacewalk/Red Hat Satellite processes.
Please, keep in mind that raising up this value will generate a very verbose logs, which is only useful for debugging
purposes.
.B Use it carefully!
Valid values:
.B [0-6]
.RE
.B
.P
.RS
0 low verbosity
.RE
.RS
6 high verbosity
.RE
.IP
.B Default:
1

.TP
.B "disconnected (boolean)"
This parameter controls whether server is running in connected or disconnected mode.
When running in disconnected mode, the RHN Entitlement Certificate is activated locally
but not on remote RHN Servers.
.IP
.B Default:
0

.TP
.B "enable_snapshots" (boolean)
This parameter controls whether server is allowed to perform system snapshots.
.IP
.B Default:
1

.TP
.B "pam_auth_service"
Spacewalk/Red Hat Satellite supports network-based authentication systems via Pluggable Authentication Modules (PAM).
Spacewalk/Red Hat Satellite supports LDAP, Kerberos, Directory Server and other network-based authentication
systems. To enable Spacewalk/Red Hat Satellite to use PAM and your organization's authentication infrastructure, follow the
steps below:
.RS
.IP \(bu 3
make sure that pam\-devel package is installed
.IP \(bu 3
set the parameter \fBpam_auth_service = rhn\-satellite\fR
.IP \(bu 3
create a file in \fB/etc/pam.d/rhn\-satellite\fR which contains:

.B For LDAP authentication on 32\-bit systems:
.nf
#%PAM-1.0
auth         required      /lib/security/pam_env.so
auth         sufficient    /lib/security/pam_ldap.so no_user_check
auth         required      /lib/security/pam_deny.so
account      required      /lib/security/pam_ldap.so no_user_check
.fi

.B For LDAP authentication on 64\-bit systems:
.nf
#%PAM-1.0
auth      required      /lib64/security/pam_env.so
auth      sufficient    /lib64/security/pam_ldap.so no_user_check
auth      required      /lib64/security/pam_deny.so
account   required      /lib64/security/pam_ldap.so no_user_check
.fi

.IP \(bu 3
restart Spacewalk/Red Hat Satellite service
.RE
.IP
.B Default:
none

.TP
.B "enable_nvrea" (boolean)
This parameter controls whether server will allow package uploads for same NVREA
(Name, Version, Release, Epoch, Arch) but different vendors.
.RS
.IP \(bu 3
Spacewalk Server
.RS
.IP \(bu 3
\fBDefault:\fR 1
.RE
.IP \(bu 3
Red Hat Satellite Server
.RS
.IP \(bu 3
\fBDefault:\fR 0
.RE
.RE

.TP
.B "web.maximum_config_file_size" (bytes)
This parameter controls which is the maximum allowed size for configuration files.
.IP
.B Default:
32768

.TP
.B "java.taskomatic_channel_repodata_workers" (integer)
This parameter controls how many repodata workers should generate repodata information concurrently.
If the number of repodata workers running on the system are bigger than defined on
.B java.taskomatic_channel_repodata_workers,
then the job will be queued.
.IP
.B Default:
2

.TP
.B "taskomatic.maxmemory" (integer)
The maximum amount of memory (MB) that Taskomatic can use. If you find that Taskomatic is running out of memory, consider increasing this.
.IP
.B Default:
1024


.SS Database Options
.TP
.B "db_backend"
Determine the database backend. Valid backends are:
.B postgresql
or
.B oracle
.IP

.TP
.B "db_user"
Determine the user for database connections.
.IP

.TP
.B "db_password"
Determine the password for database connections.
.IP

.TP
.B "db_name"
Determine the database name.
.IP

.TP
.B "db_host"
Determine the database host.
.IP

.TP
.B "db_port"
Determine the database port.
.IP

.SH Inter-Red Hat Satellite Sync (ISS)
The ability of synchronize two Spacewalk/Red Hat Satellites servers
is called Inter-Red Hat Satellite Sync (ISS)  which allows to synchronize channels
from the master Red Hat Satellite to slave servers, simplifying the
process of coordinating contents from one Spacewalk/Red Hat Satellite source to another or several others. Note: Several options that used to be available in rhn.conf are now only set by the Satellite Admin in the Admin -> ISS Configuration pages in the web interface. 

.SS Master Spacewalk/Red Hat Satellite Servers

.TP
.B "disable_iss"
If set to 1, then no slave will be able to sync from this server
this option does not affect the ability to sync to this server from
another spacewalk (or hosted).
.IP
.B Default:
0

.SH FILES
.I /etc/rhn/rhn.conf
.RS
Configuration file for Spacewalk/Red Hat Satellite server. See
.BR rhn.conf (5)
for further details.

.SH ADDITIONAL DOCS
For additional documentation, please visit:
.P
.RE
.B Red Hat Satellite Documentation
.RS
http://docs.redhat.com/docs/en-US/Red_Hat_Network_Satellite/index.html
.P
.RE
.B Spacewalk Documentation
.RS
http://www.spacewalkproject.org/documentation.html
.P

.SH BUGS
Please, if you find a bug or want a new feature fill a bug at
.BI http://bugzilla.redhat.com

.SH AUTHORS
Marcelo Moreira de Mello <mmello@redhat.com>

.SH "SEE ALSO"
.BR rhn.conf (5),
.BR rhn-activate-satellite (8),
.BR db-control (1),
.BR pam (8)
