#!/usr/bin/python

import sys
import getopt
from pprint import pprint
from spacewalk.common.rhnConfig import PRODUCT_NAME

try:
    from spacewalk.server import rhnSQL
except:
    print "Couldn't load needed libs, Are you sure you are running this on a satellite?"
    sys.exit(1)


rhnSQL.initDB()


def main():
    printAcrossSatelliteUsage()
    list = listOfOrgs()
    for org in list:
        printOrgHeader(org)
        printSystemEnts(org['id'])
    printOrgFooter()


def printAcrossSatelliteUsage():
    # This prints summary displayed on
    # https://satellite.fqdn/rhn/admin/multiorg/SystemEntitlements.do and
    # https://satellite.fqdn/rhn/admin/multiorg/SoftwareEntitlements.do which
    # is Channel and Entitlement usage across all organizations

    print ("\nSystem Entitlements Across " + PRODUCT_NAME + " :")
    query = "SELECT  sgt.label as label,SUM(sg.max_members) as total,SUM(sg.current_members) as used,(SELECT (sg2.max_members) - (sg2.current_members) FROM rhnServerGroup sg2 inner join  rhnServerGroupType sgt2 on sg2.group_type = sgt2.id WHERE sg2.org_ID = 1 AND sgt2.label = sgt.label) as available FROM rhnServerGroup sg inner join rhnServerGroupType sgt on sgt.id = sg.group_type GROUP BY sgt.label, sgt.id ORDER BY sgt.label"
    print("%35s %s %s %s" % ("System Entitlement", "  Total  ", "  Used  ", " Available "))
    print("%35s %s %s %s" % ("------------------", "  -----  ", "  ----  ", " --------- "))
    list = run_query(query)
    for item in list:
        print("%35s %7s %8s %10s" % (item['label'], str(item['total']), str(item['used']), str(item['available'])))


def printOrgHeader(org):
    print("\n")
    print("=" * 40)
    print(org['name'] + " (" + str(org['id']) + "):\n")


def printOrgFooter():
    print("=" * 40)
    print("\n")


def printSystemEnts(id):
    print("%35s %s %s" % ("System Entitlement", "Used", "Max Members"))
    print("%35s %s %s" % ("------------------", "----", "-----------"))
    query = """select T.label, G.current_members,G.max_members
                 from rhnServerGroup G inner join rhnServerGroupType T  on G.group_type = T.id
                 where org_id = %d order by T.label """ % (id)
    list = run_query(query)
    for item in list:
        print("%35s %3s %8s" % (item['label'], str(item['current_members']), str(item['max_members'])))
    print("")
    return


def listOfOrgs():
    query = "select id, name from web_customer"
    return run_query(query)


def run_query(query):
    _get_data_sql = rhnSQL.prepare(query)
    _get_data_sql.execute()
    return _get_data_sql.fetchall_dict()


if __name__ == "__main__":
    main()
