#!/usr/bin/python
#
# Script to synchronize RHN meta data between Red Hat and a local RHN Satellite.
#
# Copyright (c) 2008 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public License,
# version 2 (GPLv2). There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
# along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
# 
# Red Hat trademarks are not licensed under GPLv2. No permission is
# granted to use or replicate Red Hat trademarks that are incorporated
# in this software or its documentation. 
#

# This program syncs the kickstart distros
# and profiles from spacewalk to cobbler
# useful in a upgrade process
import optparse
import xmlrpclib



def setup(parser):
    parser.add_option('-s','--spacewalk',dest='host',
            default='localhost',help='spacewalk host name')
    parser.add_option("-u", "--username", dest="login", 
                        help='spacewalk username')

    parser.add_option("-p","--password", dest="password",
                                help="spacewalk password")

def sync(user, password, host):
    client = xmlrpclib.Server("http://%s/rpc/api" % host)
    key = client.auth.login(user, password)
    print "Syncing kickstart distributions..."
    client.cobbler.syncDistributions(key)
    print "Syncing kickstart profiles..."
    client.cobbler.syncProfiles(key)
    client.auth.logout(key)
    print "sync done"

def main():
    parser = optparse.OptionParser()
    setup(parser)
    (options, args) = parser.parse_args()
    user = options.login
    if not user:
        user = raw_input("Enter login: ") 
    password = options.password
    if not password:
        password  = raw_input("Enter password: ")
    sync(user, password, options.host)

if __name__ == "__main__":
    main()
