#!/usr/bin/python -u
#
# Copyright (c) 2008--2011 Red Hat, Inc.
# Copyright (c) 2011 SUSE LINUX Products GmbH, Nuernberg, Germany.
#
# This software is licensed to you under the GNU General Public License,
# version 2 (GPLv2). There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
# along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
#
# Red Hat trademarks are not licensed under GPLv2. No permission is
# granted to use or replicate Red Hat trademarks that are incorporated
# in this software or its documentation.
#

LOCK = None
import sys
import os
import socket
from optparse import OptionParser


def systemExit(code, msg=None):
    "Exit with a code and optional message(s). Saved a few lines of code."
    sys.stderr.write(str(msg)+'\n')
    sys.exit(code)

try:
    from rhn import rhnLockfile
    from spacewalk.common.rhnConfig import CFG
    from spacewalk.common.rhnTB import fetchTraceback
    from spacewalk.satellite_tools import reposync
except KeyboardInterrupt:
    systemExit(0, "\nUser interrupted process.")
except ImportError:
    systemExit(1, "Unable to find code tree.\n"
               "Path not correct? " + sys.path)

def releaseLOCK():
    global LOCK
    if LOCK:
        LOCK.release()
        LOCK = None

def main():

    # quick check to see if you are a super-user.
    if os.getuid() != 0:
        systemExit(8, 'ERROR: must be root to execute.')

    global LOCK
    try:
        LOCK = rhnLockfile.Lockfile('/var/run/spacewalk-repo-sync.pid')
    except rhnLockfile.LockfileLockedException:
        systemExit(1, "ERROR: attempting to run more than one instance of "
                      "spacewalk-repo-sync Exiting.")

    parser = OptionParser()
    parser.add_option('-u', '--url', action='store', dest='url',
                      help='The url to sync')
    parser.add_option('-c', '--channel', action='store',
                      dest='channel_label',
                      help='The label of the channel to sync packages to')
    parser.add_option('-t', '--type', action='store', dest='repo_type',
                      help='The type of repo, currently only "yum" is supported',
                      default='yum')
    parser.add_option('-f', '--fail', action='store_true', dest='fail',
                      default=False,
                      help="If a package import fails, fail the entire operation")
    parser.add_option('-q', '--quiet', action='store_true', dest='quiet',
                      default=False, help="Print no output, still logs output")
    parser.add_option('-i', '--include', action='callback',
                      callback=reposync.set_filter_opt, type='str', nargs=1,
                      dest='filters', default=[],
                      help="List of included packages")
    parser.add_option('-e', '--exclude', action='callback',
                      callback=reposync.set_filter_opt,
                      type='str', nargs=1, dest='filters', default=[],
                      help="List of excluded packages")
    (options, args) = parser.parse_args()

    if not options.channel_label:
        systemExit(1, "--channel must be specified")

    sync = reposync.RepoSync(channel_label=options.channel_label,
                      repo_type=options.repo_type,
                      url=options.url,
                      fail=options.fail,
                      quiet=options.quiet,
                      filters=options.filters)
    sync.sync()
    releaseLOCK()
    return 0


if __name__ == '__main__':
    try:
        sys.exit(abs(main() or 0))
    except KeyboardInterrupt:
        systemExit(0, "\nUser interrupted process.")
    except SystemExit, e:
        releaseLOCK()
        sys.exit(e.code)
    except Exception, e:
        releaseLOCK()
        raise
