%{!?perlgen:%define perlgen 5.8}

Name: perl-GD2
Source9999: version
Version: %(echo `awk '{ print $1 }' %{SOURCE9999}`)
Release: %(echo `awk '{ print $2 }' %{SOURCE9999}`)%{?dist}
Packager: cturner@redhat.com
Summary: GD Perl module
License: distributable
Group: Development/Libraries
URL: http://search.cpan.org/search?mode=module&query=GD
BuildRoot: %{_tmppath}/%{name}-root
BuildRequires: gd-devel >= 2.0.28
BuildRequires: libpng, libjpeg
%if "%{perlgen}" == "5.8"
BuildRequires: perl >= 2:5.8.0
%else
BuildRequires: perl >= 1:5.6.0
%endif
Source0: GD-%{version}.tar.gz
Patch0: perl-GD-1.40-noxpm.patch

%description
GD Perl module
%prep
%setup -q -n GD-%{version} 
#%patch0 -p1 -b .noxpm

%build
%if "%{perlgen}" == "5.8"
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL PREFIX=$RPM_BUILD_ROOT%{_prefix} < /dev/null
%else
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL < /dev/null
%endif
make
# make test

%clean
rm -rf $RPM_BUILD_ROOT
%install

rm -rf $RPM_BUILD_ROOT
eval `perl '-V:installarchlib'`
mkdir -p $RPM_BUILD_ROOT/$installarchlib
%if "%{perlgen}" == "5.8"
make install
%else
make install PREFIX=$RPM_BUILD_ROOT%{_prefix}
%endif

[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress

rm -f `find $RPM_BUILD_ROOT -type f -name perllocal.pod -o -name .packlist`
find $RPM_BUILD_ROOT/usr -type f -print | \
        sed "s@^$RPM_BUILD_ROOT@@g" | \
        grep -v perllocal.pod | \
        grep -v "\.packlist" > perl-GD2-%{version}-filelist
if [ "$(cat perl-GD2-%{version}-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit 1
fi

%files -f perl-GD2-%{version}-filelist
%defattr(-,root,root)

%changelog
* Fri Jun 27 2008 Jan Pazdziora 2.17-11
- Fixing %files not to own perllocal.pod and directories

* Fri Jul 12 2002 cturner@redhat.com
- Specfile autogenerated

