Name: perl-Crypt-RIPEMD160
Version: 0.04
Release: 15%{?dist}
Summary: Crypt-RIPEMD160 Perl module
License: GPL+ or Artistic
Group: Development/Libraries
URL: http://search.cpan.org/search?mode=module&query=Crypt%3a%3aRIPEMD160
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n) 
BuildRequires: perl(ExtUtils::MakeMaker)
Requires: perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Source0: http://search.cpan.org/CPAN/authors/id/C/CH/CHGEUER/Crypt-RIPEMD160-%{version}.tar.gz
Patch0: perl-Crypt-RIPEMD160-utf.patch
Patch1: ripemd160-64bit-unclean.patch

%description
Crypt-RIPEMD160 Perl module
%prep
%setup -q -n Crypt-RIPEMD160-%{version} 
%patch0 -p1 -b .utf
%patch1 -p1 -b .unclean

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT
make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT
find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} ';'
find $RPM_BUILD_ROOT -type f -name '*.bs' -a -size 0 -exec rm -f {} ';'
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null ';'
chmod -R u+w $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Crypt/
%{_mandir}/man3/*.3*

%changelog
* Thu Oct 16 2008 Milan Zazrivec 0.04-15
- bumped release for minor release tagging & build

* Tue Aug 26 2008 Dennis Gilmore <dgilmore@redhat.com> - 0.04-14
- clean up spec 
- fix license 

* Mon Aug 19 2002 cturner@redhat.com
- Specfile autogenerated

