Name: perl-Crypt-RIPEMD160
Source9999: version
Version: %(echo `awk '{ print $1 }' %{SOURCE9999}`)
Release: %(echo `awk '{ print $2 }' %{SOURCE9999}`)%{?dist}
Summary: Crypt-RIPEMD160 Perl module
License: distributable
Group: Development/Libraries
URL: http://search.cpan.org/search?mode=module&query=Crypt%3a%3aRIPEMD160
BuildRoot: %{_tmppath}/%{name}-root
BuildRequires: perl >= 2:5.8.0
Requires: %(perl -MConfig -le 'if (defined $Config{useithreads}) { print "perl(:WITH_ITHREADS)" } else { print "perl(:WITHOUT_ITHREADS)" }')
Requires: %(perl -MConfig -le 'if (defined $Config{usethreads}) { print "perl(:WITH_THREADS)" } else { print "perl(:WITHOUT_THREADS)" }')
Requires: %(perl -MConfig -le 'if (defined $Config{uselargefiles}) { print "perl(:WITH_LARGEFILES)" } else { print "perl(:WITHOUT_LARGEFILES)" }')
Source0: Crypt-RIPEMD160-0.04.tar.gz
Patch0: perl-Crypt-RIPEMD160-utf.patch
Patch1: ripemd160-64bit-unclean.patch

%description
Crypt-RIPEMD160 Perl module
%prep
%setup -q -n Crypt-RIPEMD160-%{version} 
%patch0 -p1 -b .utf
%patch1 -p1 -b .unclean

%build
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL PREFIX=$RPM_BUILD_ROOT/usr 
make
make test

%clean
rm -rf $RPM_BUILD_ROOT
%install

rm -rf $RPM_BUILD_ROOT
eval `perl '-V:installarchlib'`
mkdir -p $RPM_BUILD_ROOT/$installarchlib
make install

[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress

rm -f `find $RPM_BUILD_ROOT -type f -name perllocal.pod -o -name .packlist`
find $RPM_BUILD_ROOT/usr -type f -print | \
	sed "s@^$RPM_BUILD_ROOT@@g" | \
	grep -v perllocal.pod | \
	grep -v "\.packlist" > Crypt-RIPEMD160-%{version}-filelist
if [ "$(cat Crypt-RIPEMD160-%{version}-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit 1
fi

%files -f Crypt-RIPEMD160-%{version}-filelist
%defattr(-,root,root)

%changelog
* Mon Aug 19 2002 cturner@redhat.com
- Specfile autogenerated

