#!/usr/bin/python

import sys
import rpm

def print_help(stream=sys.stdout):
    stream.write("Usage: %s <epoch1> <version1> <release1> <epoch2> <version2> <release2>\n" % sys.argv[0])

def main():
    if len(sys.argv) != 7:
        print_help(sys.stderr)
        return 1
    epoch1 = normalize_epoch(sys.argv[1])
    version1 = sys.argv[2]
    release1 = sys.argv[3]
    epoch2 = normalize_epoch(sys.argv[4])
    version2 = sys.argv[5]
    release2 = sys.argv[6]

    label1 = (epoch1, version1, release1)
    label2 = (epoch2, version2, release2)

    print rpm.labelCompare(label1, label2)

def normalize_epoch(epoch):
    if epoch == '(none)':
        return ""
    return epoch

if __name__ == '__main__':
    sys.exit(main() or 0)
