#!/bin/sh -x
#
# Startup script for the NOCpulse Scheduling Kernel
#
# chkconfig: 345 95 15
# description: SSL bridge
# processname: ssl_bridge.pl


# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
case "$1" in
  start)
	echo -n "Starting ssl_bridge"
	su nocpulse -c "/opt/home/nocpulse/bin/ssl_bridge.pl >/dev/null &"
	echo_success
	echo
	;;
  stop)
  	killall ssl_bridge.pl
	exit $?
	;;
  restart)
	$0 stop
	$0 start
	exit $?
	;;
  status)
	status ssl_bridge.pl
	;;
  *)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
esac

exit 0
